# app/core/conversation/brain.py
"""
Conversation Brain - Health Care Assistant (COMMANDER)

RESPONSIBILITY:
- Entry point for all chat interactions
- Receives: user_id, user_message
- Determines current conversation stage
- Manages three types of memory: SHORT-TERM, MEDIUM-TERM, LONG-TERM
- Requests text from prompts.py (AI-generated, NO hardcoded text)
- Updates memory via memory.py
- Proactively initiates conversations for health check-ins
- Provides personalized health, wellness, and fitness suggestions
- Returns assistant message + metadata
- NO database queries directly
- NO hardcoded text - all text generated by AI
"""

from typing import Dict, Optional
from sqlalchemy.orm import Session
from app.core.conversation.stages import ConversationStage, get_stage, transition_stage
from app.core.conversation.memory import ConversationMemory
from app.core.conversation.context import ConversationContext
from app.core.conversation.prompts import ConversationPrompts
from app.models import User


class ConversationBrain:
    """Central decision engine for all conversation interactions"""
    
    def __init__(self, db: Session, language: str = "en"):
        self.db = db
        self.language = language
        self.memory = ConversationMemory(db)
        self.prompts = ConversationPrompts(language)
    
    def process_message(
        self,
        user_id: int,
        user_message: str
    ) -> Dict[str, any]:
        """
        Process user message and generate Sedi's response.
        
        Flow:
        1. Get current conversation stage
        2. Build conversation context
        3. Generate response using prompts
        4. Save conversation to memory
        5. Check for stage transition
        6. Return response with metadata
        
        Args:
            user_id: User ID
            user_message: User's message
        
        Returns:
            Dict with:
            - message: Sedi's response text
            - language: Language code
            - stage: Current conversation stage
            - metadata: Optional metadata (tone, intent, etc.)
        """
        # TEMP DEBUG: Log entry
        print(f"[BRAIN DEBUG] ===== PROCESSING MESSAGE =====")
        print(f"[BRAIN DEBUG] user_id={user_id}, message={user_message[:50]}...")
        
        # Validate user exists
        user = self.db.query(User).filter(User.id == user_id).first()
        if not user:
            print(f"[BRAIN DEBUG] ERROR: User not found")
            return {
                "message": self._get_error_message("user_not_found"),
                "language": self.language,
                "stage": None,
                "error": "User not found"
            }
        
        # Get current stage (BEFORE save - to know where we are)
        current_stage = get_stage(user_id, self.db)
        print(f"[BRAIN DEBUG] Current stage: {current_stage.value}")
        
        # Build context (BEFORE save - includes previous state)
        context = ConversationContext(
            user_id=user_id,
            stage=current_stage,
            memory=self.memory,
            user_message=user_message
        )
        context_data = context.build()
        print(f"[BRAIN DEBUG] Context built - conversation_count={context_data.get('conversation_count', 0)}")
        
        # Determine engagement level (minimal logic - selection only)
        engagement_level = self._determine_engagement_level(context_data)
        print(f"[BRAIN DEBUG] Engagement level: {engagement_level}")
        
        # Generate response with engagement-aware prompts
        sedi_response = self.prompts.generate_response(
            context_data, 
            user_message,
            engagement_level
        )
        print(f"[BRAIN DEBUG] Response generated (length={len(sedi_response)})")
        
        # CRITICAL FIX: Save conversation to memory BEFORE checking stage transition
        # This ensures memory_count is updated for next request
        self.memory.save_conversation(
            user_id=user_id,
            user_message=user_message,
            sedi_response=sedi_response,
            language=self.language
        )
        
        # Check for stage transition (AFTER save - uses updated memory_count)
        new_stage = transition_stage(current_stage, user_id, self.db)
        print(f"[BRAIN DEBUG] New stage: {new_stage.value}")
        print(f"[BRAIN DEBUG] ===== MESSAGE PROCESSED =====")
        
        # Build metadata
        metadata = {
            "stage": new_stage.value,
            "conversation_count": context_data.get("conversation_count", 0) + 1,
            "tone": self._infer_tone(sedi_response),
        }
        
        return {
            "message": sedi_response,
            "language": self.language,
            "stage": new_stage.value,
            "metadata": metadata
        }
    
    def get_greeting(self, user_id: int) -> Dict[str, any]:
        """
        Generate initial greeting for user.
        
        Used when user first opens chat or returns after absence.
        
        Args:
            user_id: User ID
        
        Returns:
            Dict with greeting message and metadata
        """
        # Get current stage
        stage = get_stage(user_id, self.db)
        
        # Build context
        context = ConversationContext(
            user_id=user_id,
            stage=stage,
            memory=self.memory
        )
        context_data = context.build()
        
        # Generate greeting based on stage
        greeting = self._generate_greeting(context_data, stage)
        
        return {
            "message": greeting,
            "language": self.language,
            "stage": stage.value,
            "metadata": {
                "type": "greeting",
                "stage": stage.value
            }
        }
    
    def _generate_greeting(
        self,
        context: Dict[str, any],
        stage: ConversationStage
    ) -> str:
        """
        Generate greeting message - Sedi introduces herself and explains how she can help.
        
        CRITICAL: Sedi must be a conversation initiator and explain:
        - Who she is (health care assistant)
        - How she can improve user's quality of life
        - Through health care suggestions, lifestyle improvements, and smart device monitoring
        """
        user_name = context.get("user_name") or "friend"
        time_since = context.get("time_since_last")
        engagement_level = self._determine_engagement_level(context)
        
        # Build comprehensive greeting prompt based on stage
        if stage == ConversationStage.FIRST_CONTACT:
            # FIRST CONTACT: Sedi must introduce herself and explain her purpose
            greeting_prompt = {
                "en": f"""Introduce yourself as Sedi, an AI-powered health care assistant.

Write a warm, friendly, and natural introduction that:
1. Greets them warmly: "Hello! I'm Sedi, your AI-powered health care assistant."
2. Explains your purpose naturally (not as a list, but as a flowing conversation):
   - You help improve their quality of life
   - Through personalized health care suggestions and lifestyle improvements
   - By continuously monitoring their daily health data through smart devices
3. Explains how you work briefly:
   - You learn about their lifestyle through natural conversation
   - You use smart devices to track vital signs (heart rate, temperature, SpO2)
4. Ends with asking their name: "Can I know your name?" or "What's your name?"

Be conversational, warm, and engaging. Make it feel like a real person talking, not a robot. Keep it concise but complete (max 250 characters). End with asking for their name naturally.""",
                "fa": f"""خودت را به عنوان صدی، یک دستیار مراقبت سلامت با هوش مصنوعی معرفی کن.

یک معرفی گرم، دوستانه و طبیعی بنویس که:
1. با گرمی به آن‌ها سلام کند: "سلام! من صدی هستم، دستیار مراقبت سلامت شما با هوش مصنوعی."
2. هدفت را به طور طبیعی توضیح دهد (نه به صورت لیست، بلکه به صورت یک گفتگوی روان):
   - کمک به بهبود کیفیت زندگی‌شان
   - از طریق پیشنهادهای شخصی‌سازی شده مراقبت سلامت و بهبود سبک زندگی
   - با پایش پیوسته داده‌های سلامت روزمره‌شان از طریق گجت‌های هوشمند
3. نحوه کارت را مختصر توضیح دهد:
   - از طریق گفتگوی طبیعی درباره سبک زندگی‌شان یاد می‌گیری
   - از گجت‌های هوشمند برای ثبت علائم حیاتی (ضربان قلب، دما، SpO2) استفاده می‌کنی
4. با پرسیدن نامشان تمام شود: "میتونم اسمتون را بدونم؟" یا "اسم شما چیه؟"

گفتگویی، گرم و جذاب باش. طوری باش که مثل یک انسان واقعی صحبت می‌کنی، نه ربات. مختصر اما کامل نگه دار (حداکثر 250 کاراکتر). با پرسیدن نامشان به طور طبیعی تمام کن.""",
                "ar": f"""قدم نفسك كصدي، مساعد رعاية صحية مدعوم بالذكاء الاصطناعي.

اكتب مقدمة دافئة وودودة وطبيعية:
1. حييهم بحرارة: "مرحباً! أنا صدي، مساعد رعاية صحية الخاص بك المدعوم بالذكاء الاصطناعي."
2. اشرح هدفك بشكل طبيعي (ليس كقائمة، بل كمحادثة متدفقة):
   - مساعدتهم على تحسين جودة حياتهم
   - من خلال اقتراحات رعاية صحية مخصصة وتحسينات نمط الحياة
   - من خلال مراقبة مستمرة لبيانات صحتهم اليومية عبر الأجهزة الذكية
3. اشرح كيف تعمل باختصار:
   - تتعلم عن نمط حياتهم من خلال محادثة طبيعية
   - تستخدم الأجهزة الذكية لتتبع العلامات الحيوية (معدل ضربات القلب، درجة الحرارة، SpO2)
4. انتهي بطلب اسمهم: "هل يمكنني معرفة اسمك؟" أو "ما اسمك؟"

كن محادثاً ودافئاً وجذاباً. اجعله يبدو كأن شخصاً حقيقياً يتحدث، وليس روبوتاً. اجعله مختصراً لكن كاملاً (بحد أقصى 250 حرف). انتهي بطلب اسمهم بشكل طبيعي."""
            }
        elif time_since:
            # User returning after absence - be warm and check in
            greeting_prompt = {
                "en": f"""Greet {user_name} warmly. You haven't talked in a while. Remind them briefly who you are (Sedi, their health care assistant) and that you're here to help improve their quality of life through health monitoring and lifestyle suggestions. Be warm but not overwhelming. Ask how they've been.""",
                "fa": f"""با {user_name} گرم سلام کن. مدتی است که حرف نزده‌اید. مختصر یادآوری کن که تو کیستی (صدی، دستیار مراقبت سلامت‌شان) و اینجا هستی تا از طریق نظارت سلامت و پیشنهادهای سبک زندگی کیفیت زندگی‌شان را بهبود دهی. گرم باش اما نه بیش از حد. بپرس چطور بوده‌اند.""",
                "ar": f"""حي {user_name} بحرارة. لم تتحدثا منذ فترة. ذكره باختصار من أنت (صدي، مساعد رعاية صحية) وأنك هنا لمساعدتهم على تحسين جودة حياتهم من خلال مراقبة الصحة واقتراحات نمط الحياة. كن دافئاً لكن ليس ساحقاً. اسأل كيف كانوا."""
            }
        else:
            # Regular greeting - proactive health check-in
            greeting_prompt = {
                "en": f"""Greet {user_name} warmly. As their health care assistant, proactively check in on their wellness. You can mention their health data if available, or ask about their day. Be conversational and supportive. Keep it brief (1-2 sentences, max 150 characters).""",
                "fa": f"""با {user_name} گرم سلام کن. به عنوان دستیار مراقبت سلامت‌شان، به صورت فعالانه چک‌آپ تندرستی کن. می‌توانی به داده‌های سلامت‌شان اشاره کنی اگر در دسترس است، یا درباره روزشان بپرسی. گفتگویی و حمایت‌کننده باش. مختصر نگه دار (1-2 جمله، حداکثر 150 کاراکتر).""",
                "ar": f"""حي {user_name} بحرارة. كمساعد رعاية صحية، تحقق بشكل استباقي من صحتهم. يمكنك ذكر بيانات صحتهم إذا كانت متاحة، أو السؤال عن يومهم. كن محادثاً وداعماً. اجعلها مختصرة (1-2 جملة، بحد أقصى 150 حرف)."""
            }
        
        try:
            system_prompt = self.prompts._build_system_prompt(
                stage,
                user_name,
                context.get("conversation_count", 0),
                engagement_level
            )
            
            # Add greeting-specific instruction
            greeting_instruction = {
                "en": "\n\nIMPORTANT: This is a greeting message where you introduce yourself and explain your purpose. Be conversational, warm, and engaging. Make the user want to respond and start a real conversation. Explain clearly how you can help improve their quality of life. CRITICAL: End your message by asking for their name naturally, like 'Can I know your name?' or 'What's your name?' - DO NOT ask 'How can I help you today?'",
                "fa": "\n\nمهم: این یک پیام سلام است که در آن خودت را معرفی می‌کنی و هدفت را توضیح می‌دهی. گفتگویی، گرم و جذاب باش. کاربر را تشویق کن که پاسخ دهد و یک گفتگوی واقعی شروع کند. واضح توضیح بده چگونه می‌توانی کیفیت زندگی‌شان را بهبود دهی. مهم: پیامت را با پرسیدن نامشان به طور طبیعی تمام کن، مثل 'میتونم اسمتون را بدونم؟' یا 'اسم شما چیه؟' - نپرس 'چطور می‌تونم کمکتون کنم؟'",
                "ar": "\n\nمهم: هذه رسالة تحية حيث تقدم نفسك وتشرح هدفك. كن محادثاً ودافئاً وجذاباً. اجعل المستخدم يريد الرد وبدء محادثة حقيقية. اشرح بوضوح كيف يمكنك مساعدتهم على تحسين جودة حياتهم. مهم: انتهي رسالتك بطلب اسمهم بشكل طبيعي، مثل 'هل يمكنني معرفة اسمك؟' أو 'ما اسمك؟' - لا تسأل 'كيف يمكنني مساعدتك اليوم؟'"
            }
            
            system_prompt += greeting_instruction.get(self.language, greeting_instruction["en"])
            
            prompt_text = greeting_prompt.get(self.language, greeting_prompt["en"])
            
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt_text}
            ]
            
            from app.core.conversation.prompts import client as gpt_client
            response = gpt_client.chat.completions.create(
                model="gpt-4o-mini",
                messages=messages,
                temperature=0.8,  # Slightly higher for more natural, engaging greeting
                max_tokens=300,  # Increased for comprehensive introduction
            )
            
            return response.choices[0].message.content.strip()
            
        except Exception as e:
            print(f"[BRAIN GREETING ERROR] {e}")
            # Fallback with introduction
            if stage == ConversationStage.FIRST_CONTACT:
                fallbacks = {
                    "en": "Hello! I'm Sedi, your AI-powered health care assistant. I help improve your quality of life through personalized health suggestions, lifestyle improvements, and continuous monitoring of your daily health data via smart devices. Can I know your name?",
                    "fa": "سلام! من صدی هستم، دستیار مراقبت سلامت شما با هوش مصنوعی. من از طریق پیشنهادهای شخصی‌سازی شده سلامت، بهبود سبک زندگی و پایش پیوسته داده‌های سلامت روزمره‌تان از طریق گجت‌های هوشمند، به بهبود کیفیت زندگی‌تان کمک می‌کنم. میتونم اسمتون را بدونم؟",
                    "ar": "مرحباً! أنا صدي، مساعد رعاية صحية الخاص بك المدعوم بالذكاء الاصطناعي. أساعدك على تحسين جودة حياتك من خلال اقتراحات صحية مخصصة وتحسينات نمط الحياة ومراقبة مستمرة لبيانات صحتك اليومية عبر الأجهزة الذكية. هل يمكنني معرفة اسمك؟"
                }
                return fallbacks.get(self.language, fallbacks["en"])
            return self.prompts._get_fallback_response(stage)
    
    def _determine_engagement_level(self, context: Dict[str, any]) -> str:
        """
        Determine user engagement level based on conversation patterns.
        
        MINIMAL logic - selection only, no complex calculations.
        
        Returns:
            "low": User rarely responds, long gaps
            "normal": Standard engagement
            "high": User is very engaged, frequent responses
        """
        conversation_count = context.get("conversation_count", 0)
        time_since_last = context.get("time_since_last")
        recent_messages = context.get("recent_messages", [])
        
        # Low engagement indicators
        if conversation_count > 0:
            if time_since_last:
                # Parse time delta (format: "X days, Y:Z:W")
                try:
                    days = 0
                    if "day" in time_since_last.lower():
                        days = int(time_since_last.split()[0])
                    if days > 7:  # More than a week
                        return "low"
                except:
                    pass
            
            # Check recent message frequency
            if len(recent_messages) < 2 and conversation_count > 5:
                return "low"
        
        # High engagement indicators
        if len(recent_messages) >= 3 and conversation_count > 3:
            # User has been actively chatting
            return "high"
        
        # Default to normal
        return "normal"
    
    def _infer_tone(self, message: str) -> str:
        """Infer tone from message (simple heuristic)"""
        message_lower = message.lower()
        if any(word in message_lower for word in ["!", "urgent", "important"]):
            return "urgent"
        elif any(word in message_lower for word in ["?", "wonder", "curious"]):
            return "curious"
        elif any(word in message_lower for word in ["😊", "happy", "glad", "great"]):
            return "warm"
        else:
            return "neutral"
    
    def _get_error_message(self, error_type: str) -> str:
        """Get error message based on type"""
        error_messages = {
            "user_not_found": {
                "en": "I'm sorry, I couldn't find your account. Please try again.",
                "fa": "متاسفم، نتوانستم حساب کاربری شما را پیدا کنم. لطفاً دوباره تلاش کنید.",
                "ar": "عذراً، لم أتمكن من العثور على حسابك. يرجى المحاولة مرة أخرى."
            }
        }
        
        return error_messages.get(error_type, {}).get(
            self.language,
            error_messages.get(error_type, {}).get("en", "An error occurred.")
        )

