# app/core/conversation/brain.py
"""
Conversation Brain - Health Care Assistant (COMMANDER)

RESPONSIBILITY:
- Entry point for all chat interactions
- Receives: user_id, user_message
- Determines current conversation stage
- Manages three types of memory: SHORT-TERM, MEDIUM-TERM, LONG-TERM
- Requests text from prompts.py (AI-generated, NO hardcoded text)
- Updates memory via memory.py
- Proactively initiates conversations for health check-ins
- Provides personalized health, wellness, and fitness suggestions
- Returns assistant message + metadata
- NO database queries directly
- NO hardcoded text - all text generated by AI
"""

from typing import Dict, Optional
from sqlalchemy.orm import Session
from app.core.conversation.stages import ConversationStage, get_stage, transition_stage
from app.core.conversation.memory import ConversationMemory
from app.core.conversation.context import ConversationContext
from app.core.conversation.prompts import ConversationPrompts
from app.models import User


class ConversationBrain:
    """Central decision engine for all conversation interactions"""
    
    def __init__(self, db: Session, language: str = "en"):
        self.db = db
        self.language = language
        self.memory = ConversationMemory(db)
        self.prompts = ConversationPrompts(language)
    
    def process_message(
        self,
        user_id: int,
        user_message: str
    ) -> Dict[str, any]:
        """
        Process user message and generate Sedi's response.
        
        Flow:
        1. Get current conversation stage
        2. Build conversation context
        3. Generate response using prompts
        4. Save conversation to memory
        5. Check for stage transition
        6. Return response with metadata
        
        Args:
            user_id: User ID
            user_message: User's message
        
        Returns:
            Dict with:
            - message: Sedi's response text
            - language: Language code
            - stage: Current conversation stage
            - metadata: Optional metadata (tone, intent, etc.)
        """
        # TEMP DEBUG: Log entry
        print(f"[BRAIN DEBUG] ===== PROCESSING MESSAGE =====")
        print(f"[BRAIN DEBUG] user_id={user_id}, message={user_message[:50]}...")
        
        try:
            # Validate user exists
            user = self.db.query(User).filter(User.id == user_id).first()
            if not user:
                print(f"[BRAIN DEBUG] ERROR: User not found")
                return {
                    "message": self._get_error_message("user_not_found"),
                    "language": self.language,
                    "stage": None,
                    "error": "User not found"
                }
            
            # EXPERIENCE STABILITY: Strict orchestration order
            # 1. IDENTIFY: Ensure user_id is valid (already validated above)
            # 2. LOAD: Get current state (stage, memory count, facts)
            current_stage = get_stage(user_id, self.db)
            current_memory_count = self.memory.get_conversation_count(user_id)
            print(f"[BRAIN DEBUG] Current stage: {current_stage.value}, memory_count: {current_memory_count}")
            
            # 3. BUILD CONTEXT: Build context with CURRENT state (before new message)
            context = ConversationContext(
                user_id=user_id,
                stage=current_stage,
                memory=self.memory,
                user_message=user_message
            )
            context_data = context.build()
            print(f"[BRAIN DEBUG] Context built - conversation_count={context_data.get('conversation_count', 0)}")
            
            # 4. GENERATE: Generate response with current context
            engagement_level = self._determine_engagement_level(context_data)
            print(f"[BRAIN DEBUG] Engagement level: {engagement_level}")
            
            # Check if we need to save user name from onboarding
            # This happens when user provides name in response to "what's your name?"
            self._save_user_name_if_provided(user_id, user_message, current_stage, context_data)
            
            sedi_response = self.prompts.generate_response(
                context_data, 
                user_message,
                engagement_level
            )
            print(f"[BRAIN DEBUG] Response generated (length={len(sedi_response)})")
            
            # 5. SAVE: Save conversation to memory (updates memory_count)
            self.memory.save_conversation(
                user_id=user_id,
                user_message=user_message,
                sedi_response=sedi_response,
                language=self.language
            )
            print(f"[BRAIN DEBUG] Conversation saved - new memory_count: {self.memory.get_conversation_count(user_id)}")
            
            # 6. TRANSITION: Check for stage transition (AFTER save - uses updated memory_count)
            new_stage = transition_stage(current_stage, user_id, self.db)
            print(f"[BRAIN DEBUG] Stage transition: {current_stage.value} -> {new_stage.value}")
            
            # 7. UPDATE: Update context_data with new stage for response
            context_data["stage"] = new_stage.value
            context_data["conversation_count"] = self.memory.get_conversation_count(user_id)
            
            print(f"[BRAIN DEBUG] ===== MESSAGE PROCESSED =====")
            
            # Build metadata with updated state
            metadata = {
                "stage": new_stage.value,
                "conversation_count": context_data.get("conversation_count", 0),
                "tone": self._infer_tone(sedi_response),
                "stage_transitioned": new_stage != current_stage
            }
            
            return {
                "message": sedi_response,
                "language": self.language,
                "stage": new_stage.value,  # Return NEW stage (after save and transition)
                "metadata": metadata
            }
        except Exception as e:
            # Log the error for debugging
            print(f"[BRAIN ERROR] Exception in process_message: {e}")
            print(f"[BRAIN ERROR] Exception type: {type(e).__name__}")
            import traceback
            print(f"[BRAIN ERROR] Traceback: {traceback.format_exc()}")
            
            # Return a user-friendly error message
            error_messages = {
                "en": "I'm sorry, I encountered an error processing your message. Please try again.",
                "fa": "متاسفم، در پردازش پیام شما خطایی رخ داد. لطفاً دوباره تلاش کنید.",
                "ar": "عذراً، حدث خطأ في معالجة رسالتك. يرجى المحاولة مرة أخرى."
            }
            
            error_message = error_messages.get(self.language, error_messages["en"])
            
            # Try to get current stage for response
            try:
                current_stage = get_stage(user_id, self.db)
                stage_value = current_stage.value
            except:
                stage_value = "FIRST_CONTACT"
            
            return {
                "message": error_message,
                "language": self.language,
                "stage": stage_value,
                "metadata": {
                    "error": True,
                    "error_type": type(e).__name__
                }
            }
    
    def get_initial_message(self, user_id: int, user_name: str, language: str) -> str:
        """
        Generate initial message after onboarding.
        Uses GPT with Sedi's knowledge base to introduce Sedi and explain what she does.
        """
        from app.core.conversation.sedi_knowledge_base import build_complete_sedi_context
        from app.core.conversation.prompts import client as gpt_client
        
        # Get Sedi's complete context
        sedi_context = build_complete_sedi_context(language)
        
        # Build system prompt
        system_prompt = f"""{sedi_context}

You are Sedi, speaking with {user_name} for the first time after they completed onboarding.

Your role is to:
1. Introduce yourself warmly
2. Explain who you are (Sedi, AI-powered health care assistant)
3. Explain your purpose: How you help improve their quality of life through:
   - Personalized health care suggestions
   - Lifestyle improvement recommendations
   - Continuous monitoring of daily health data via smart devices
4. Explain how you work: You learn about their lifestyle through natural conversation and use smart devices to track vital signs (heart rate, temperature, SpO2) continuously
5. Be warm, friendly, and engaging
6. Keep it concise (2-3 sentences, max 200 characters)

Speak in {language} language.
"""
        
        # Build user prompt
        user_prompt = {
            "en": f"Introduce yourself to {user_name} and explain what you do as their health care assistant. Be warm and welcoming.",
            "fa": f"خودت را به {user_name} معرفی کن و توضیح بده که به عنوان دستیار مراقبت سلامت‌شان چه کاری انجام می‌دهی. گرم و خوش‌آمدگو باش.",
            "ar": f"قدم نفسك إلى {user_name} واشرح ما تفعله كمساعد رعاية صحية. كن دافئاً ومرحباً."
        }.get(language, user_prompt["en"])
        
        try:
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ]
            
            response = gpt_client.chat.completions.create(
                model="gpt-4o-mini",
                messages=messages,
                temperature=0.7,
                max_tokens=200,
            )
            
            return response.choices[0].message.content.strip()
        except Exception as e:
            print(f"[BRAIN INITIAL MESSAGE ERROR] {e}")
            # Fallback message
            fallback = {
                "en": f"Hello {user_name}! I'm Sedi, your AI-powered health care assistant. I'm here to help improve your quality of life through personalized health suggestions, lifestyle improvements, and continuous monitoring via smart devices.",
                "fa": f"سلام {user_name}! من صدی هستم، دستیار مراقبت سلامت شما با هوش مصنوعی. من اینجا هستم تا از طریق پیشنهادهای شخصی‌سازی شده سلامت، بهبود سبک زندگی و پایش پیوسته از طریق گجت‌های هوشمند به بهبود کیفیت زندگی‌تان کمک کنم.",
                "ar": f"مرحباً {user_name}! أنا صدي، مساعد رعاية صحية الخاص بك المدعوم بالذكاء الاصطناعي. أنا هنا لمساعدتك على تحسين جودة حياتك من خلال اقتراحات صحية مخصصة وتحسينات نمط الحياة ومراقبة مستمرة عبر الأجهزة الذكية."
            }
            return fallback.get(language, fallback["en"])
    
    def get_greeting(self, user_id: int) -> Dict[str, any]:
        """
        Generate initial greeting for user.
        
        Used when user first opens chat or returns after absence.
        
        Args:
            user_id: User ID
        
        Returns:
            Dict with greeting message and metadata
        """
        # Get current stage
        stage = get_stage(user_id, self.db)
        
        # Build context
        context = ConversationContext(
            user_id=user_id,
            stage=stage,
            memory=self.memory
        )
        context_data = context.build()
        
        # Generate greeting based on stage
        greeting = self._generate_greeting(context_data, stage)
        
        return {
            "message": greeting,
            "language": self.language,
            "stage": stage.value,
            "metadata": {
                "type": "greeting",
                "stage": stage.value
            }
        }
    
    def _generate_greeting(
        self,
        context: Dict[str, any],
        stage: ConversationStage
    ) -> str:
        """
        Generate greeting message - Sedi introduces herself and explains how she can help.
        
        CRITICAL: Sedi must be a conversation initiator and explain:
        - Who she is (health care assistant)
        - How she can improve user's quality of life
        - Through health care suggestions, lifestyle improvements, and smart device monitoring
        """
        user_name = context.get("user_name") or "friend"
        time_since = context.get("time_since_last")
        engagement_level = self._determine_engagement_level(context)
        
        # Build comprehensive greeting prompt based on stage
        if stage == ConversationStage.FIRST_CONTACT:
            # FIRST CONTACT: Use GPT with Sedi's knowledge base for introduction
            # This ensures Sedi introduces herself properly based on her knowledge
            user_id = context.get("user_id")
            if user_id:
                user = self.db.query(User).filter(User.id == user_id).first()
                if user:
                    return self.get_initial_message(user_id, user_name, self.language)
            # Fallback if user_id not available
            return self.prompts._get_fallback_response(stage)
        elif time_since:
            # User returning after absence - be warm and check in
            greeting_prompt = {
                "en": f"""Greet {user_name} warmly. You haven't talked in a while. Remind them briefly who you are (Sedi, their health care assistant) and that you're here to help improve their quality of life through health monitoring and lifestyle suggestions. Be warm but not overwhelming. Ask how they've been.""",
                "fa": f"""با {user_name} گرم سلام کن. مدتی است که حرف نزده‌اید. مختصر یادآوری کن که تو کیستی (صدی، دستیار مراقبت سلامت‌شان) و اینجا هستی تا از طریق نظارت سلامت و پیشنهادهای سبک زندگی کیفیت زندگی‌شان را بهبود دهی. گرم باش اما نه بیش از حد. بپرس چطور بوده‌اند.""",
                "ar": f"""حي {user_name} بحرارة. لم تتحدثا منذ فترة. ذكره باختصار من أنت (صدي، مساعد رعاية صحية) وأنك هنا لمساعدتهم على تحسين جودة حياتهم من خلال مراقبة الصحة واقتراحات نمط الحياة. كن دافئاً لكن ليس ساحقاً. اسأل كيف كانوا."""
            }
        else:
            # Regular greeting - proactive health check-in
            greeting_prompt = {
                "en": f"""Greet {user_name} warmly. As their health care assistant, proactively check in on their wellness. You can mention their health data if available, or ask about their day. Be conversational and supportive. Keep it brief (1-2 sentences, max 150 characters).""",
                "fa": f"""با {user_name} گرم سلام کن. به عنوان دستیار مراقبت سلامت‌شان، به صورت فعالانه چک‌آپ تندرستی کن. می‌توانی به داده‌های سلامت‌شان اشاره کنی اگر در دسترس است، یا درباره روزشان بپرسی. گفتگویی و حمایت‌کننده باش. مختصر نگه دار (1-2 جمله، حداکثر 150 کاراکتر).""",
                "ar": f"""حي {user_name} بحرارة. كمساعد رعاية صحية، تحقق بشكل استباقي من صحتهم. يمكنك ذكر بيانات صحتهم إذا كانت متاحة، أو السؤال عن يومهم. كن محادثاً وداعماً. اجعلها مختصرة (1-2 جملة، بحد أقصى 150 حرف)."""
            }
        
        # For non-FIRST_CONTACT stages, use GPT for greeting
        try:
            system_prompt = self.prompts._build_system_prompt(
                stage,
                user_name,
                context.get("conversation_count", 0),
                engagement_level
            )
            
            prompt_text = greeting_prompt.get(self.language, greeting_prompt["en"])
            
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt_text}
            ]
            
            from app.core.conversation.prompts import client as gpt_client
            response = gpt_client.chat.completions.create(
                model="gpt-4o-mini",
                messages=messages,
                temperature=0.8,
                max_tokens=300,
            )
            
            return response.choices[0].message.content.strip()
            
        except Exception as e:
            print(f"[BRAIN GREETING ERROR] {e}")
            return self.prompts._get_fallback_response(stage)
    
    def _determine_engagement_level(self, context: Dict[str, any]) -> str:
        """
        Determine user engagement level based on conversation patterns.
        
        MINIMAL logic - selection only, no complex calculations.
        
        Returns:
            "low": User rarely responds, long gaps
            "normal": Standard engagement
            "high": User is very engaged, frequent responses
        """
        conversation_count = context.get("conversation_count", 0)
        time_since_last = context.get("time_since_last")
        recent_messages = context.get("recent_messages", [])
        
        # Low engagement indicators
        if conversation_count > 0:
            if time_since_last:
                # Parse time delta (format: "X days, Y:Z:W")
                try:
                    days = 0
                    if "day" in time_since_last.lower():
                        days = int(time_since_last.split()[0])
                    if days > 7:  # More than a week
                        return "low"
                except:
                    pass
            
            # Check recent message frequency
            if len(recent_messages) < 2 and conversation_count > 5:
                return "low"
        
        # High engagement indicators
        if len(recent_messages) >= 3 and conversation_count > 3:
            # User has been actively chatting
            return "high"
        
        # Default to normal
        return "normal"
    
    def _infer_tone(self, message: str) -> str:
        """Infer tone from message (simple heuristic)"""
        message_lower = message.lower()
        if any(word in message_lower for word in ["!", "urgent", "important"]):
            return "urgent"
        elif any(word in message_lower for word in ["?", "wonder", "curious"]):
            return "curious"
        elif any(word in message_lower for word in ["😊", "happy", "glad", "great"]):
            return "warm"
        else:
            return "neutral"
    
    def _save_user_name_if_provided(
        self,
        user_id: int,
        user_message: str,
        stage: ConversationStage,
        context: Dict[str, any]
    ):
        """
        Save user name if provided during onboarding.
        
        This handles the case where user provides name in response to "what's your name?"
        during FIRST_CONTACT or INTRODUCTION stage.
        """
        # Only check in onboarding stages
        if stage not in [ConversationStage.FIRST_CONTACT, ConversationStage.INTRODUCTION]:
            return
        
        # Check if user already has a real name (not anonymous)
        user = self.db.query(User).filter(User.id == user_id).first()
        if not user:
            return
        
        # If user already has a real name, don't overwrite
        if user.name and not user.name.startswith("anonymous_"):
            return
        
        # Check if this looks like a name response
        # (short, no digits, reasonable length, and this is early in conversation)
        user_message_clean = user_message.strip()
        conversation_count = context.get("conversation_count", 0)
        
        # Check if last Sedi message asked for name
        recent_messages = context.get("recent_messages", [])
        last_sedi_message = recent_messages[-1].get("sedi", "") if recent_messages else ""
        
        name_keywords = [
            "name", "اسم", "اسمك", "اسمك", "what's your name", "اسم شما", "ما اسمك",
            "اسمتون", "اسمت", "اسمتون را", "اسم شما چیه", "اسم شما چیست", "اسمت چیه", "اسمت چیست",
            "میتونم اسمتون", "میتونم اسمت", "بدونم اسمتون", "بدونم اسمت", "بدانم اسمتون", "بدانم اسمت"
        ]
        name_was_requested = any(keyword in last_sedi_message.lower() for keyword in name_keywords) if last_sedi_message else False
        
        # CRITICAL: Check if password was requested - don't save name if we're in password flow
        password_keywords = ["password", "رمز", "كلمة مرور", "security", "امنیت", "أمان", "امنیتی"]
        password_requested = any(keyword in last_sedi_message.lower() for keyword in password_keywords) if last_sedi_message else False
        
        # List of common short responses that should NOT be saved as names
        invalid_name_responses = {
            "en": ["good", "fine", "ok", "okay", "yes", "no", "hi", "hello", "hey", "thanks", "thank you", "well", "great", "nice"],
            "fa": ["خوب", "خوبم", "خوبی", "خوبه", "بله", "نه", "سلام", "درود", "ممنون", "تشکر", "عالی", "خوب است", "خوبم", "خوبی", "خوبه", "خوب است", "خوبم", "خوبی", "خوبه"],
            "ar": ["جيد", "حسنا", "نعم", "لا", "مرحبا", "شكرا", "شكراً"]
        }
        invalid_responses = invalid_name_responses.get(self.language, invalid_name_responses["en"])
        # Also check in all languages
        all_invalid = []
        for lang_responses in invalid_name_responses.values():
            all_invalid.extend(lang_responses)
        
        is_invalid_response = user_message_clean.lower() in [r.lower() for r in all_invalid]
        
        # If name was requested and user message looks like a name
        # CRITICAL: Don't save name if password was requested or if it's an invalid response
        # Allow name detection in early conversation (first 5 messages) or if name was explicitly requested
        if (name_was_requested and 
            not password_requested and  # CRITICAL: Don't save name during password flow
            not is_invalid_response and  # CRITICAL: Don't save common responses as names
            conversation_count <= 5 and  # Early in conversation (increased from 2 to 5)
            2 <= len(user_message_clean) <= 30 and  # Reasonable name length
            not any(char.isdigit() for char in user_message_clean) and  # No digits
            not any(char in user_message_clean for char in ["?", "؟", "!", "!"])):  # Not a question/exclamation
            # Extract name (first word, clean)
            name = user_message_clean.split()[0] if user_message_clean.split() else user_message_clean
            name = name.strip()
            
            # Check if name is valid (not empty, not just punctuation)
            if name and len(name) > 1:
                # Check if name is already taken by another user
                existing_user = self.db.query(User).filter(
                    User.name == name,
                    User.id != user_id
                ).first()
                
                if not existing_user:
                    # Save name to user
                    user.name = name
                    self.db.commit()
                    self.db.refresh(user)
                    print(f"[BRAIN DEBUG] Saved user name: {name} for user_id={user_id}")
    
    def _get_error_message(self, error_type: str) -> str:
        """Get error message based on type"""
        error_messages = {
            "user_not_found": {
                "en": "I'm sorry, I couldn't find your account. Please try again.",
                "fa": "متاسفم، نتوانستم حساب کاربری شما را پیدا کنم. لطفاً دوباره تلاش کنید.",
                "ar": "عذراً، لم أتمكن من العثور على حسابك. يرجى المحاولة مرة أخرى."
            }
        }
        
        return error_messages.get(error_type, {}).get(
            self.language,
            error_messages.get(error_type, {}).get("en", "An error occurred.")
        )

