"""I5 W1-P01 weekly governance + GSP additive

Revision ID: 053_i5_w1_p01_weekly_governance
Revises: 052_i5_w5_iran_directory

MIG-I5-W1-P01 — schema authoring for current frozen ORM (W6-P01).
Additive PostgreSQL-only. Exact ORM CHECK/FK/UQ/Index parity.
No seed, network, activation, or Base.metadata.create_all.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "053_i5_w1_p01_weekly_governance"
down_revision: Union[str, None] = "052_i5_w5_iran_directory"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- GSP W1-P01 additive contract (alter 051) ---
    op.add_column('governed_source_profiles', sa.Column('registry_state', sa.String(length=32), nullable=False, server_default='DISCOVERED'))
    op.add_column('governed_source_profiles', sa.Column('runtime_eligibility', sa.String(length=32), nullable=False, server_default='NOT_ELIGIBLE'))
    op.add_column('governed_source_profiles', sa.Column('block_reason', sa.Text(), nullable=True))
    op.add_column('governed_source_profiles', sa.Column('owner_reference', sa.String(length=512), nullable=True))
    op.add_column('governed_source_profiles', sa.Column('reviewer_reference', sa.String(length=512), nullable=True))
    op.add_column('governed_source_profiles', sa.Column('approver_reference', sa.String(length=512), nullable=True))
    op.add_column('governed_source_profiles', sa.Column('topic_coverage', sa.Text(), nullable=True))
    op.add_column('governed_source_profiles', sa.Column('effective_from', sa.DateTime(), nullable=True))
    op.add_column('governed_source_profiles', sa.Column('effective_to', sa.DateTime(), nullable=True))
    op.add_column('governed_source_profiles', sa.Column('last_discovered_at', sa.DateTime(), nullable=True))
    op.add_column('governed_source_profiles', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    op.add_column('governed_source_profiles', sa.Column('last_reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('governed_source_profiles', sa.Column('canonicalization_version', sa.String(length=32), nullable=False, server_default='v1'))
    op.create_check_constraint('ck_gsp_registry_state_vocab', 'governed_source_profiles', """registry_state IN ('DISCOVERED', 'UNDER_REVIEW', 'APPROVED', 'ACTIVE', 'DEFERRED', 'BLOCKED', 'REVOKED', 'SUPERSEDED', 'ARCHIVED')""")
    op.create_check_constraint('ck_gsp_block_reason_length', 'governed_source_profiles', """block_reason IS NULL OR char_length(block_reason) <= 2000""")
    op.create_check_constraint('ck_gsp_effective_window_order', 'governed_source_profiles', """effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from""")
    op.create_check_constraint('ck_gsp_runtime_eligibility_vocab', 'governed_source_profiles', """runtime_eligibility IN ('NOT_ELIGIBLE', 'REVIEW_REQUIRED', 'ELIGIBLE', 'SUSPENDED', 'REVOKED')""")
    op.create_index('ix_gsp_registry_state', 'governed_source_profiles', ['registry_state'])
    op.create_index('ix_gsp_runtime_eligibility', 'governed_source_profiles', ['runtime_eligibility'])
    op.create_index('ix_gsp_last_checked_at', 'governed_source_profiles', ['last_checked_at'])
    op.create_index('ix_gsp_last_reviewed_at', 'governed_source_profiles', ['last_reviewed_at'])
    op.create_index('ix_gsp_registry_runtime', 'governed_source_profiles', ['registry_state', 'runtime_eligibility'])

    # --- weekly_knowledge_runs ---
    op.execute("""

CREATE TABLE weekly_knowledge_runs (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	logical_run_key VARCHAR(64) NOT NULL, 
	canonicalization_version VARCHAR(32) DEFAULT 'v1' NOT NULL, 
	hash_algorithm VARCHAR(32) DEFAULT 'SHA-256' NOT NULL, 
	schedule_key VARCHAR(128) NOT NULL, 
	run_type VARCHAR(64) DEFAULT 'WEEKLY_GOVERNED' NOT NULL, 
	trigger_type VARCHAR(64) NOT NULL, 
	planned_window_start TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	planned_window_end TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	approval_state VARCHAR(32) NOT NULL, 
	source_scope_hash VARCHAR(64) NOT NULL, 
	domain_scope_hash VARCHAR(64) NOT NULL, 
	gap_scope_hash VARCHAR(64) NOT NULL, 
	config_version VARCHAR(64) NOT NULL, 
	config_hash VARCHAR(64) NOT NULL, 
	source_scope TEXT NOT NULL, 
	domain_scope TEXT NOT NULL, 
	gap_scope TEXT NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	successful_attempt_id INTEGER, 
	latest_attempt_id INTEGER, 
	created_by_reference VARCHAR(512), 
	approved_by_reference VARCHAR(512), 
	approved_at TIMESTAMP WITHOUT TIME ZONE, 
	supersedes_run_id INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	row_version INTEGER DEFAULT '1' NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_weekly_knowledge_runs_logical_run_key UNIQUE (logical_run_key), 
	CONSTRAINT ck_wkr_run_type_vocab CHECK (run_type IN ('WEEKLY_GOVERNED')), 
	CONSTRAINT ck_wkr_trigger_type_vocab CHECK (trigger_type IN ('SCHEDULED', 'MANUAL', 'RETRY_PARENT', 'AD_HOC')), 
	CONSTRAINT ck_wkr_approval_state_vocab CHECK (approval_state IN ('NOT_REQUIRED', 'REQUIRED', 'APPROVED', 'REJECTED', 'EXPIRED')), 
	CONSTRAINT ck_wkr_status_vocab CHECK (status IN ('PLANNED', 'APPROVAL_REQUIRED', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', 'BLOCKED', 'DEFERRED', 'CANCELLED', 'SUPERSEDED')), 
	CONSTRAINT ck_wkr_window_order CHECK (planned_window_end >= planned_window_start), 
	CONSTRAINT ck_wkr_supersedes_not_self CHECK (supersedes_run_id IS NULL OR supersedes_run_id <> id), 
	CONSTRAINT fk_wkr_supersedes_run_id FOREIGN KEY(supersedes_run_id) REFERENCES weekly_knowledge_runs (id) ON DELETE RESTRICT
);
""")

    # --- weekly_knowledge_run_attempts ---
    op.execute("""

CREATE TABLE weekly_knowledge_run_attempts (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	weekly_run_id INTEGER NOT NULL, 
	attempt_number INTEGER NOT NULL, 
	retry_of_attempt_id INTEGER, 
	status VARCHAR(32) NOT NULL, 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	worker_reference VARCHAR(512), 
	config_snapshot_reference VARCHAR(2048), 
	run_checksum VARCHAR(64), 
	canonicalization_version VARCHAR(32) DEFAULT 'v1' NOT NULL, 
	hash_algorithm VARCHAR(32) DEFAULT 'SHA-256' NOT NULL, 
	total_sources INTEGER DEFAULT '0' NOT NULL, 
	checked_sources INTEGER DEFAULT '0' NOT NULL, 
	fetched_sources INTEGER DEFAULT '0' NOT NULL, 
	skipped_sources INTEGER DEFAULT '0' NOT NULL, 
	blocked_sources INTEGER DEFAULT '0' NOT NULL, 
	failed_sources INTEGER DEFAULT '0' NOT NULL, 
	new_knowledge_count INTEGER DEFAULT '0' NOT NULL, 
	updated_knowledge_count INTEGER DEFAULT '0' NOT NULL, 
	superseded_knowledge_count INTEGER DEFAULT '0' NOT NULL, 
	rejected_knowledge_count INTEGER DEFAULT '0' NOT NULL, 
	created_gap_count INTEGER DEFAULT '0' NOT NULL, 
	resolved_gap_count INTEGER DEFAULT '0' NOT NULL, 
	warning_count INTEGER DEFAULT '0' NOT NULL, 
	error_count INTEGER DEFAULT '0' NOT NULL, 
	failure_code VARCHAR(128), 
	failure_reason TEXT, 
	block_reason TEXT, 
	evidence_reference VARCHAR(2048), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	row_version INTEGER DEFAULT '1' NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_wkra_run_attempt UNIQUE (weekly_run_id, attempt_number), 
	CONSTRAINT uq_wkra_id_weekly_run_id UNIQUE (id, weekly_run_id), 
	CONSTRAINT ck_wkra_status_vocab CHECK (status IN ('CREATED', 'STARTED', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', 'BLOCKED', 'DEFERRED', 'CANCELLED', 'SUPERSEDED')), 
	CONSTRAINT ck_wkra_attempt_number_pos CHECK (attempt_number > 0), 
	CONSTRAINT ck_wkra_retry_not_self CHECK (retry_of_attempt_id IS NULL OR retry_of_attempt_id <> id), 
	CONSTRAINT ck_wkra_completed_after_started CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at), 
	CONSTRAINT ck_wkra_failure_reason_length CHECK (failure_reason IS NULL OR char_length(failure_reason) <= 2000), 
	CONSTRAINT ck_wkra_block_reason_length CHECK (block_reason IS NULL OR char_length(block_reason) <= 2000), 
	CONSTRAINT ck_wkra_total_sources_nonnegative CHECK (total_sources >= 0), 
	CONSTRAINT ck_wkra_checked_sources_nonnegative CHECK (checked_sources >= 0), 
	CONSTRAINT ck_wkra_fetched_sources_nonnegative CHECK (fetched_sources >= 0), 
	CONSTRAINT ck_wkra_skipped_sources_nonnegative CHECK (skipped_sources >= 0), 
	CONSTRAINT ck_wkra_blocked_sources_nonnegative CHECK (blocked_sources >= 0), 
	CONSTRAINT ck_wkra_failed_sources_nonnegative CHECK (failed_sources >= 0), 
	CONSTRAINT ck_wkra_new_knowledge_count_nonnegative CHECK (new_knowledge_count >= 0), 
	CONSTRAINT ck_wkra_updated_knowledge_count_nonnegative CHECK (updated_knowledge_count >= 0), 
	CONSTRAINT ck_wkra_superseded_knowledge_count_nonnegative CHECK (superseded_knowledge_count >= 0), 
	CONSTRAINT ck_wkra_rejected_knowledge_count_nonnegative CHECK (rejected_knowledge_count >= 0), 
	CONSTRAINT ck_wkra_created_gap_count_nonnegative CHECK (created_gap_count >= 0), 
	CONSTRAINT ck_wkra_resolved_gap_count_nonnegative CHECK (resolved_gap_count >= 0), 
	CONSTRAINT ck_wkra_warning_count_nonnegative CHECK (warning_count >= 0), 
	CONSTRAINT ck_wkra_error_count_nonnegative CHECK (error_count >= 0), 
	CONSTRAINT fk_wkra_retry_same_run FOREIGN KEY(retry_of_attempt_id, weekly_run_id) REFERENCES weekly_knowledge_run_attempts (id, weekly_run_id) ON DELETE RESTRICT, 
	CONSTRAINT fk_wkra_weekly_run_id FOREIGN KEY(weekly_run_id) REFERENCES weekly_knowledge_runs (id) ON DELETE RESTRICT
);
""")

    # --- knowledge_gaps ---
    op.execute("""

CREATE TABLE knowledge_gaps (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	canonical_gap_key VARCHAR(64) NOT NULL, 
	canonicalization_version VARCHAR(32) DEFAULT 'v1' NOT NULL, 
	hash_algorithm VARCHAR(32) DEFAULT 'SHA-256' NOT NULL, 
	domain VARCHAR(128) NOT NULL, 
	subdomain VARCHAR(128), 
	capability_id VARCHAR(64), 
	gap_type VARCHAR(64) NOT NULL, 
	title VARCHAR(512) NOT NULL, 
	description TEXT, 
	evidence_of_gap TEXT, 
	current_knowledge_state TEXT, 
	required_knowledge_state TEXT, 
	source_need TEXT, 
	priority VARCHAR(32) DEFAULT 'P2' NOT NULL, 
	severity VARCHAR(32) DEFAULT 'MEDIUM' NOT NULL, 
	urgency VARCHAR(32) DEFAULT 'NORMAL' NOT NULL, 
	confidence FLOAT, 
	status VARCHAR(32) DEFAULT 'OPEN' NOT NULL, 
	owner_reference VARCHAR(512), 
	reviewer_reference VARCHAR(512), 
	blocker TEXT, 
	dependencies TEXT, 
	target_package_id VARCHAR(64), 
	target_source_profile_id INTEGER, 
	target_knowledge_unit_id INTEGER, 
	discovered_by VARCHAR(512), 
	discovered_attempt_id INTEGER, 
	next_action TEXT, 
	next_review_at TIMESTAMP WITHOUT TIME ZONE, 
	retry_count INTEGER DEFAULT '0' NOT NULL, 
	last_attempt_at TIMESTAMP WITHOUT TIME ZONE, 
	resolution_type VARCHAR(64), 
	resolution_evidence TEXT, 
	resolved_by_reference VARCHAR(512), 
	resolved_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	row_version INTEGER DEFAULT '1' NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_knowledge_gaps_canonical_gap_key UNIQUE (canonical_gap_key), 
	CONSTRAINT ck_kg_gap_type_vocab CHECK (gap_type IN ('MISSING', 'STALE', 'LOW_CONFIDENCE', 'CONFLICTING', 'RETRACTED', 'INSUFFICIENT_COVERAGE', 'MISSING_PROVENANCE', 'MISSING_RIGHTS_REVIEW', 'MISSING_SAFETY_REVIEW', 'RUNTIME_RETRIEVAL_FAILURE')), 
	CONSTRAINT ck_kg_priority_vocab CHECK (priority IN ('P0', 'P1', 'P2', 'P3')), 
	CONSTRAINT ck_kg_severity_vocab CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')), 
	CONSTRAINT ck_kg_urgency_vocab CHECK (urgency IN ('LOW', 'NORMAL', 'HIGH', 'IMMEDIATE')), 
	CONSTRAINT ck_kg_status_vocab CHECK (status IN ('OPEN', 'TRIAGED', 'PLANNED', 'IN_PROGRESS', 'BLOCKED', 'DEFERRED', 'RESOLVED', 'REJECTED', 'REOPENED')), 
	CONSTRAINT ck_kg_confidence_range CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)), 
	CONSTRAINT ck_kg_retry_count_nonneg CHECK (retry_count >= 0), 
	CONSTRAINT ck_kg_description_length CHECK (description IS NULL OR char_length(description) <= 8000), 
	CONSTRAINT ck_kg_current_knowledge_state_length CHECK (current_knowledge_state IS NULL OR char_length(current_knowledge_state) <= 4000), 
	CONSTRAINT ck_kg_required_knowledge_state_length CHECK (required_knowledge_state IS NULL OR char_length(required_knowledge_state) <= 4000), 
	CONSTRAINT ck_kg_next_action_length CHECK (next_action IS NULL OR char_length(next_action) <= 2000), 
	CONSTRAINT ck_kg_blocker_length CHECK (blocker IS NULL OR char_length(blocker) <= 2000), 
	CONSTRAINT fk_knowledge_gaps_target_source_profile_id FOREIGN KEY(target_source_profile_id) REFERENCES governed_source_profiles (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_knowledge_gaps_discovered_attempt_id FOREIGN KEY(discovered_attempt_id) REFERENCES weekly_knowledge_run_attempts (id) ON DELETE RESTRICT
);
""")

    # --- weekly_run_source_results ---
    op.execute("""

CREATE TABLE weekly_run_source_results (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	attempt_id INTEGER NOT NULL, 
	source_profile_id INTEGER NOT NULL, 
	source_version_id INTEGER, 
	result_status VARCHAR(32) NOT NULL, 
	checked_at TIMESTAMP WITHOUT TIME ZONE, 
	fetch_outcome VARCHAR(64), 
	extraction_outcome VARCHAR(64), 
	publication_outcome VARCHAR(64), 
	knowledge_new_count INTEGER DEFAULT '0' NOT NULL, 
	knowledge_updated_count INTEGER DEFAULT '0' NOT NULL, 
	knowledge_superseded_count INTEGER DEFAULT '0' NOT NULL, 
	knowledge_rejected_count INTEGER DEFAULT '0' NOT NULL, 
	gap_created_count INTEGER DEFAULT '0' NOT NULL, 
	warning_count INTEGER DEFAULT '0' NOT NULL, 
	error_count INTEGER DEFAULT '0' NOT NULL, 
	failure_code VARCHAR(128), 
	failure_reason TEXT, 
	evidence_reference VARCHAR(2048), 
	content_fingerprint VARCHAR(64), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_wrsr_attempt_source_profile UNIQUE (attempt_id, source_profile_id), 
	CONSTRAINT ck_wrsr_result_status_vocab CHECK (result_status IN ('CHECKED', 'FETCHED', 'EXTRACTED', 'PUBLISHED', 'SKIPPED', 'BLOCKED', 'FAILED', 'WARNING')), 
	CONSTRAINT ck_wrsr_failure_reason_length CHECK (failure_reason IS NULL OR char_length(failure_reason) <= 2000), 
	CONSTRAINT ck_wrsr_knowledge_new_count_nonnegative CHECK (knowledge_new_count >= 0), 
	CONSTRAINT ck_wrsr_knowledge_updated_count_nonnegative CHECK (knowledge_updated_count >= 0), 
	CONSTRAINT ck_wrsr_knowledge_superseded_count_nonnegative CHECK (knowledge_superseded_count >= 0), 
	CONSTRAINT ck_wrsr_knowledge_rejected_count_nonnegative CHECK (knowledge_rejected_count >= 0), 
	CONSTRAINT ck_wrsr_gap_created_count_nonnegative CHECK (gap_created_count >= 0), 
	CONSTRAINT ck_wrsr_warning_count_nonnegative CHECK (warning_count >= 0), 
	CONSTRAINT ck_wrsr_error_count_nonnegative CHECK (error_count >= 0), 
	CONSTRAINT fk_wrsr_attempt_id FOREIGN KEY(attempt_id) REFERENCES weekly_knowledge_run_attempts (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_wrsr_source_profile_id FOREIGN KEY(source_profile_id) REFERENCES governed_source_profiles (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_wrsr_source_version_id FOREIGN KEY(source_version_id) REFERENCES governed_source_profile_versions (id) ON DELETE RESTRICT
);
""")

    # --- weekly_run_gap_results ---
    op.execute("""

CREATE TABLE weekly_run_gap_results (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	attempt_id INTEGER NOT NULL, 
	gap_id INTEGER NOT NULL, 
	result_type VARCHAR(32) NOT NULL, 
	previous_status VARCHAR(32), 
	new_status VARCHAR(32), 
	evidence_reference VARCHAR(2048), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_wrgr_attempt_gap UNIQUE (attempt_id, gap_id), 
	CONSTRAINT ck_wrgr_result_type_vocab CHECK (result_type IN ('DISCOVERED', 'UPDATED', 'TRIAGED', 'PLANNED', 'BLOCKED', 'DEFERRED', 'RESOLVED', 'REOPENED', 'REJECTED', 'UNCHANGED')), 
	CONSTRAINT ck_wrgr_previous_status_vocab CHECK (previous_status IS NULL OR (previous_status IN ('OPEN', 'TRIAGED', 'PLANNED', 'IN_PROGRESS', 'BLOCKED', 'DEFERRED', 'RESOLVED', 'REJECTED', 'REOPENED'))), 
	CONSTRAINT ck_wrgr_new_status_vocab CHECK (new_status IS NULL OR (new_status IN ('OPEN', 'TRIAGED', 'PLANNED', 'IN_PROGRESS', 'BLOCKED', 'DEFERRED', 'RESOLVED', 'REJECTED', 'REOPENED'))), 
	CONSTRAINT fk_wrgr_attempt_id FOREIGN KEY(attempt_id) REFERENCES weekly_knowledge_run_attempts (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_wrgr_gap_id FOREIGN KEY(gap_id) REFERENCES knowledge_gaps (id) ON DELETE RESTRICT
);
""")

    # --- i5_governance_decisions ---
    op.execute("""

CREATE TABLE i5_governance_decisions (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	entity_type VARCHAR(64) NOT NULL, 
	entity_id INTEGER NOT NULL, 
	decision_family VARCHAR(64) NOT NULL, 
	decision_type VARCHAR(64) NOT NULL, 
	decision_request_key VARCHAR(128) NOT NULL, 
	from_state VARCHAR(64), 
	to_state VARCHAR(64), 
	outcome VARCHAR(32) NOT NULL, 
	reason_code VARCHAR(128), 
	reason TEXT, 
	actor_type VARCHAR(32) NOT NULL, 
	actor_reference VARCHAR(512), 
	evidence_reference VARCHAR(2048), 
	decision_metadata TEXT, 
	canonical_hash VARCHAR(64) NOT NULL, 
	canonicalization_version VARCHAR(32) DEFAULT 'v1' NOT NULL, 
	hash_algorithm VARCHAR(32) DEFAULT 'SHA-256' NOT NULL, 
	supersedes_decision_id INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_i5gd_decision_request UNIQUE (entity_type, entity_id, decision_request_key), 
	CONSTRAINT uq_i5gd_id_entity_family UNIQUE (id, entity_type, entity_id, decision_family), 
	CONSTRAINT ck_i5gd_entity_type_vocab CHECK (entity_type IN ('SOURCE_PROFILE', 'SOURCE_PROFILE_VERSION', 'KNOWLEDGE_GAP', 'WEEKLY_RUN', 'WEEKLY_RUN_ATTEMPT', 'RUN_SOURCE_RESULT', 'RUN_GAP_RESULT')), 
	CONSTRAINT ck_i5gd_decision_family_vocab CHECK (decision_family IN ('RIGHTS', 'AUTOMATION', 'QUALITY', 'MEDICAL_SAFETY', 'SECURITY', 'LIFECYCLE', 'GAP_LIFECYCLE', 'RUN_APPROVAL', 'RUN_TERMINALIZATION')), 
	CONSTRAINT ck_i5gd_decision_type_vocab CHECK (decision_type IN ('RIGHTS_REVIEW', 'AUTOMATION_REVIEW', 'QUALITY_REVIEW', 'MEDICAL_SAFETY_REVIEW', 'SECURITY_REVIEW', 'APPROVAL', 'REJECTION', 'ACTIVATION', 'SUSPENSION', 'REVOCATION', 'SUPERSESSION', 'GAP_RESOLUTION', 'GAP_REOPEN', 'RUN_APPROVAL', 'RUN_TERMINALIZATION')), 
	CONSTRAINT ck_i5gd_outcome_vocab CHECK (outcome IN ('APPROVED', 'REJECTED', 'DEFERRED', 'BLOCKED', 'SUPERSEDED', 'RECORDED')), 
	CONSTRAINT ck_i5gd_actor_type_vocab CHECK (actor_type IN ('SYSTEM', 'HUMAN', 'SERVICE', 'JAVAD', 'UNKNOWN')), 
	CONSTRAINT ck_i5gd_entity_id_pos CHECK (entity_id > 0), 
	CONSTRAINT ck_i5gd_supersedes_not_self CHECK (supersedes_decision_id IS NULL OR supersedes_decision_id <> id), 
	CONSTRAINT ck_i5gd_canonical_hash_format CHECK (canonical_hash ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_i5gd_decision_request_key_format CHECK (decision_request_key ~ '^[A-Za-z0-9._:-]{1,128}$'), 
	CONSTRAINT ck_i5gd_hash_algorithm_constant CHECK (hash_algorithm = 'SHA-256'), 
	CONSTRAINT ck_i5gd_canonicalization_version_constant CHECK (canonicalization_version = 'v1'), 
	CONSTRAINT ck_i5gd_reason_length CHECK (reason IS NULL OR char_length(reason) <= 4000), 
	CONSTRAINT ck_i5gd_supersession_requires_parent CHECK ((decision_type <> 'SUPERSESSION') OR (supersedes_decision_id IS NOT NULL)), 
	CONSTRAINT ck_i5gd_decision_type_family_matrix CHECK ((decision_type = 'SUPERSESSION') OR ((decision_type = 'RIGHTS_REVIEW' AND decision_family = 'RIGHTS') OR (decision_type = 'AUTOMATION_REVIEW' AND decision_family = 'AUTOMATION') OR (decision_type = 'QUALITY_REVIEW' AND decision_family = 'QUALITY') OR (decision_type = 'MEDICAL_SAFETY_REVIEW' AND decision_family = 'MEDICAL_SAFETY') OR (decision_type = 'SECURITY_REVIEW' AND decision_family = 'SECURITY') OR (decision_type = 'APPROVAL' AND decision_family = 'LIFECYCLE') OR (decision_type = 'REJECTION' AND decision_family = 'LIFECYCLE') OR (decision_type = 'ACTIVATION' AND decision_family = 'LIFECYCLE') OR (decision_type = 'SUSPENSION' AND decision_family = 'LIFECYCLE') OR (decision_type = 'REVOCATION' AND decision_family = 'LIFECYCLE') OR (decision_type = 'GAP_RESOLUTION' AND decision_family = 'GAP_LIFECYCLE') OR (decision_type = 'GAP_REOPEN' AND decision_family = 'GAP_LIFECYCLE') OR (decision_type = 'RUN_APPROVAL' AND decision_family = 'RUN_APPROVAL') OR (decision_type = 'RUN_TERMINALIZATION' AND decision_family = 'RUN_TERMINALIZATION'))), 
	CONSTRAINT ck_i5gd_entity_family_matrix CHECK ((entity_type IN ('SOURCE_PROFILE', 'SOURCE_PROFILE_VERSION') AND decision_family IN ('RIGHTS', 'AUTOMATION', 'QUALITY', 'MEDICAL_SAFETY', 'SECURITY', 'LIFECYCLE')) OR (entity_type = 'KNOWLEDGE_GAP' AND decision_family IN ('LIFECYCLE', 'GAP_LIFECYCLE')) OR (entity_type = 'WEEKLY_RUN' AND decision_family IN ('LIFECYCLE', 'RUN_APPROVAL')) OR (entity_type = 'WEEKLY_RUN_ATTEMPT' AND decision_family = 'RUN_TERMINALIZATION') OR (entity_type = 'RUN_SOURCE_RESULT' AND decision_family IN ('RIGHTS', 'AUTOMATION', 'QUALITY', 'MEDICAL_SAFETY', 'SECURITY', 'LIFECYCLE')) OR (entity_type = 'RUN_GAP_RESULT' AND decision_family IN ('QUALITY', 'LIFECYCLE'))), 
	CONSTRAINT ck_i5gd_entity_decision_matrix CHECK ((entity_type = 'SOURCE_PROFILE' AND decision_type IN ('RIGHTS_REVIEW', 'AUTOMATION_REVIEW', 'QUALITY_REVIEW', 'MEDICAL_SAFETY_REVIEW', 'SECURITY_REVIEW', 'APPROVAL', 'REJECTION', 'ACTIVATION', 'SUSPENSION', 'REVOCATION', 'SUPERSESSION')) OR (entity_type = 'SOURCE_PROFILE_VERSION' AND decision_type IN ('RIGHTS_REVIEW', 'AUTOMATION_REVIEW', 'QUALITY_REVIEW', 'MEDICAL_SAFETY_REVIEW', 'SECURITY_REVIEW', 'APPROVAL', 'REJECTION', 'SUPERSESSION')) OR (entity_type = 'KNOWLEDGE_GAP' AND decision_type IN ('APPROVAL', 'REJECTION', 'GAP_RESOLUTION', 'GAP_REOPEN', 'SUPERSESSION')) OR (entity_type = 'WEEKLY_RUN' AND decision_type IN ('RUN_APPROVAL', 'APPROVAL', 'REJECTION', 'SUSPENSION', 'REVOCATION', 'SUPERSESSION')) OR (entity_type = 'WEEKLY_RUN_ATTEMPT' AND decision_type IN ('RUN_TERMINALIZATION', 'SUPERSESSION')) OR (entity_type = 'RUN_SOURCE_RESULT' AND decision_type IN ('RIGHTS_REVIEW', 'AUTOMATION_REVIEW', 'QUALITY_REVIEW', 'MEDICAL_SAFETY_REVIEW', 'SECURITY_REVIEW', 'APPROVAL', 'REJECTION', 'SUPERSESSION')) OR (entity_type = 'RUN_GAP_RESULT' AND decision_type IN ('QUALITY_REVIEW', 'APPROVAL', 'REJECTION', 'SUPERSESSION'))), 
	CONSTRAINT fk_i5gd_supersedes_same_entity_family FOREIGN KEY(supersedes_decision_id, entity_type, entity_id, decision_family) REFERENCES i5_governance_decisions (id, entity_type, entity_id, decision_family) ON DELETE RESTRICT
);
""")

    op.execute("""CREATE INDEX ix_weekly_knowledge_runs_id ON weekly_knowledge_runs (id);""")
    op.execute("""CREATE INDEX ix_wkr_approval_state ON weekly_knowledge_runs (approval_state);""")
    op.execute("""CREATE INDEX ix_wkr_latest_attempt_id ON weekly_knowledge_runs (latest_attempt_id);""")
    op.execute("""CREATE INDEX ix_wkr_schedule_window ON weekly_knowledge_runs (schedule_key, planned_window_start);""")
    op.execute("""CREATE INDEX ix_wkr_status_window ON weekly_knowledge_runs (status, planned_window_start);""")
    op.execute("""CREATE INDEX ix_wkr_successful_attempt_id ON weekly_knowledge_runs (successful_attempt_id);""")
    op.execute("""CREATE INDEX ix_wkr_supersedes_run_id ON weekly_knowledge_runs (supersedes_run_id);""")
    op.execute("""CREATE INDEX ix_weekly_knowledge_run_attempts_id ON weekly_knowledge_run_attempts (id);""")
    op.execute("""CREATE INDEX ix_wkra_retry_of_attempt_id ON weekly_knowledge_run_attempts (retry_of_attempt_id);""")
    op.execute("""CREATE INDEX ix_wkra_status_started_at ON weekly_knowledge_run_attempts (status, started_at);""")
    op.execute("""CREATE UNIQUE INDEX uq_wkra_one_successful_terminal ON weekly_knowledge_run_attempts (weekly_run_id) WHERE status IN ('COMPLETED', 'COMPLETED_WITH_WARNINGS');""")
    op.execute("""CREATE INDEX ix_kg_capability_id ON knowledge_gaps (capability_id);""")
    op.execute("""CREATE INDEX ix_kg_discovered_attempt_id ON knowledge_gaps (discovered_attempt_id);""")
    op.execute("""CREATE INDEX ix_kg_domain_subdomain ON knowledge_gaps (domain, subdomain);""")
    op.execute("""CREATE INDEX ix_kg_next_review_at ON knowledge_gaps (next_review_at);""")
    op.execute("""CREATE INDEX ix_kg_status_priority_severity ON knowledge_gaps (status, priority, severity);""")
    op.execute("""CREATE INDEX ix_kg_target_knowledge_unit_id ON knowledge_gaps (target_knowledge_unit_id);""")
    op.execute("""CREATE INDEX ix_kg_target_package_id ON knowledge_gaps (target_package_id);""")
    op.execute("""CREATE INDEX ix_kg_target_source_profile_id ON knowledge_gaps (target_source_profile_id);""")
    op.execute("""CREATE INDEX ix_knowledge_gaps_id ON knowledge_gaps (id);""")
    op.execute("""CREATE INDEX ix_weekly_run_source_results_id ON weekly_run_source_results (id);""")
    op.execute("""CREATE INDEX ix_wrsr_result_status ON weekly_run_source_results (result_status);""")
    op.execute("""CREATE INDEX ix_wrsr_source_profile_id ON weekly_run_source_results (source_profile_id);""")
    op.execute("""CREATE INDEX ix_weekly_run_gap_results_id ON weekly_run_gap_results (id);""")
    op.execute("""CREATE INDEX ix_wrgr_gap_id ON weekly_run_gap_results (gap_id);""")
    op.execute("""CREATE INDEX ix_wrgr_result_type ON weekly_run_gap_results (result_type);""")
    op.execute("""CREATE INDEX ix_i5_governance_decisions_id ON i5_governance_decisions (id);""")
    op.execute("""CREATE INDEX ix_i5gd_content_hash ON i5_governance_decisions (hash_algorithm, canonicalization_version, canonical_hash);""")
    op.execute("""CREATE INDEX ix_i5gd_decision_type ON i5_governance_decisions (decision_type);""")
    op.execute("""CREATE INDEX ix_i5gd_entity_history ON i5_governance_decisions (entity_type, entity_id, created_at, id);""")
    op.execute("""CREATE INDEX ix_i5gd_family_history ON i5_governance_decisions (entity_type, entity_id, decision_family, created_at, id);""")
    op.execute("""CREATE INDEX ix_i5gd_outcome ON i5_governance_decisions (outcome);""")
    op.execute("""CREATE UNIQUE INDEX uq_i5gd_one_root_per_family ON i5_governance_decisions (entity_type, entity_id, decision_family) WHERE supersedes_decision_id IS NULL;""")
    op.execute("""CREATE UNIQUE INDEX uq_i5gd_one_superseder ON i5_governance_decisions (supersedes_decision_id) WHERE supersedes_decision_id IS NOT NULL;""")

    # deferred / use_alter foreign keys
    op.create_foreign_key(
        'fk_wkr_latest_attempt_same_run',
        'weekly_knowledge_runs',
        'weekly_knowledge_run_attempts',
        ['id', 'latest_attempt_id'],
        ['weekly_run_id', 'id'], ondelete='RESTRICT', deferrable=True, initially='DEFERRED',
    )
    op.create_foreign_key(
        'fk_wkr_successful_attempt_same_run',
        'weekly_knowledge_runs',
        'weekly_knowledge_run_attempts',
        ['id', 'successful_attempt_id'],
        ['weekly_run_id', 'id'], ondelete='RESTRICT', deferrable=True, initially='DEFERRED',
    )



def downgrade() -> None:
    # drop deferred / use_alter foreign keys first
    op.drop_constraint('fk_wkr_latest_attempt_same_run', 'weekly_knowledge_runs', type_='foreignkey')
    op.drop_constraint('fk_wkr_successful_attempt_same_run', 'weekly_knowledge_runs', type_='foreignkey')

    op.drop_index('uq_i5gd_one_superseder', table_name='i5_governance_decisions')
    op.drop_index('uq_i5gd_one_root_per_family', table_name='i5_governance_decisions')
    op.drop_index('ix_i5gd_outcome', table_name='i5_governance_decisions')
    op.drop_index('ix_i5gd_family_history', table_name='i5_governance_decisions')
    op.drop_index('ix_i5gd_entity_history', table_name='i5_governance_decisions')
    op.drop_index('ix_i5gd_decision_type', table_name='i5_governance_decisions')
    op.drop_index('ix_i5gd_content_hash', table_name='i5_governance_decisions')
    op.drop_index('ix_i5_governance_decisions_id', table_name='i5_governance_decisions')
    op.drop_table('i5_governance_decisions')
    op.drop_index('ix_wrgr_result_type', table_name='weekly_run_gap_results')
    op.drop_index('ix_wrgr_gap_id', table_name='weekly_run_gap_results')
    op.drop_index('ix_weekly_run_gap_results_id', table_name='weekly_run_gap_results')
    op.drop_table('weekly_run_gap_results')
    op.drop_index('ix_wrsr_source_profile_id', table_name='weekly_run_source_results')
    op.drop_index('ix_wrsr_result_status', table_name='weekly_run_source_results')
    op.drop_index('ix_weekly_run_source_results_id', table_name='weekly_run_source_results')
    op.drop_table('weekly_run_source_results')
    op.drop_index('ix_knowledge_gaps_id', table_name='knowledge_gaps')
    op.drop_index('ix_kg_target_source_profile_id', table_name='knowledge_gaps')
    op.drop_index('ix_kg_target_package_id', table_name='knowledge_gaps')
    op.drop_index('ix_kg_target_knowledge_unit_id', table_name='knowledge_gaps')
    op.drop_index('ix_kg_status_priority_severity', table_name='knowledge_gaps')
    op.drop_index('ix_kg_next_review_at', table_name='knowledge_gaps')
    op.drop_index('ix_kg_domain_subdomain', table_name='knowledge_gaps')
    op.drop_index('ix_kg_discovered_attempt_id', table_name='knowledge_gaps')
    op.drop_index('ix_kg_capability_id', table_name='knowledge_gaps')
    op.drop_table('knowledge_gaps')
    op.drop_index('uq_wkra_one_successful_terminal', table_name='weekly_knowledge_run_attempts')
    op.drop_index('ix_wkra_status_started_at', table_name='weekly_knowledge_run_attempts')
    op.drop_index('ix_wkra_retry_of_attempt_id', table_name='weekly_knowledge_run_attempts')
    op.drop_index('ix_weekly_knowledge_run_attempts_id', table_name='weekly_knowledge_run_attempts')
    op.drop_table('weekly_knowledge_run_attempts')
    op.drop_index('ix_wkr_supersedes_run_id', table_name='weekly_knowledge_runs')
    op.drop_index('ix_wkr_successful_attempt_id', table_name='weekly_knowledge_runs')
    op.drop_index('ix_wkr_status_window', table_name='weekly_knowledge_runs')
    op.drop_index('ix_wkr_schedule_window', table_name='weekly_knowledge_runs')
    op.drop_index('ix_wkr_latest_attempt_id', table_name='weekly_knowledge_runs')
    op.drop_index('ix_wkr_approval_state', table_name='weekly_knowledge_runs')
    op.drop_index('ix_weekly_knowledge_runs_id', table_name='weekly_knowledge_runs')
    op.drop_table('weekly_knowledge_runs')

    op.drop_index('ix_gsp_registry_runtime', table_name='governed_source_profiles')
    op.drop_index('ix_gsp_last_reviewed_at', table_name='governed_source_profiles')
    op.drop_index('ix_gsp_last_checked_at', table_name='governed_source_profiles')
    op.drop_index('ix_gsp_runtime_eligibility', table_name='governed_source_profiles')
    op.drop_index('ix_gsp_registry_state', table_name='governed_source_profiles')
    op.drop_constraint('ck_gsp_effective_window_order', 'governed_source_profiles', type_='check')
    op.drop_constraint('ck_gsp_block_reason_length', 'governed_source_profiles', type_='check')
    op.drop_constraint('ck_gsp_runtime_eligibility_vocab', 'governed_source_profiles', type_='check')
    op.drop_constraint('ck_gsp_registry_state_vocab', 'governed_source_profiles', type_='check')
    op.drop_column('governed_source_profiles', 'canonicalization_version')
    op.drop_column('governed_source_profiles', 'last_reviewed_at')
    op.drop_column('governed_source_profiles', 'last_checked_at')
    op.drop_column('governed_source_profiles', 'last_discovered_at')
    op.drop_column('governed_source_profiles', 'effective_to')
    op.drop_column('governed_source_profiles', 'effective_from')
    op.drop_column('governed_source_profiles', 'topic_coverage')
    op.drop_column('governed_source_profiles', 'approver_reference')
    op.drop_column('governed_source_profiles', 'reviewer_reference')
    op.drop_column('governed_source_profiles', 'owner_reference')
    op.drop_column('governed_source_profiles', 'block_reason')
    op.drop_column('governed_source_profiles', 'runtime_eligibility')
    op.drop_column('governed_source_profiles', 'registry_state')
