"""I5 W1-P02 KU / raw evidence / provenance

Revision ID: 054_i5_w1_p02_ku_provenance
Revises: 053_i5_w1_p01_weekly_governance

MIG-I5-W1-P02 — schema authoring for current frozen ORM (W6-P01).
Additive PostgreSQL-only. Exact ORM CHECK/FK/UQ/Index parity.
No seed, network, activation, or Base.metadata.create_all.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "054_i5_w1_p02_ku_provenance"
down_revision: Union[str, None] = "053_i5_w1_p01_weekly_governance"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- knowledge_units ---
    op.execute("""

CREATE TABLE knowledge_units (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	canonical_unit_id VARCHAR(64) NOT NULL, 
	immutable_version_id VARCHAR(64) NOT NULL, 
	domain VARCHAR(128) NOT NULL, 
	topic_taxonomy VARCHAR(256), 
	disease_or_health_condition VARCHAR(256), 
	manifest_entity_id VARCHAR(16), 
	manifest_track_id VARCHAR(64), 
	language VARCHAR(32) DEFAULT 'en' NOT NULL, 
	knowledge_type VARCHAR(32) NOT NULL, 
	normalized_statement TEXT NOT NULL, 
	applicability TEXT, 
	exclusions TEXT, 
	population VARCHAR(256), 
	jurisdiction VARCHAR(64), 
	evidence_strength VARCHAR(32) DEFAULT 'UNKNOWN' NOT NULL, 
	medical_safety_state VARCHAR(32) DEFAULT 'UNKNOWN' NOT NULL, 
	conflict_state VARCHAR(32) DEFAULT 'NONE' NOT NULL, 
	freshness_state VARCHAR(32) DEFAULT 'UNKNOWN' NOT NULL, 
	review_state VARCHAR(32) DEFAULT 'NOT_REVIEWED' NOT NULL, 
	publication_state VARCHAR(32) DEFAULT 'DRAFT' NOT NULL, 
	runtime_eligibility VARCHAR(32) DEFAULT 'NOT_ELIGIBLE' NOT NULL, 
	provenance_complete BOOLEAN DEFAULT false NOT NULL, 
	deduplication_key VARCHAR(64) NOT NULL, 
	canonical_hash VARCHAR(64) NOT NULL, 
	hash_algorithm VARCHAR(32) DEFAULT 'SHA-256' NOT NULL, 
	canonicalization_version VARCHAR(32) DEFAULT 'v1' NOT NULL, 
	supersedes_unit_id INTEGER, 
	retraction_reason TEXT, 
	valid_from TIMESTAMP WITHOUT TIME ZONE, 
	valid_until TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	last_reviewed_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_ku_knowledge_type_vocab CHECK (knowledge_type IN ('FACT', 'GUIDELINE', 'RECOMMENDATION', 'WARNING', 'DEFINITION', 'PROCEDURE', 'OTHER')), 
	CONSTRAINT ck_ku_evidence_strength_vocab CHECK (evidence_strength IN ('UNKNOWN', 'LOW', 'MODERATE', 'HIGH', 'CONFLICTED')), 
	CONSTRAINT ck_ku_medical_safety_state_vocab CHECK (medical_safety_state IN ('UNKNOWN', 'PENDING_REVIEW', 'CLEARED', 'RESTRICTED', 'BLOCKED')), 
	CONSTRAINT ck_ku_conflict_state_vocab CHECK (conflict_state IN ('NONE', 'SUSPECTED', 'CONFIRMED', 'RESOLVED')), 
	CONSTRAINT ck_ku_freshness_state_vocab CHECK (freshness_state IN ('UNKNOWN', 'CURRENT', 'STALE', 'EXPIRED')), 
	CONSTRAINT ck_ku_review_state_vocab CHECK (review_state IN ('NOT_REVIEWED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'DEFERRED')), 
	CONSTRAINT ck_ku_publication_state_vocab CHECK (publication_state IN ('DRAFT', 'CANDIDATE', 'PUBLISHED', 'WITHDRAWN', 'SUPERSEDED')), 
	CONSTRAINT ck_ku_runtime_eligibility_vocab CHECK (runtime_eligibility IN ('NOT_ELIGIBLE', 'REVIEW_REQUIRED', 'ELIGIBLE', 'SUSPENDED', 'REVOKED')), 
	CONSTRAINT ck_ku_canonical_hash_format CHECK (canonical_hash ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_ku_deduplication_key_format CHECK (deduplication_key ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_ku_hash_algorithm_constant CHECK (hash_algorithm = 'SHA-256'), 
	CONSTRAINT ck_ku_canonicalization_version_constant CHECK (canonicalization_version = 'v1'), 
	CONSTRAINT ck_ku_normalized_statement_nonempty CHECK (char_length(normalized_statement) >= 1), 
	CONSTRAINT ck_ku_supersedes_not_self CHECK (supersedes_unit_id IS NULL OR supersedes_unit_id <> id), 
	CONSTRAINT ck_ku_eligible_requires_provenance CHECK ((runtime_eligibility <> 'ELIGIBLE') OR (provenance_complete = true)), 
	CONSTRAINT uq_ku_canonical_version UNIQUE (canonical_unit_id, immutable_version_id), 
	CONSTRAINT uq_ku_deduplication_key UNIQUE (deduplication_key), 
	CONSTRAINT fk_ku_supersedes_unit_id FOREIGN KEY(supersedes_unit_id) REFERENCES knowledge_units (id) ON DELETE RESTRICT
);
""")

    # --- i5_raw_evidence ---
    op.execute("""

CREATE TABLE i5_raw_evidence (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	source_profile_id INTEGER NOT NULL, 
	source_document_id VARCHAR(128), 
	source_version_id VARCHAR(128), 
	retrieval_run_id INTEGER, 
	retrieval_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	canonical_url TEXT NOT NULL, 
	content_hash VARCHAR(64) NOT NULL, 
	byte_hash VARCHAR(64), 
	normalized_hash VARCHAR(64), 
	hash_algorithm VARCHAR(32) DEFAULT 'SHA-256' NOT NULL, 
	mime_type VARCHAR(128), 
	language VARCHAR(32), 
	jurisdiction VARCHAR(64), 
	storage_mode VARCHAR(64) DEFAULT 'NONE' NOT NULL, 
	retention_mode VARCHAR(64) NOT NULL, 
	rights_terms_state VARCHAR(32) DEFAULT 'UNKNOWN' NOT NULL, 
	robots_access_state VARCHAR(32) DEFAULT 'UNKNOWN' NOT NULL, 
	redaction_state VARCHAR(32) DEFAULT 'NONE' NOT NULL, 
	prohibited_data_state VARCHAR(32) DEFAULT 'UNKNOWN' NOT NULL, 
	expiry_state VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL, 
	supersedes_raw_evidence_id INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	created_by_run_id INTEGER, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_ire_retention_mode_vocab CHECK (retention_mode IN ('RAW_FULL_GOVERNED_RETENTION', 'RAW_TRANSIENT_PROCESSING', 'RAW_MINIMAL_EVIDENCE_ONLY', 'RAW_LINK_AND_CITATION_ONLY', 'RAW_EXCLUDED_PROTECTED_ELEMENTS')), 
	CONSTRAINT ck_ire_storage_mode_vocab CHECK (storage_mode IN ('OBJECT_STORE', 'DATABASE_INLINE', 'EXTERNAL_REFERENCE', 'NONE')), 
	CONSTRAINT ck_ire_rights_terms_state_vocab CHECK (rights_terms_state IN ('UNKNOWN', 'UNDER_REVIEW', 'APPROVED', 'RESTRICTED', 'PROHIBITED', 'EXPIRED')), 
	CONSTRAINT ck_ire_robots_access_state_vocab CHECK (robots_access_state IN ('UNKNOWN', 'ALLOWED', 'DISALLOWED', 'CONDITIONAL', 'NOT_APPLICABLE')), 
	CONSTRAINT ck_ire_redaction_state_vocab CHECK (redaction_state IN ('NONE', 'PARTIAL', 'FULL', 'REQUIRED')), 
	CONSTRAINT ck_ire_prohibited_data_state_vocab CHECK (prohibited_data_state IN ('CLEARED', 'SUSPECTED', 'CONFIRMED_PROHIBITED', 'UNKNOWN')), 
	CONSTRAINT ck_ire_expiry_state_vocab CHECK (expiry_state IN ('ACTIVE', 'EXPIRING', 'EXPIRED', 'TOMBSTONED', 'SUPERSEDED')), 
	CONSTRAINT ck_ire_content_hash_format CHECK (content_hash ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_ire_byte_hash_format CHECK (byte_hash IS NULL OR byte_hash ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_ire_normalized_hash_format CHECK (normalized_hash IS NULL OR normalized_hash ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_ire_hash_algorithm_constant CHECK (hash_algorithm = 'SHA-256'), 
	CONSTRAINT ck_ire_canonical_url_nonempty CHECK (char_length(canonical_url) >= 1), 
	CONSTRAINT ck_ire_supersedes_not_self CHECK (supersedes_raw_evidence_id IS NULL OR supersedes_raw_evidence_id <> id), 
	CONSTRAINT ck_ire_prohibited_requires_excluded_mode CHECK ((prohibited_data_state <> 'CONFIRMED_PROHIBITED') OR (retention_mode = 'RAW_EXCLUDED_PROTECTED_ELEMENTS')), 
	CONSTRAINT uq_ire_content_source_url UNIQUE (content_hash, source_profile_id, canonical_url), 
	CONSTRAINT fk_ire_source_profile_id FOREIGN KEY(source_profile_id) REFERENCES governed_source_profiles (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_ire_retrieval_run_id FOREIGN KEY(retrieval_run_id) REFERENCES weekly_knowledge_runs (id) ON DELETE SET NULL, 
	CONSTRAINT fk_ire_supersedes_raw_evidence_id FOREIGN KEY(supersedes_raw_evidence_id) REFERENCES i5_raw_evidence (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_ire_created_by_run_id FOREIGN KEY(created_by_run_id) REFERENCES weekly_knowledge_runs (id) ON DELETE SET NULL
);
""")

    # --- knowledge_provenance ---
    op.execute("""

CREATE TABLE knowledge_provenance (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	knowledge_unit_id INTEGER NOT NULL, 
	source_profile_id INTEGER NOT NULL, 
	source_document_id VARCHAR(128), 
	source_version_id VARCHAR(128), 
	raw_evidence_id INTEGER, 
	retrieval_method VARCHAR(128) NOT NULL, 
	access_route VARCHAR(128), 
	content_hash VARCHAR(64), 
	byte_hash VARCHAR(64), 
	normalized_hash VARCHAR(64), 
	extraction_process VARCHAR(256), 
	normalization_process VARCHAR(256), 
	review_decision_id INTEGER, 
	attribution_data TEXT, 
	citation_rendering_data TEXT, 
	conflict_hook VARCHAR(256), 
	supersession_hook VARCHAR(256), 
	retraction_hook VARCHAR(256), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_kp_content_hash_format CHECK (content_hash IS NULL OR content_hash ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_kp_byte_hash_format CHECK (byte_hash IS NULL OR byte_hash ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_kp_normalized_hash_format CHECK (normalized_hash IS NULL OR normalized_hash ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_kp_retrieval_method_nonempty CHECK (char_length(retrieval_method) >= 1), 
	CONSTRAINT uq_kp_knowledge_unit_id UNIQUE (knowledge_unit_id), 
	CONSTRAINT fk_kp_knowledge_unit_id FOREIGN KEY(knowledge_unit_id) REFERENCES knowledge_units (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_kp_source_profile_id FOREIGN KEY(source_profile_id) REFERENCES governed_source_profiles (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_kp_raw_evidence_id FOREIGN KEY(raw_evidence_id) REFERENCES i5_raw_evidence (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_kp_review_decision_id FOREIGN KEY(review_decision_id) REFERENCES i5_governance_decisions (id) ON DELETE SET NULL
);
""")

    op.execute("""CREATE INDEX ix_knowledge_units_id ON knowledge_units (id);""")
    op.execute("""CREATE INDEX ix_ku_canonical_hash ON knowledge_units (canonical_hash);""")
    op.execute("""CREATE INDEX ix_ku_domain ON knowledge_units (domain);""")
    op.execute("""CREATE INDEX ix_ku_manifest_track_id ON knowledge_units (manifest_track_id);""")
    op.execute("""CREATE INDEX ix_ku_runtime_eligibility ON knowledge_units (runtime_eligibility);""")
    op.execute("""CREATE INDEX ix_i5_raw_evidence_id ON i5_raw_evidence (id);""")
    op.execute("""CREATE INDEX ix_ire_content_hash ON i5_raw_evidence (content_hash);""")
    op.execute("""CREATE INDEX ix_ire_retention_mode ON i5_raw_evidence (retention_mode);""")
    op.execute("""CREATE INDEX ix_ire_retrieval_run_id ON i5_raw_evidence (retrieval_run_id);""")
    op.execute("""CREATE INDEX ix_ire_source_profile_id ON i5_raw_evidence (source_profile_id);""")
    op.execute("""CREATE INDEX ix_knowledge_provenance_id ON knowledge_provenance (id);""")
    op.execute("""CREATE INDEX ix_kp_raw_evidence_id ON knowledge_provenance (raw_evidence_id);""")
    op.execute("""CREATE INDEX ix_kp_source_profile_id ON knowledge_provenance (source_profile_id);""")

    # Deferred from 053: KnowledgeGap.target_knowledge_unit_id
    op.create_foreign_key('fk_knowledge_gaps_target_knowledge_unit_id', 'knowledge_gaps', 'knowledge_units', ['target_knowledge_unit_id'], ['id'], ondelete='RESTRICT')


def downgrade() -> None:
    op.drop_constraint('fk_knowledge_gaps_target_knowledge_unit_id', 'knowledge_gaps', type_='foreignkey')
    op.drop_index('ix_kp_source_profile_id', table_name='knowledge_provenance')
    op.drop_index('ix_kp_raw_evidence_id', table_name='knowledge_provenance')
    op.drop_index('ix_knowledge_provenance_id', table_name='knowledge_provenance')
    op.drop_table('knowledge_provenance')
    op.drop_index('ix_ire_source_profile_id', table_name='i5_raw_evidence')
    op.drop_index('ix_ire_retrieval_run_id', table_name='i5_raw_evidence')
    op.drop_index('ix_ire_retention_mode', table_name='i5_raw_evidence')
    op.drop_index('ix_ire_content_hash', table_name='i5_raw_evidence')
    op.drop_index('ix_i5_raw_evidence_id', table_name='i5_raw_evidence')
    op.drop_table('i5_raw_evidence')
    op.drop_index('ix_ku_runtime_eligibility', table_name='knowledge_units')
    op.drop_index('ix_ku_manifest_track_id', table_name='knowledge_units')
    op.drop_index('ix_ku_domain', table_name='knowledge_units')
    op.drop_index('ix_ku_canonical_hash', table_name='knowledge_units')
    op.drop_index('ix_knowledge_units_id', table_name='knowledge_units')
    op.drop_table('knowledge_units')
