"""I5 W2-P01 knowledge memory / transitions

Revision ID: 055_i5_w2_p01_knowledge_memory
Revises: 054_i5_w1_p02_ku_provenance

MIG-I5-W2-P01 — schema authoring for current frozen ORM (W6-P01).
Additive PostgreSQL-only. Exact ORM CHECK/FK/UQ/Index parity.
No seed, network, activation, or Base.metadata.create_all.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "055_i5_w2_p01_knowledge_memory"
down_revision: Union[str, None] = "054_i5_w1_p02_ku_provenance"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- knowledge_memory_items ---
    op.execute("""

CREATE TABLE knowledge_memory_items (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	memory_item_id VARCHAR(64) NOT NULL, 
	knowledge_unit_id INTEGER NOT NULL, 
	domain VARCHAR(128) NOT NULL, 
	topic VARCHAR(256), 
	knowledge_version VARCHAR(64) NOT NULL, 
	source_ids TEXT, 
	source_versions TEXT, 
	evidence_strength VARCHAR(32) DEFAULT 'UNKNOWN' NOT NULL, 
	freshness_state VARCHAR(32) DEFAULT 'UNKNOWN' NOT NULL, 
	conflict_state VARCHAR(32) DEFAULT 'NONE' NOT NULL, 
	medical_safety_state VARCHAR(32) DEFAULT 'UNKNOWN' NOT NULL, 
	runtime_eligibility VARCHAR(32) DEFAULT 'NOT_ELIGIBLE' NOT NULL, 
	supersession_state VARCHAR(32) DEFAULT 'CURRENT' NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_kmi_evidence_strength_vocab CHECK (evidence_strength IN ('UNKNOWN', 'LOW', 'MODERATE', 'HIGH', 'CONFLICTED')), 
	CONSTRAINT ck_kmi_freshness_state_vocab CHECK (freshness_state IN ('UNKNOWN', 'CURRENT', 'STALE', 'EXPIRED')), 
	CONSTRAINT ck_kmi_conflict_state_vocab CHECK (conflict_state IN ('NONE', 'SUSPECTED', 'CONFIRMED', 'RESOLVED')), 
	CONSTRAINT ck_kmi_medical_safety_state_vocab CHECK (medical_safety_state IN ('UNKNOWN', 'PENDING_REVIEW', 'CLEARED', 'RESTRICTED', 'BLOCKED')), 
	CONSTRAINT ck_kmi_runtime_eligibility_vocab CHECK (runtime_eligibility IN ('NOT_ELIGIBLE', 'REVIEW_REQUIRED', 'ELIGIBLE', 'SUSPENDED', 'REVOKED')), 
	CONSTRAINT ck_kmi_supersession_state_vocab CHECK (supersession_state IN ('CURRENT', 'SUPERSEDED', 'STALE', 'WITHDRAWN', 'CONFLICTED', 'UNDER_REVIEW', 'REJECTED', 'RETRACTED')), 
	CONSTRAINT ck_kmi_eligible_requires_current CHECK ((runtime_eligibility <> 'ELIGIBLE') OR (supersession_state = 'CURRENT')), 
	CONSTRAINT uq_kmi_memory_item_id UNIQUE (memory_item_id), 
	CONSTRAINT uq_kmi_knowledge_unit_id UNIQUE (knowledge_unit_id), 
	CONSTRAINT fk_kmi_knowledge_unit_id FOREIGN KEY(knowledge_unit_id) REFERENCES knowledge_units (id) ON DELETE RESTRICT
);
""")

    # --- knowledge_memory_transitions ---
    op.execute("""

CREATE TABLE knowledge_memory_transitions (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	memory_row_id INTEGER NOT NULL, 
	memory_item_id VARCHAR(64) NOT NULL, 
	from_knowledge_unit_id INTEGER, 
	to_knowledge_unit_id INTEGER, 
	transition_kind VARCHAR(32) NOT NULL, 
	change_kind VARCHAR(32) NOT NULL, 
	diff_json TEXT, 
	idempotency_key VARCHAR(64) NOT NULL, 
	reason TEXT, 
	process_id VARCHAR(128) DEFAULT 'W2P01_SUPERSESSION_SERVICE' NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_kmt_transition_kind_vocab CHECK (transition_kind IN ('CREATED', 'NO_CHANGE', 'SUPERSEDED', 'RETRACTED', 'WITHDRAWN', 'CURRENT_VERSION_CHANGED')), 
	CONSTRAINT ck_kmt_change_kind_vocab CHECK (change_kind IN ('NO_MATERIAL_CHANGE', 'CONTENT_CHANGE', 'SOURCE_METADATA_CHANGE', 'PROVENANCE_CHANGE', 'SAFETY_GOVERNANCE_CHANGE', 'RETRACTION_WITHDRAWAL')), 
	CONSTRAINT ck_kmt_idempotency_key_format CHECK (idempotency_key ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_kmt_diff_json_object CHECK (diff_json IS NULL OR (char_length(diff_json) >= 2 AND left(diff_json, 1) = '{' AND right(diff_json, 1) = '}')), 
	CONSTRAINT uq_kmt_idempotency_key UNIQUE (idempotency_key), 
	CONSTRAINT fk_kmt_memory_item_row_id FOREIGN KEY(memory_row_id) REFERENCES knowledge_memory_items (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_kmt_from_knowledge_unit_id FOREIGN KEY(from_knowledge_unit_id) REFERENCES knowledge_units (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_kmt_to_knowledge_unit_id FOREIGN KEY(to_knowledge_unit_id) REFERENCES knowledge_units (id) ON DELETE RESTRICT
);
""")

    op.execute("""CREATE INDEX ix_kmi_domain ON knowledge_memory_items (domain);""")
    op.execute("""CREATE INDEX ix_kmi_runtime_eligibility ON knowledge_memory_items (runtime_eligibility);""")
    op.execute("""CREATE INDEX ix_kmi_supersession_state ON knowledge_memory_items (supersession_state);""")
    op.execute("""CREATE INDEX ix_knowledge_memory_items_id ON knowledge_memory_items (id);""")
    op.execute("""CREATE INDEX ix_kmt_created_at ON knowledge_memory_transitions (created_at);""")
    op.execute("""CREATE INDEX ix_kmt_memory_item_id ON knowledge_memory_transitions (memory_item_id);""")
    op.execute("""CREATE INDEX ix_knowledge_memory_transitions_id ON knowledge_memory_transitions (id);""")



def downgrade() -> None:
    op.drop_index('ix_knowledge_memory_transitions_id', table_name='knowledge_memory_transitions')
    op.drop_index('ix_kmt_memory_item_id', table_name='knowledge_memory_transitions')
    op.drop_index('ix_kmt_created_at', table_name='knowledge_memory_transitions')
    op.drop_table('knowledge_memory_transitions')
    op.drop_index('ix_knowledge_memory_items_id', table_name='knowledge_memory_items')
    op.drop_index('ix_kmi_supersession_state', table_name='knowledge_memory_items')
    op.drop_index('ix_kmi_runtime_eligibility', table_name='knowledge_memory_items')
    op.drop_index('ix_kmi_domain', table_name='knowledge_memory_items')
    op.drop_table('knowledge_memory_items')
