"""I5 W2-P02 conflict / medical-safety review

Revision ID: 056_i5_w2_p02_conflict_safety
Revises: 055_i5_w2_p01_knowledge_memory

MIG-I5-W2-P02 — schema authoring for current frozen ORM (W6-P01).
Additive PostgreSQL-only. Exact ORM CHECK/FK/UQ/Index parity.
No seed, network, activation, or Base.metadata.create_all.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "056_i5_w2_p02_conflict_safety"
down_revision: Union[str, None] = "055_i5_w2_p01_knowledge_memory"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- knowledge_conflicts ---
    op.execute("""

CREATE TABLE knowledge_conflicts (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	conflict_key VARCHAR(64) NOT NULL, 
	knowledge_unit_id_a INTEGER NOT NULL, 
	knowledge_unit_id_b INTEGER NOT NULL, 
	conflict_state VARCHAR(32) DEFAULT 'SUSPECTED' NOT NULL, 
	conflict_summary TEXT, 
	resolution_note TEXT, 
	idempotency_key VARCHAR(64) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_kc_conflict_state_vocab CHECK (conflict_state IN ('NONE', 'SUSPECTED', 'CONFIRMED', 'RESOLVED')), 
	CONSTRAINT ck_kc_idempotency_key_format CHECK (idempotency_key ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_kc_units_ordered CHECK (knowledge_unit_id_a < knowledge_unit_id_b), 
	CONSTRAINT uq_kc_idempotency_key UNIQUE (idempotency_key), 
	CONSTRAINT uq_kc_conflict_key UNIQUE (conflict_key), 
	CONSTRAINT uq_kc_unit_pair UNIQUE (knowledge_unit_id_a, knowledge_unit_id_b), 
	CONSTRAINT fk_kc_ku_a FOREIGN KEY(knowledge_unit_id_a) REFERENCES knowledge_units (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_kc_ku_b FOREIGN KEY(knowledge_unit_id_b) REFERENCES knowledge_units (id) ON DELETE RESTRICT
);
""")

    # --- knowledge_safety_reviews ---
    op.execute("""

CREATE TABLE knowledge_safety_reviews (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	queue_item_id VARCHAR(64) NOT NULL, 
	knowledge_unit_id INTEGER NOT NULL, 
	queue_status VARCHAR(32) DEFAULT 'OPEN' NOT NULL, 
	medical_safety_state VARCHAR(32) NOT NULL, 
	high_risk_domain BOOLEAN DEFAULT false NOT NULL, 
	reason TEXT, 
	decision_id INTEGER, 
	idempotency_key VARCHAR(64) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_ksr_queue_status_vocab CHECK (queue_status IN ('OPEN', 'IN_REVIEW', 'CLOSED_CLEARED', 'CLOSED_RESTRICTED', 'CLOSED_BLOCKED', 'CLOSED_REJECTED')), 
	CONSTRAINT ck_ksr_medical_safety_state_vocab CHECK (medical_safety_state IN ('UNKNOWN', 'PENDING_REVIEW', 'CLEARED', 'RESTRICTED', 'BLOCKED')), 
	CONSTRAINT ck_ksr_idempotency_key_format CHECK (idempotency_key ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT uq_ksr_queue_item_id UNIQUE (queue_item_id), 
	CONSTRAINT uq_ksr_idempotency_key UNIQUE (idempotency_key), 
	CONSTRAINT fk_ksr_knowledge_unit_id FOREIGN KEY(knowledge_unit_id) REFERENCES knowledge_units (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_ksr_decision_id FOREIGN KEY(decision_id) REFERENCES i5_governance_decisions (id) ON DELETE SET NULL
);
""")

    op.execute("""CREATE INDEX ix_kc_conflict_state ON knowledge_conflicts (conflict_state);""")
    op.execute("""CREATE INDEX ix_kc_ku_a ON knowledge_conflicts (knowledge_unit_id_a);""")
    op.execute("""CREATE INDEX ix_kc_ku_b ON knowledge_conflicts (knowledge_unit_id_b);""")
    op.execute("""CREATE INDEX ix_knowledge_conflicts_id ON knowledge_conflicts (id);""")
    op.execute("""CREATE INDEX ix_knowledge_safety_reviews_id ON knowledge_safety_reviews (id);""")
    op.execute("""CREATE INDEX ix_ksr_knowledge_unit_id ON knowledge_safety_reviews (knowledge_unit_id);""")
    op.execute("""CREATE INDEX ix_ksr_queue_status ON knowledge_safety_reviews (queue_status);""")



def downgrade() -> None:
    op.drop_index('ix_ksr_queue_status', table_name='knowledge_safety_reviews')
    op.drop_index('ix_ksr_knowledge_unit_id', table_name='knowledge_safety_reviews')
    op.drop_index('ix_knowledge_safety_reviews_id', table_name='knowledge_safety_reviews')
    op.drop_table('knowledge_safety_reviews')
    op.drop_index('ix_knowledge_conflicts_id', table_name='knowledge_conflicts')
    op.drop_index('ix_kc_ku_b', table_name='knowledge_conflicts')
    op.drop_index('ix_kc_ku_a', table_name='knowledge_conflicts')
    op.drop_index('ix_kc_conflict_state', table_name='knowledge_conflicts')
    op.drop_table('knowledge_conflicts')
