"""DB-03 Wave 1 — additive foundations

Revision ID: 058_db03_w1_additive_foundations
Revises: 057_db03_w0_drift_normalization

MIG-DB03-W1 — §270.D/F/Q
Additive PostgreSQL-only. Exact frozen NEW tables + EXTEND columns.
No clinical window seeds. No pgvector. No rag_embeddings.
"""
from typing import Sequence, Union

from alembic import op


revision: str = "058_db03_w1_additive_foundations"
down_revision: Union[str, None] = "057_db03_w0_drift_normalization"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE user_consents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    subject_user_id INTEGER NOT NULL,
    consent_type VARCHAR(64) NOT NULL,
    purpose VARCHAR(128) NOT NULL,
    scope_summary TEXT,
    grantee_type VARCHAR(64) NOT NULL,
    grantee_id VARCHAR(128) NOT NULL,
    relationship_id INTEGER,
    status VARCHAR(16) DEFAULT 'pending' NOT NULL,
    policy_version VARCHAR(32),
    granted_at TIMESTAMPTZ,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_until TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revocation_reason TEXT,
    source VARCHAR(64),
    provenance TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_user_consents_status_vocab CHECK (status IN ('pending', 'active', 'revoked', 'expired')),
    CONSTRAINT fk_user_consents_subject_user_id FOREIGN KEY (subject_user_id) REFERENCES users(id) ON DELETE RESTRICT
);
"""
    )
    op.execute(
        """
CREATE UNIQUE INDEX uq_user_consents_active_grant
ON user_consents (subject_user_id, consent_type, purpose, grantee_type, grantee_id, effective_from)
WHERE status = 'active';
"""
    )
    op.execute("""CREATE INDEX ix_user_consents_subject_user_id ON user_consents (subject_user_id);""")
    op.execute("""CREATE INDEX ix_user_consents_status ON user_consents (status);""")
    op.execute("""CREATE INDEX ix_user_consents_id ON user_consents (id);""")
    op.execute("""COMMENT ON TABLE user_consents IS 'DB-03 durable consent authority; caregiver relationship != medical notify authorization';""")

    op.execute(
        """
CREATE TABLE user_consent_scopes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    consent_id INTEGER NOT NULL,
    permission_key VARCHAR(128) NOT NULL,
    allowed BOOLEAN DEFAULT false NOT NULL,
    metadata TEXT,
    PRIMARY KEY (id),
    CONSTRAINT uq_user_consent_scopes_consent_permission UNIQUE (consent_id, permission_key),
    CONSTRAINT fk_user_consent_scopes_consent_id FOREIGN KEY (consent_id) REFERENCES user_consents(id) ON DELETE CASCADE
);
"""
    )
    op.execute("""CREATE INDEX ix_user_consent_scopes_consent_id ON user_consent_scopes (consent_id);""")
    op.execute("""CREATE INDEX ix_user_consent_scopes_id ON user_consent_scopes (id);""")
    op.execute("""COMMENT ON TABLE user_consent_scopes IS 'DB-03 consent permission scopes (grantee/purpose granularity)';""")

    op.execute(
        """
CREATE TABLE care_response_policies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    policy_id VARCHAR(64) NOT NULL,
    policy_version VARCHAR(32) NOT NULL,
    risk_category VARCHAR(64) NOT NULL,
    ack_window_seconds INTEGER,
    escalation_window_seconds INTEGER,
    expiry_behavior VARCHAR(64),
    recipient_rules_json TEXT,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_until TIMESTAMPTZ,
    status VARCHAR(32) DEFAULT 'draft' NOT NULL,
    approval_metadata TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_crp_policy_id_version UNIQUE (policy_id, policy_version)
);
"""
    )
    op.execute("""CREATE INDEX ix_crp_status ON care_response_policies (status);""")
    op.execute("""CREATE INDEX ix_care_response_policies_id ON care_response_policies (id);""")
    op.execute(
        """COMMENT ON TABLE care_response_policies IS 'DB-03 versioned care policy; ack/escalation windows NULL until clinical policy Gate';"""
    )
    op.execute(
        """COMMENT ON COLUMN care_response_policies.ack_window_seconds IS 'MUST remain NULL until authorized clinical policy; no invented defaults';"""
    )
    op.execute(
        """COMMENT ON COLUMN care_response_policies.escalation_window_seconds IS 'MUST remain NULL until authorized clinical policy; no invented defaults';"""
    )

    op.execute(
        """
CREATE TABLE care_episodes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    user_id INTEGER NOT NULL,
    origin_type VARCHAR(64) NOT NULL,
    origin_ref VARCHAR(255),
    category VARCHAR(64),
    policy_id VARCHAR(64),
    policy_version VARCHAR(32),
    opened_at TIMESTAMPTZ NOT NULL,
    current_state VARCHAR(64) DEFAULT 'open' NOT NULL,
    resolved_at TIMESTAMPTZ,
    resolution_reason TEXT,
    ack_due_at TIMESTAMPTZ,
    escalation_due_at TIMESTAMPTZ,
    expired_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_ce_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);
"""
    )
    op.execute("""CREATE INDEX ix_ce_user_id ON care_episodes (user_id);""")
    op.execute("""CREATE INDEX ix_ce_current_state ON care_episodes (current_state);""")
    op.execute("""CREATE INDEX ix_ce_opened_at ON care_episodes (opened_at);""")
    op.execute("""CREATE INDEX ix_care_episodes_id ON care_episodes (id);""")
    op.execute("""COMMENT ON TABLE care_episodes IS 'DB-03 care continuity spine; not a diagnosis';""")

    op.execute(
        """
CREATE TABLE care_episode_links (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    episode_id INTEGER NOT NULL,
    link_type VARCHAR(64) NOT NULL,
    link_table VARCHAR(128) NOT NULL,
    link_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_cel_episode_type_id UNIQUE (episode_id, link_type, link_id),
    CONSTRAINT fk_cel_episode_id FOREIGN KEY (episode_id) REFERENCES care_episodes(id) ON DELETE CASCADE
);
"""
    )
    op.execute("""CREATE INDEX ix_cel_episode_id ON care_episode_links (episode_id);""")
    op.execute("""CREATE INDEX ix_care_episode_links_id ON care_episode_links (id);""")

    op.execute(
        """
CREATE TABLE user_period_summaries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    user_id INTEGER NOT NULL,
    summary_type VARCHAR(16) NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    version INTEGER DEFAULT 1 NOT NULL,
    structured_summary_json TEXT,
    narrative_summary TEXT,
    evidence_range TEXT,
    generated_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(32) DEFAULT 'active' NOT NULL,
    superseded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_ups_summary_type_vocab CHECK (summary_type IN ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY')),
    CONSTRAINT uq_ups_user_type_period_version UNIQUE (user_id, summary_type, period_start, version),
    CONSTRAINT fk_ups_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
"""
    )
    op.execute("""CREATE INDEX ix_ups_user_id ON user_period_summaries (user_id);""")
    op.execute("""CREATE INDEX ix_ups_summary_type ON user_period_summaries (summary_type);""")
    op.execute("""CREATE INDEX ix_user_period_summaries_id ON user_period_summaries (id);""")
    op.execute("""COMMENT ON TABLE user_period_summaries IS 'DB-03 I7 canonical period summaries (DAILY/WEEKLY/MONTHLY/YEARLY)';""")

    op.execute(
        """
CREATE TABLE physiological_measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    user_id INTEGER NOT NULL,
    device_id INTEGER NOT NULL,
    sensor_id INTEGER,
    measurement_type VARCHAR(32) NOT NULL,
    numeric_value DOUBLE PRECISION NOT NULL,
    unit VARCHAR(32) DEFAULT 'bpm' NOT NULL,
    measured_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    quality_state VARCHAR(32),
    idempotency_key VARCHAR(255) NOT NULL,
    source_sequence VARCHAR(128),
    ingestion_status VARCHAR(32) DEFAULT 'accepted' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_pm_measurement_type_vocab CHECK (measurement_type IN ('heart_rate')),
    CONSTRAINT uq_pm_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_pm_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_pm_device_id FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pm_sensor_id FOREIGN KEY (sensor_id) REFERENCES device_sensors(id) ON DELETE SET NULL
);
"""
    )
    op.execute(
        """CREATE INDEX ix_pm_user_measured_at ON physiological_measurements (user_id, measured_at DESC);"""
    )
    op.execute(
        """CREATE INDEX ix_pm_device_measured_at ON physiological_measurements (device_id, measured_at DESC);"""
    )
    op.execute("""CREATE INDEX ix_pm_idempotency_key ON physiological_measurements (idempotency_key);""")
    op.execute("""CREATE INDEX ix_physiological_measurements_id ON physiological_measurements (id);""")
    op.execute(
        """COMMENT ON TABLE physiological_measurements IS 'DB-03 canonical scalar physiological measurements; device_events remains lifecycle';"""
    )
    op.execute("""COMMENT ON COLUMN physiological_measurements.measured_at IS 'Time physiological measurement occurred';""")
    op.execute("""COMMENT ON COLUMN physiological_measurements.received_at IS 'Time backend received measurement';""")

    op.execute(
        """
CREATE TABLE physiological_baselines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    user_id INTEGER NOT NULL,
    measurement_type VARCHAR(32) NOT NULL,
    window_start TIMESTAMPTZ NOT NULL,
    window_end TIMESTAMPTZ NOT NULL,
    coverage DOUBLE PRECISION,
    quality VARCHAR(32),
    baseline_version INTEGER DEFAULT 1 NOT NULL,
    derived_at TIMESTAMPTZ NOT NULL,
    source_range TEXT,
    baseline_value DOUBLE PRECISION,
    PRIMARY KEY (id),
    CONSTRAINT uq_pb_user_type_version_window UNIQUE (user_id, measurement_type, baseline_version, window_start),
    CONSTRAINT fk_pb_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
"""
    )
    op.execute("""CREATE INDEX ix_pb_user_id ON physiological_baselines (user_id);""")
    op.execute("""CREATE INDEX ix_physiological_baselines_id ON physiological_baselines (id);""")

    op.execute(
        """
CREATE TABLE derived_health_signals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    user_id INTEGER NOT NULL,
    signal_type VARCHAR(64) NOT NULL,
    severity_band VARCHAR(32),
    evidence_measurement_ids TEXT,
    policy_ref VARCHAR(128),
    detected_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(32) DEFAULT 'open' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_dhs_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
"""
    )
    op.execute("""CREATE INDEX ix_dhs_user_id ON derived_health_signals (user_id);""")
    op.execute("""CREATE INDEX ix_dhs_detected_at ON derived_health_signals (detected_at);""")
    op.execute("""CREATE INDEX ix_derived_health_signals_id ON derived_health_signals (id);""")
    op.execute("""COMMENT ON TABLE derived_health_signals IS 'DB-03 nondiagnostic derived signals; not a diagnosis authority';""")

    # --- EXTEND existing tables ---
    op.execute("""ALTER TABLE i5_raw_evidence ADD COLUMN IF NOT EXISTS storage_locator TEXT;""")
    op.execute("""ALTER TABLE i5_raw_evidence ADD COLUMN IF NOT EXISTS object_key TEXT;""")
    op.execute("""ALTER TABLE i5_raw_evidence ADD COLUMN IF NOT EXISTS durable_path TEXT;""")
    op.execute("""ALTER TABLE i5_raw_evidence ADD COLUMN IF NOT EXISTS byte_size BIGINT;""")
    op.execute("""ALTER TABLE i5_raw_evidence ADD COLUMN IF NOT EXISTS integrity_state VARCHAR(32);""")
    op.execute("""ALTER TABLE i5_raw_evidence ADD COLUMN IF NOT EXISTS recoverability_state VARCHAR(32);""")
    op.execute(
        """
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_ire_recoverability_state_vocab') THEN
    ALTER TABLE i5_raw_evidence
      ADD CONSTRAINT ck_ire_recoverability_state_vocab
      CHECK (recoverability_state IS NULL OR recoverability_state IN ('RECOVERABLE', 'ABSENCE_GOVERNED', 'UNKNOWN'));
  END IF;
END $$;
"""
    )

    op.execute("""ALTER TABLE user_memory_facts ADD COLUMN IF NOT EXISTS consent_id INTEGER;""")
    op.execute("""ALTER TABLE user_memory_facts ADD COLUMN IF NOT EXISTS sensitivity_class VARCHAR(32);""")
    op.execute("""ALTER TABLE user_memory_facts ADD COLUMN IF NOT EXISTS human_readable_value TEXT;""")
    op.execute("""ALTER TABLE user_memory_facts ADD COLUMN IF NOT EXISTS provenance_class VARCHAR(32);""")
    op.execute("""ALTER TABLE user_memory_facts ADD COLUMN IF NOT EXISTS soft_invalidated_at TIMESTAMPTZ;""")
    op.execute("""ALTER TABLE user_memory_facts ADD COLUMN IF NOT EXISTS invalidation_reason TEXT;""")
    op.execute(
        """
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_umf_provenance_class_vocab') THEN
    ALTER TABLE user_memory_facts
      ADD CONSTRAINT ck_umf_provenance_class_vocab
      CHECK (provenance_class IS NULL OR provenance_class IN (
        'USER_STATED', 'USER_CONFIRMED', 'CONVERSATION_DERIVED', 'DEVICE_DERIVED',
        'SYSTEM_DERIVED', 'CAREGIVER_PROVIDED', 'CLINICIAN_PROVIDED'
      ));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_umf_consent_id') THEN
    ALTER TABLE user_memory_facts
      ADD CONSTRAINT fk_umf_consent_id
      FOREIGN KEY (consent_id) REFERENCES user_consents(id) ON DELETE SET NULL;
  END IF;
END $$;
"""
    )
    op.execute("""CREATE INDEX IF NOT EXISTS ix_umf_consent_id ON user_memory_facts (consent_id);""")

    op.execute("""ALTER TABLE notifications ADD COLUMN IF NOT EXISTS care_episode_id INTEGER;""")
    op.execute("""ALTER TABLE notifications ADD COLUMN IF NOT EXISTS queued_at TIMESTAMPTZ;""")
    op.execute("""ALTER TABLE notifications ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ;""")
    op.execute("""ALTER TABLE notifications ADD COLUMN IF NOT EXISTS opened_at TIMESTAMPTZ;""")
    op.execute("""ALTER TABLE notifications ADD COLUMN IF NOT EXISTS decision_at TIMESTAMPTZ;""")
    op.execute(
        """
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notifications_care_episode_id') THEN
    ALTER TABLE notifications
      ADD CONSTRAINT fk_notifications_care_episode_id
      FOREIGN KEY (care_episode_id) REFERENCES care_episodes(id) ON DELETE SET NULL;
  END IF;
END $$;
"""
    )
    op.execute("""CREATE INDEX IF NOT EXISTS ix_notifications_care_episode_id ON notifications (care_episode_id);""")

    op.execute("""ALTER TABLE emergency_escalation_records ADD COLUMN IF NOT EXISTS care_episode_id INTEGER;""")
    op.execute("""ALTER TABLE emergency_escalation_records ADD COLUMN IF NOT EXISTS step_no INTEGER;""")
    op.execute("""ALTER TABLE emergency_escalation_records ADD COLUMN IF NOT EXISTS from_recipient VARCHAR(128);""")
    op.execute("""ALTER TABLE emergency_escalation_records ADD COLUMN IF NOT EXISTS to_recipient VARCHAR(128);""")
    op.execute("""ALTER TABLE emergency_escalation_records ADD COLUMN IF NOT EXISTS consent_evidence_id INTEGER;""")
    op.execute("""ALTER TABLE emergency_escalation_records ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMPTZ;""")
    op.execute("""ALTER TABLE emergency_escalation_records ADD COLUMN IF NOT EXISTS executed_at TIMESTAMPTZ;""")
    op.execute("""ALTER TABLE emergency_escalation_records ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;""")
    op.execute(
        """
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_eer_care_episode_id') THEN
    ALTER TABLE emergency_escalation_records
      ADD CONSTRAINT fk_eer_care_episode_id
      FOREIGN KEY (care_episode_id) REFERENCES care_episodes(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_eer_consent_evidence_id') THEN
    ALTER TABLE emergency_escalation_records
      ADD CONSTRAINT fk_eer_consent_evidence_id
      FOREIGN KEY (consent_evidence_id) REFERENCES user_consents(id) ON DELETE SET NULL;
  END IF;
END $$;
"""
    )
    op.execute("""CREATE INDEX IF NOT EXISTS ix_eer_care_episode_id ON emergency_escalation_records (care_episode_id);""")
    op.execute("""CREATE INDEX IF NOT EXISTS ix_eer_consent_evidence_id ON emergency_escalation_records (consent_evidence_id);""")

    op.execute("""ALTER TABLE knowledge_chunk_embeddings ADD COLUMN IF NOT EXISTS knowledge_unit_id INTEGER;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings ADD COLUMN IF NOT EXISTS immutable_version_id VARCHAR(64);""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings ADD COLUMN IF NOT EXISTS source_profile_id INTEGER;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings ADD COLUMN IF NOT EXISTS raw_evidence_id INTEGER;""")
    op.execute(
        """ALTER TABLE knowledge_chunk_embeddings ADD COLUMN IF NOT EXISTS index_generation INTEGER DEFAULT 1 NOT NULL;"""
    )
    op.execute(
        """ALTER TABLE knowledge_chunk_embeddings ADD COLUMN IF NOT EXISTS backend_kind VARCHAR(32) DEFAULT 'JSON_INLINE' NOT NULL;"""
    )
    op.execute("""ALTER TABLE knowledge_chunk_embeddings ADD COLUMN IF NOT EXISTS runtime_eligibility_snapshot TEXT;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings ADD COLUMN IF NOT EXISTS retracted_at TIMESTAMPTZ;""")
    op.execute(
        """
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_kce_backend_kind_vocab') THEN
    ALTER TABLE knowledge_chunk_embeddings
      ADD CONSTRAINT ck_kce_backend_kind_vocab
      CHECK (backend_kind IS NULL OR backend_kind IN ('JSON_INLINE', 'EXTERNAL_VECTOR_DEFERRED'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_kce_knowledge_unit_id') THEN
    ALTER TABLE knowledge_chunk_embeddings
      ADD CONSTRAINT fk_kce_knowledge_unit_id
      FOREIGN KEY (knowledge_unit_id) REFERENCES knowledge_units(id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_kce_source_profile_id') THEN
    ALTER TABLE knowledge_chunk_embeddings
      ADD CONSTRAINT fk_kce_source_profile_id
      FOREIGN KEY (source_profile_id) REFERENCES governed_source_profiles(id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_kce_raw_evidence_id') THEN
    ALTER TABLE knowledge_chunk_embeddings
      ADD CONSTRAINT fk_kce_raw_evidence_id
      FOREIGN KEY (raw_evidence_id) REFERENCES i5_raw_evidence(id) ON DELETE SET NULL;
  END IF;
END $$;
"""
    )
    op.execute("""CREATE INDEX IF NOT EXISTS ix_kce_knowledge_unit_id ON knowledge_chunk_embeddings (knowledge_unit_id);""")
    op.execute("""CREATE INDEX IF NOT EXISTS ix_kce_source_profile_id ON knowledge_chunk_embeddings (source_profile_id);""")
    op.execute("""CREATE INDEX IF NOT EXISTS ix_kce_raw_evidence_id ON knowledge_chunk_embeddings (raw_evidence_id);""")


def downgrade() -> None:
    op.execute("""ALTER TABLE knowledge_chunk_embeddings DROP CONSTRAINT IF EXISTS fk_kce_raw_evidence_id;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings DROP CONSTRAINT IF EXISTS fk_kce_source_profile_id;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings DROP CONSTRAINT IF EXISTS fk_kce_knowledge_unit_id;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings DROP CONSTRAINT IF EXISTS ck_kce_backend_kind_vocab;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings DROP COLUMN IF EXISTS retracted_at;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings DROP COLUMN IF EXISTS runtime_eligibility_snapshot;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings DROP COLUMN IF EXISTS backend_kind;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings DROP COLUMN IF EXISTS index_generation;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings DROP COLUMN IF EXISTS raw_evidence_id;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings DROP COLUMN IF EXISTS source_profile_id;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings DROP COLUMN IF EXISTS immutable_version_id;""")
    op.execute("""ALTER TABLE knowledge_chunk_embeddings DROP COLUMN IF EXISTS knowledge_unit_id;""")

    op.execute("""ALTER TABLE emergency_escalation_records DROP CONSTRAINT IF EXISTS fk_eer_consent_evidence_id;""")
    op.execute("""ALTER TABLE emergency_escalation_records DROP CONSTRAINT IF EXISTS fk_eer_care_episode_id;""")
    op.execute("""ALTER TABLE emergency_escalation_records DROP COLUMN IF EXISTS cancelled_at;""")
    op.execute("""ALTER TABLE emergency_escalation_records DROP COLUMN IF EXISTS executed_at;""")
    op.execute("""ALTER TABLE emergency_escalation_records DROP COLUMN IF EXISTS scheduled_at;""")
    op.execute("""ALTER TABLE emergency_escalation_records DROP COLUMN IF EXISTS consent_evidence_id;""")
    op.execute("""ALTER TABLE emergency_escalation_records DROP COLUMN IF EXISTS to_recipient;""")
    op.execute("""ALTER TABLE emergency_escalation_records DROP COLUMN IF EXISTS from_recipient;""")
    op.execute("""ALTER TABLE emergency_escalation_records DROP COLUMN IF EXISTS step_no;""")
    op.execute("""ALTER TABLE emergency_escalation_records DROP COLUMN IF EXISTS care_episode_id;""")

    op.execute("""ALTER TABLE notifications DROP CONSTRAINT IF EXISTS fk_notifications_care_episode_id;""")
    op.execute("""ALTER TABLE notifications DROP COLUMN IF EXISTS decision_at;""")
    op.execute("""ALTER TABLE notifications DROP COLUMN IF EXISTS opened_at;""")
    op.execute("""ALTER TABLE notifications DROP COLUMN IF EXISTS delivered_at;""")
    op.execute("""ALTER TABLE notifications DROP COLUMN IF EXISTS queued_at;""")
    op.execute("""ALTER TABLE notifications DROP COLUMN IF EXISTS care_episode_id;""")

    op.execute("""ALTER TABLE user_memory_facts DROP CONSTRAINT IF EXISTS fk_umf_consent_id;""")
    op.execute("""ALTER TABLE user_memory_facts DROP CONSTRAINT IF EXISTS ck_umf_provenance_class_vocab;""")
    op.execute("""ALTER TABLE user_memory_facts DROP COLUMN IF EXISTS invalidation_reason;""")
    op.execute("""ALTER TABLE user_memory_facts DROP COLUMN IF EXISTS soft_invalidated_at;""")
    op.execute("""ALTER TABLE user_memory_facts DROP COLUMN IF EXISTS provenance_class;""")
    op.execute("""ALTER TABLE user_memory_facts DROP COLUMN IF EXISTS human_readable_value;""")
    op.execute("""ALTER TABLE user_memory_facts DROP COLUMN IF EXISTS sensitivity_class;""")
    op.execute("""ALTER TABLE user_memory_facts DROP COLUMN IF EXISTS consent_id;""")

    op.execute("""ALTER TABLE i5_raw_evidence DROP CONSTRAINT IF EXISTS ck_ire_recoverability_state_vocab;""")
    op.execute("""ALTER TABLE i5_raw_evidence DROP COLUMN IF EXISTS recoverability_state;""")
    op.execute("""ALTER TABLE i5_raw_evidence DROP COLUMN IF EXISTS integrity_state;""")
    op.execute("""ALTER TABLE i5_raw_evidence DROP COLUMN IF EXISTS byte_size;""")
    op.execute("""ALTER TABLE i5_raw_evidence DROP COLUMN IF EXISTS durable_path;""")
    op.execute("""ALTER TABLE i5_raw_evidence DROP COLUMN IF EXISTS object_key;""")
    op.execute("""ALTER TABLE i5_raw_evidence DROP COLUMN IF EXISTS storage_locator;""")

    op.drop_table("derived_health_signals")
    op.drop_table("physiological_baselines")
    op.drop_table("physiological_measurements")
    op.drop_table("user_period_summaries")
    op.drop_table("care_episode_links")
    op.drop_table("care_episodes")
    op.drop_table("care_response_policies")
    op.drop_table("user_consent_scopes")
    op.drop_table("user_consents")
