"""DB-03 Wave 2 — backfill / duplicate-authority consolidation

Revision ID: 059_db03_w2_backfill_consolidation
Revises: 058_db03_w1_additive_foundations

MIG-DB03-W2 — §270.R
Logically reversible (source tables retained). Runs deterministic SQL + Python helpers.
No DROP of legacy authorities.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "059_db03_w2_backfill_consolidation"
down_revision: Union[str, None] = "058_db03_w1_additive_foundations"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Migration conflict / audit ledger for unexplained mappings (no PHI payloads).
    op.execute(
        """
CREATE TABLE IF NOT EXISTS db03_migration_conflicts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    wave VARCHAR(32) NOT NULL,
    source_table VARCHAR(128) NOT NULL,
    source_id VARCHAR(128),
    target_table VARCHAR(128) NOT NULL,
    conflict_kind VARCHAR(64) NOT NULL,
    detail TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id)
);
"""
    )

    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    try:
        from backend.app.services.db03.memory_fact_merge import merge_legacy_facts_into_user_memory_facts
        from backend.app.services.db03.period_summary_backfill import backfill_daily_memory_summaries
        from backend.app.services.db03.health_data_backfill import (
            backfill_health_data_to_physiological_measurements,
        )

        mem = merge_legacy_facts_into_user_memory_facts(session)
        for detail in mem.details:
            session.execute(
                sa.text(
                    """
                    INSERT INTO db03_migration_conflicts
                      (wave, source_table, source_id, target_table, conflict_kind, detail)
                    VALUES
                      ('W2', 'memory_fact_stacks', NULL, 'user_memory_facts', 'unmap', :detail)
                    """
                ),
                {"detail": detail[:2000]},
            )

        per = backfill_daily_memory_summaries(session)
        if per.unmapped_rows:
            session.execute(
                sa.text(
                    """
                    INSERT INTO db03_migration_conflicts
                      (wave, source_table, source_id, target_table, conflict_kind, detail)
                    VALUES
                      ('W2', 'daily_memory_summaries', NULL, 'user_period_summaries', 'unmap', :detail)
                    """
                ),
                {"detail": f"unmapped={per.unmapped_rows}"},
            )

        hr = backfill_health_data_to_physiological_measurements(session)
        if hr.unmapped_rows:
            session.execute(
                sa.text(
                    """
                    INSERT INTO db03_migration_conflicts
                      (wave, source_table, source_id, target_table, conflict_kind, detail)
                    VALUES
                      ('W2', 'health_data', NULL, 'physiological_measurements', 'unmap', :detail)
                    """
                ),
                {"detail": f"unmapped={hr.unmapped_rows} skipped_no_device={hr.skipped_no_device}"},
            )

        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()

    # Mark knowledge_sources crawler authority deprecated (bridge retained).
    op.execute(
        """
COMMENT ON TABLE knowledge_sources IS
'LEGACY — crawler authority DEPRECATED in favor of governed_source_profiles (DB-03/§270); bridge retained until Wave5';
"""
    )
    op.execute(
        """
COMMENT ON TABLE health_data IS
'LEGACY DEPRECATE — canonical HR authority is physiological_measurements (DB-03/§270); retained for rollback';
"""
    )
    op.execute(
        """
COMMENT ON TABLE daily_memory_summaries IS
'LEGACY REPLACE — canonical I7 authority is user_period_summaries (DB-03/§270); retained for rollback';
"""
    )


def downgrade() -> None:
    # Logical reverse: leave migrated target rows (forward-fix preferred for backfills).
    # Drop only the conflict ledger created by this revision.
    op.execute("""DROP TABLE IF EXISTS db03_migration_conflicts;""")
