"""DB-03 Wave 4+5+6 — scale rollups, inspectability, role prep markers

Revision ID: 060_db03_w4_w6_scale_inspect_roles
Revises: 059_db03_w2_backfill_consolidation

MIG-DB03-W4/W6 — §270.L/P/Q
- Optional physiological_measurement_rollups
- Inspection views (no PHI payloads)
- Partitioning NOT activated (trigger ANY documented via COMMENT)
- Role SQL lives in backend/ops/db03/ (NOT applied to Production here)
"""
from typing import Sequence, Union

from alembic import op


revision: str = "060_db03_w4_w6_scale_inspect_roles"
down_revision: Union[str, None] = "059_db03_w2_backfill_consolidation"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE physiological_measurement_rollups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    user_id INTEGER NOT NULL,
    measurement_type VARCHAR(32) NOT NULL,
    bucket_kind VARCHAR(16) NOT NULL,
    bucket_start TIMESTAMPTZ NOT NULL,
    bucket_end TIMESTAMPTZ NOT NULL,
    sample_count INTEGER DEFAULT 0 NOT NULL,
    avg_value DOUBLE PRECISION,
    min_value DOUBLE PRECISION,
    max_value DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_pmr_user_type_bucket UNIQUE (user_id, measurement_type, bucket_start, bucket_kind),
    CONSTRAINT fk_pmr_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
"""
    )
    op.execute("""CREATE INDEX ix_pmr_user_bucket ON physiological_measurement_rollups (user_id, bucket_start);""")
    op.execute(
        """
COMMENT ON TABLE physiological_measurements IS
'DB-03 canonical HR measurements. PARTITIONING DEFERRED. Triggers ANY: active_devices>=1000 OR rows>=50M OR p95 SLO breach. Key when activated: RANGE(measured_at) monthly. No TimescaleDB.';
"""
    )

    # Inspection views — aggregates / status only; no phone/body/payload.
    op.execute(
        """
CREATE OR REPLACE VIEW vw_user_memory_overview AS
SELECT
  user_id,
  COUNT(*) AS fact_count,
  COUNT(*) FILTER (WHERE fact_status = 'active') AS active_count,
  COUNT(*) FILTER (WHERE soft_invalidated_at IS NOT NULL) AS soft_invalidated_count,
  COUNT(DISTINCT domain) AS domain_count
FROM user_memory_facts
GROUP BY user_id;
"""
    )
    op.execute(
        """
CREATE OR REPLACE VIEW vw_user_heart_rate_daily AS
SELECT
  user_id,
  (measured_at AT TIME ZONE 'UTC')::date AS day_utc,
  COUNT(*) AS sample_count,
  AVG(numeric_value) AS avg_bpm,
  MIN(numeric_value) AS min_bpm,
  MAX(numeric_value) AS max_bpm
FROM physiological_measurements
WHERE measurement_type = 'heart_rate'
GROUP BY user_id, (measured_at AT TIME ZONE 'UTC')::date;
"""
    )
    op.execute(
        """
CREATE OR REPLACE VIEW vw_notification_reaction_timeline AS
SELECT
  n.id AS notification_id,
  n.user_id,
  n.care_episode_id,
  n.queued_at,
  n.sent_at,
  n.delivered_at,
  n.opened_at,
  n.decision_at,
  f.action AS reaction_action,
  f.created_at AS reaction_at
FROM notifications n
LEFT JOIN notification_feedback f ON f.notification_id = n.id;
"""
    )
    op.execute(
        """
CREATE OR REPLACE VIEW vw_open_care_episodes AS
SELECT
  id,
  user_id,
  origin_type,
  category,
  policy_id,
  policy_version,
  opened_at,
  current_state,
  ack_due_at,
  escalation_due_at,
  expired_at
FROM care_episodes
WHERE resolved_at IS NULL AND current_state <> 'resolved';
"""
    )
    op.execute(
        """
CREATE OR REPLACE VIEW vw_knowledge_runtime_status AS
SELECT
  runtime_eligibility,
  COUNT(*) AS unit_count
FROM knowledge_units
GROUP BY runtime_eligibility;
"""
    )
    op.execute(
        """
CREATE OR REPLACE VIEW vw_crawler_latest_runs AS
SELECT
  id,
  run_type,
  status,
  created_at
FROM weekly_knowledge_runs;
"""
    )

    # Deprecation markers (Wave 5 — no DROP).
    op.execute(
        """
COMMENT ON TABLE user_facts IS
'LEGACY MERGE — writes should prefer user_memory_facts after DB-03 cutover; retained for rollback';
"""
    )
    op.execute(
        """
COMMENT ON TABLE kc_user_facts IS
'LEGACY MERGE — writes should prefer user_memory_facts after DB-03 cutover; retained for rollback';
"""
    )
    op.execute(
        """
COMMENT ON TABLE user_profile_facts IS
'LEGACY MERGE — writes should prefer user_memory_facts after DB-03 cutover; retained for rollback';
"""
    )


def downgrade() -> None:
    op.execute("""DROP VIEW IF EXISTS vw_crawler_latest_runs;""")
    op.execute("""DROP VIEW IF EXISTS vw_knowledge_runtime_status;""")
    op.execute("""DROP VIEW IF EXISTS vw_open_care_episodes;""")
    op.execute("""DROP VIEW IF EXISTS vw_notification_reaction_timeline;""")
    op.execute("""DROP VIEW IF EXISTS vw_user_heart_rate_daily;""")
    op.execute("""DROP VIEW IF EXISTS vw_user_memory_overview;""")
    op.drop_table("physiological_measurement_rollups")
