"""I5-KNOW-01 — Trusted Source Registry + Rights + Reference Books (additive).

Revision ID: 062_i5_know01_source_registry_rights
Revises: 061_scis01_pgvector_kce_foundation

NO Production apply in this Gate. Rehearsal/CI only.
Does NOT create KNOW-02 scientific_artifacts / study tables.
Does NOT mutate coverage_manifest Diabetes D20.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "062_i5_know01_source_registry_rights"
down_revision: Union[str, None] = "061_scis01_pgvector_kce_foundation"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE i5_source_registry_extensions (
    source_profile_id INTEGER PRIMARY KEY,
    source_universe VARCHAR(32) NOT NULL,
    publisher_family VARCHAR(128),
    authority_class VARCHAR(64) NOT NULL,
    country VARCHAR(64),
    jurisdiction VARCHAR(64),
    languages VARCHAR(128),
    knowledge_domains TEXT,
    specialty_domains TEXT,
    canonical_home TEXT,
    canonical_discovery_endpoint TEXT,
    api_endpoint TEXT,
    rss_endpoint TEXT,
    atom_endpoint TEXT,
    sitemap_endpoint TEXT,
    oai_endpoint TEXT,
    bulk_endpoint TEXT,
    supported_formats TEXT,
    access_right VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    automation_right VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    tdm_right VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    transform_right VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    retain_raw_right VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    retain_derived_right VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    redistribution_right VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    attribution_requirement TEXT,
    robots_state VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    rate_limit_policy TEXT,
    freshness_policy TEXT,
    processing_permission_mode VARCHAR(64) NOT NULL DEFAULT 'FULLTEXT_AUTOMATION_BLOCKED',
    review_stage VARCHAR(32) NOT NULL DEFAULT 'NONE',
    credential_authority BOOLEAN NOT NULL DEFAULT FALSE,
    current_rights_review TEXT,
    rights_reviewed_at TIMESTAMPTZ,
    last_authority_verification TIMESTAMPTZ,
    last_successful_acquisition TIMESTAMPTZ,
    last_observed_change TIMESTAMPTZ,
    registry_status VARCHAR(32),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_sre_source_profile
      FOREIGN KEY (source_profile_id) REFERENCES governed_source_profiles(id) ON DELETE CASCADE,
    CONSTRAINT ck_sre_universe CHECK (source_universe IN (
      'GLOBAL_KNOWLEDGE','IRAN_LOCAL_DIRECTORY','REFERENCE_BOOK','MIXED_EXPLICIT')),
    CONSTRAINT ck_sre_access CHECK (access_right IN ('ALLOWED','DENIED','CONDITIONAL','UNKNOWN','REVIEW_REQUIRED')),
    CONSTRAINT ck_sre_automation CHECK (automation_right IN ('ALLOWED','DENIED','CONDITIONAL','UNKNOWN','REVIEW_REQUIRED')),
    CONSTRAINT ck_sre_tdm CHECK (tdm_right IN ('ALLOWED','DENIED','CONDITIONAL','UNKNOWN','REVIEW_REQUIRED')),
    CONSTRAINT ck_sre_transform CHECK (transform_right IN ('ALLOWED','DENIED','CONDITIONAL','UNKNOWN','REVIEW_REQUIRED')),
    CONSTRAINT ck_sre_retain_raw CHECK (retain_raw_right IN ('ALLOWED','DENIED','CONDITIONAL','UNKNOWN','REVIEW_REQUIRED')),
    CONSTRAINT ck_sre_retain_derived CHECK (retain_derived_right IN ('ALLOWED','DENIED','CONDITIONAL','UNKNOWN','REVIEW_REQUIRED')),
    CONSTRAINT ck_sre_redistrib CHECK (redistribution_right IN ('ALLOWED','DENIED','CONDITIONAL','UNKNOWN','REVIEW_REQUIRED')),
    CONSTRAINT ck_sre_robots CHECK (robots_state IN ('UNKNOWN','ALLOWED','DISALLOWED','CONDITIONAL','NOT_APPLICABLE')),
    CONSTRAINT ck_sre_proc_mode CHECK (processing_permission_mode IN (
      'FULL_PROCESS_AND_RETAIN','TRANSIENT_PROCESS_ONLY','DERIVED_KNOWLEDGE_ONLY',
      'METADATA_ABSTRACT_ONLY','FULLTEXT_AUTOMATION_BLOCKED','LICENSED_CONNECTOR_ONLY'))
);
"""
    )
    op.execute(
        "CREATE INDEX ix_sre_universe ON i5_source_registry_extensions (source_universe);"
    )
    op.execute(
        "CREATE INDEX ix_sre_authority ON i5_source_registry_extensions (authority_class);"
    )
    op.execute(
        "CREATE INDEX ix_sre_automation ON i5_source_registry_extensions (automation_right);"
    )

    op.execute(
        """
CREATE TABLE i5_source_registry_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_profile_id INTEGER NOT NULL,
    role VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_srr_source_profile
      FOREIGN KEY (source_profile_id) REFERENCES governed_source_profiles(id) ON DELETE CASCADE,
    CONSTRAINT uq_srr_profile_role UNIQUE (source_profile_id, role)
);
"""
    )
    op.execute(
        "CREATE INDEX ix_srr_role ON i5_source_registry_roles (role);"
    )

    op.execute(
        """
CREATE TABLE i5_source_p0_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_profile_id INTEGER NOT NULL,
    disease VARCHAR(32) NOT NULL,
    relevance VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_sp0_source_profile
      FOREIGN KEY (source_profile_id) REFERENCES governed_source_profiles(id) ON DELETE CASCADE,
    CONSTRAINT uq_sp0_profile_disease UNIQUE (source_profile_id, disease),
    CONSTRAINT ck_sp0_disease CHECK (disease IN ('ALS','MS','DIABETES')),
    CONSTRAINT ck_sp0_relevance CHECK (relevance IN ('PRIMARY','IMPORTANT','SUPPORTING','NOT_SPECIFIC'))
);
"""
    )
    op.execute("CREATE INDEX ix_sp0_disease ON i5_source_p0_tags (disease);")

    op.execute(
        """
CREATE TABLE i5_source_coverage_gaps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disease_or_domain VARCHAR(128) NOT NULL,
    knowledge_dimension VARCHAR(128) NOT NULL,
    evidence_class VARCHAR(64),
    status VARCHAR(64) NOT NULL,
    detail TEXT,
    knowledge_gap_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_scg_status CHECK (status IN (
      'COVERED','PARTIAL','SOURCE_DISCOVERY_REQUIRED','RIGHTS_REVIEW_REQUIRED',
      'AUTHORITY_GAP','STALE_SOURCE_SET','NO_AUTHORITATIVE_SOURCE_FOUND')),
    CONSTRAINT fk_scg_knowledge_gap
      FOREIGN KEY (knowledge_gap_id) REFERENCES knowledge_gaps(id) ON DELETE SET NULL
);
"""
    )
    op.execute(
        "CREATE INDEX ix_scg_disease_dim ON i5_source_coverage_gaps (disease_or_domain, knowledge_dimension);"
    )

    op.execute(
        """
CREATE TABLE i5_reference_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_key VARCHAR(256) NOT NULL,
    title VARCHAR(512) NOT NULL,
    publisher VARCHAR(256),
    publisher_source_profile_id INTEGER,
    authors_editors TEXT,
    isbn VARCHAR(32),
    specialty VARCHAR(128),
    disease_coverage TEXT,
    rights_class VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN_RIGHTS',
    medical_authority_note TEXT,
    automation_tdm_permission VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    fulltext_automation_permission VARCHAR(32) NOT NULL DEFAULT 'DENIED',
    retention_policy TEXT,
    canonical_access_route TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_irb_book_key UNIQUE (book_key),
    CONSTRAINT fk_irb_publisher_gsp
      FOREIGN KEY (publisher_source_profile_id) REFERENCES governed_source_profiles(id) ON DELETE SET NULL,
    CONSTRAINT ck_irb_rights CHECK (rights_class IN (
      'OPEN_AUTOMATION_ALLOWED','PUBLIC_DOMAIN','OPEN_LICENSE_RESTRICTED','LICENSED',
      'METADATA_ONLY','FULLTEXT_TDM_PROHIBITED','UNKNOWN_RIGHTS')),
    CONSTRAINT ck_irb_tdm CHECK (automation_tdm_permission IN ('ALLOWED','DENIED','CONDITIONAL','UNKNOWN','REVIEW_REQUIRED')),
    CONSTRAINT ck_irb_fulltext CHECK (fulltext_automation_permission IN ('ALLOWED','DENIED','CONDITIONAL','UNKNOWN','REVIEW_REQUIRED'))
);
"""
    )

    op.execute(
        """
CREATE TABLE i5_reference_book_editions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    edition_label VARCHAR(128) NOT NULL,
    volume VARCHAR(64),
    publication_year INTEGER,
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    superseded_by_edition_id BIGINT,
    access_route TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_irbe_book FOREIGN KEY (book_id) REFERENCES i5_reference_books(id) ON DELETE CASCADE,
    CONSTRAINT uq_irbe_book_edition UNIQUE (book_id, edition_label)
);
"""
    )
    op.execute(
        """
COMMENT ON TABLE i5_source_registry_extensions IS
'I5-KNOW-01 Trusted Source Registry overlay. Listing != authorization. Iran directory != clinical KU.';
"""
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS i5_reference_book_editions")
    op.execute("DROP TABLE IF EXISTS i5_reference_books")
    op.execute("DROP TABLE IF EXISTS i5_source_coverage_gaps")
    op.execute("DROP TABLE IF EXISTS i5_source_p0_tags")
    op.execute("DROP TABLE IF EXISTS i5_source_registry_roles")
    op.execute("DROP TABLE IF EXISTS i5_source_registry_extensions")
