"""I5-KNOW-02 — Scientific artifacts, multi-evidence, claims, universal taxonomy.

Revision ID: 063_i5_know02_artifacts_claims_taxonomy
Revises: 062_i5_know01_source_registry_rights

Additive only. NO Production apply. Does NOT create KNOW-03 study/rec/trial tables.
Does NOT create user_clinical_feature_index / user_evidence_matches.
"""

from typing import Sequence, Union

from alembic import op

revision: str = "063_i5_know02_artifacts_claims_taxonomy"
down_revision: Union[str, None] = "062_i5_know01_source_registry_rights"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE i5_terminology_releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terminology_system VARCHAR(32) NOT NULL,
    release_version VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    official_source_note TEXT,
    rights_note TEXT,
    valid_from TIMESTAMPTZ,
    valid_to TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_term_rel_system_version UNIQUE (terminology_system, release_version),
    CONSTRAINT ck_term_rel_system CHECK (terminology_system IN (
      'ICD11','MESH','RXNORM','LOINC','UMLS','SNOMED_CT','ICF','ICHI','SEDI_ROOT','OTHER'))
);
"""
    )

    op.execute(
        """
CREATE TABLE i5_knowledge_dimensions (
    code VARCHAR(64) PRIMARY KEY,
    label VARCHAR(256) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
"""
    )

    op.execute(
        """
CREATE TABLE i5_clinical_concepts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concept_key VARCHAR(256) NOT NULL,
    preferred_name VARCHAR(512) NOT NULL,
    normalized_name VARCHAR(512) NOT NULL,
    concept_type VARCHAR(64) NOT NULL,
    root_category VARCHAR(64),
    parent_concept_id BIGINT,
    rare_disease_flag BOOLEAN,
    genetic_condition_flag BOOLEAN,
    communicable_flag BOOLEAN,
    chronic_flag BOOLEAN,
    pediatric_relevance BOOLEAN,
    adult_relevance BOOLEAN,
    sex_specific_relevance VARCHAR(32),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    valid_from TIMESTAMPTZ,
    valid_to TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_cc_concept_key UNIQUE (concept_key),
    CONSTRAINT fk_cc_parent FOREIGN KEY (parent_concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE SET NULL,
    CONSTRAINT ck_cc_type CHECK (concept_type IN (
      'DISEASE','SUBTYPE','PHENOTYPE','SYMPTOM','SIGN','BIOMARKER','GENE','VARIANT',
      'DRUG','INTERVENTION','PROCEDURE','DEVICE','LAB_CLASS','IMAGING_FINDING',
      'OUTCOME','COMPLICATION','RISK_FACTOR','ADVERSE_EVENT','CONTRAINDICATION',
      'HEALTHY_POPULATION','DISEASE_FAMILY','OTHER'))
);
"""
    )
    op.execute("CREATE INDEX ix_cc_root_category ON i5_clinical_concepts (root_category);")
    op.execute("CREATE INDEX ix_cc_parent ON i5_clinical_concepts (parent_concept_id);")
    op.execute("CREATE INDEX ix_cc_type ON i5_clinical_concepts (concept_type);")

    op.execute(
        """
CREATE TABLE i5_clinical_concept_labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concept_id BIGINT NOT NULL,
    language VARCHAR(16) NOT NULL,
    label_kind VARCHAR(32) NOT NULL,
    label_text VARCHAR(512) NOT NULL,
    provenance_note TEXT,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_ccl_concept FOREIGN KEY (concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE CASCADE,
    CONSTRAINT ck_ccl_kind CHECK (label_kind IN (
      'PREFERRED','SYNONYM','ABBREVIATION','COMMON_NAME','LEGACY','PATIENT_LANGUAGE'))
);
"""
    )
    op.execute("CREATE INDEX ix_ccl_concept ON i5_clinical_concept_labels (concept_id);")

    op.execute(
        """
CREATE TABLE i5_clinical_concept_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concept_id BIGINT NOT NULL,
    terminology_system VARCHAR(32) NOT NULL,
    external_code VARCHAR(128) NOT NULL,
    release_version VARCHAR(64),
    mapping_status VARCHAR(32) NOT NULL DEFAULT 'PROVISIONAL',
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    valid_from TIMESTAMPTZ,
    valid_to TIMESTAMPTZ,
    provenance_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_ccm_concept FOREIGN KEY (concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE CASCADE,
    CONSTRAINT uq_ccm_system_code_release UNIQUE (terminology_system, external_code, release_version),
    CONSTRAINT ck_ccm_system CHECK (terminology_system IN (
      'ICD11','MESH','RXNORM','LOINC','UMLS','SNOMED_CT','ICF','ICHI','SEDI_ROOT','OTHER'))
);
"""
    )
    op.execute("CREATE INDEX ix_ccm_concept ON i5_clinical_concept_mappings (concept_id);")

    op.execute(
        """
CREATE TABLE i5_sedi_priority_overlays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concept_id BIGINT NOT NULL,
    priority_class VARCHAR(32) NOT NULL,
    track_key VARCHAR(64),
    rationale TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_spo_concept FOREIGN KEY (concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE CASCADE,
    CONSTRAINT uq_spo_concept_track UNIQUE (concept_id, track_key),
    CONSTRAINT ck_spo_priority CHECK (priority_class IN (
      'P0_CRITICAL','P0_HIGH','P1','P2','STANDARD'))
);
"""
    )

    op.execute(
        """
CREATE TABLE i5_scientific_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_key VARCHAR(256) NOT NULL,
    artifact_type VARCHAR(64) NOT NULL,
    title TEXT,
    publisher_family VARCHAR(256),
    source_profile_id INTEGER,
    doi VARCHAR(256),
    pmid VARCHAR(64),
    pmcid VARCHAR(64),
    isbn VARCHAR(32),
    nct_id VARCHAR(64),
    guideline_id VARCHAR(128),
    publisher_identifier VARCHAR(256),
    canonical_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_sa_artifact_key UNIQUE (artifact_key),
    CONSTRAINT fk_sa_source_profile FOREIGN KEY (source_profile_id)
      REFERENCES governed_source_profiles(id) ON DELETE SET NULL,
    CONSTRAINT ck_sa_type CHECK (artifact_type IN (
      'ARTICLE','SYSTEMATIC_REVIEW','META_ANALYSIS','GUIDELINE','CONSENSUS_STATEMENT',
      'RCT','OBSERVATIONAL_STUDY','CASE_SERIES','CASE_REPORT','BOOK','BOOK_CHAPTER',
      'REGULATORY_DOCUMENT','DRUG_LABEL','CLINICAL_TRIAL_RECORD','DATASET','OTHER'))
);
"""
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_sa_doi_notnull ON i5_scientific_artifacts (doi) WHERE doi IS NOT NULL;"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_sa_pmid_notnull ON i5_scientific_artifacts (pmid) WHERE pmid IS NOT NULL;"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_sa_nct_notnull ON i5_scientific_artifacts (nct_id) WHERE nct_id IS NOT NULL;"
    )

    op.execute(
        """
CREATE TABLE i5_scientific_artifact_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id BIGINT NOT NULL,
    version_label VARCHAR(128) NOT NULL,
    version_state VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED',
    published_at TIMESTAMPTZ,
    content_hash VARCHAR(64),
    title_at_version TEXT,
    abstract_or_summary TEXT,
    supersedes_version_id BIGINT,
    raw_evidence_id INTEGER,
    locator TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_sav_artifact FOREIGN KEY (artifact_id)
      REFERENCES i5_scientific_artifacts(id) ON DELETE CASCADE,
    CONSTRAINT uq_sav_artifact_version UNIQUE (artifact_id, version_label),
    CONSTRAINT fk_sav_raw_evidence FOREIGN KEY (raw_evidence_id)
      REFERENCES i5_raw_evidence(id) ON DELETE SET NULL,
    CONSTRAINT ck_sav_state CHECK (version_state IN (
      'PUBLISHED','UPDATED','CORRECTED','SUPERSEDED','RETRACTED',
      'EXPRESSION_OF_CONCERN','WITHDRAWN')),
    CONSTRAINT ck_sav_hash CHECK (content_hash IS NULL OR content_hash ~ '^[0-9a-f]{64}$')
);
"""
    )
    op.execute("CREATE INDEX ix_sav_artifact ON i5_scientific_artifact_versions (artifact_id);")
    op.execute("CREATE INDEX ix_sav_state ON i5_scientific_artifact_versions (version_state);")

    op.execute(
        """
CREATE TABLE i5_knowledge_unit_evidence_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_unit_id INTEGER NOT NULL,
    artifact_version_id BIGINT NOT NULL,
    support_direction VARCHAR(32) NOT NULL,
    evidence_role VARCHAR(64),
    locator TEXT,
    directness VARCHAR(32),
    certainty VARCHAR(32),
    quality VARCHAR(32),
    support_score DOUBLE PRECISION,
    retrieved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_kuel_ku FOREIGN KEY (knowledge_unit_id)
      REFERENCES knowledge_units(id) ON DELETE CASCADE,
    CONSTRAINT fk_kuel_sav FOREIGN KEY (artifact_version_id)
      REFERENCES i5_scientific_artifact_versions(id) ON DELETE RESTRICT,
    CONSTRAINT uq_kuel_ku_sav_dir UNIQUE (knowledge_unit_id, artifact_version_id, support_direction),
    CONSTRAINT ck_kuel_direction CHECK (support_direction IN (
      'SUPPORTS','WEAKLY_SUPPORTS','NEUTRAL','CONTRADICTS','REFUTES','INCONCLUSIVE'))
);
"""
    )
    op.execute("CREATE INDEX ix_kuel_ku ON i5_knowledge_unit_evidence_links (knowledge_unit_id);")
    op.execute("CREATE INDEX ix_kuel_sav ON i5_knowledge_unit_evidence_links (artifact_version_id);")

    op.execute(
        """
CREATE TABLE i5_knowledge_claim_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_unit_id INTEGER NOT NULL,
    claim_class VARCHAR(64) NOT NULL,
    subject_concept_id BIGINT,
    predicate VARCHAR(256),
    object_concept_id BIGINT,
    population_context TEXT,
    intervention_text TEXT,
    comparator_text TEXT,
    outcome_text TEXT,
    effect_direction VARCHAR(64),
    recommendation_status VARCHAR(64),
    experimental_status VARCHAR(64),
    certainty_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_kcd_ku FOREIGN KEY (knowledge_unit_id)
      REFERENCES knowledge_units(id) ON DELETE CASCADE,
    CONSTRAINT uq_kcd_ku UNIQUE (knowledge_unit_id),
    CONSTRAINT fk_kcd_subject FOREIGN KEY (subject_concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE SET NULL,
    CONSTRAINT fk_kcd_object FOREIGN KEY (object_concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE SET NULL
);
"""
    )

    op.execute(
        """
CREATE TABLE i5_knowledge_unit_concepts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_unit_id INTEGER NOT NULL,
    concept_id BIGINT NOT NULL,
    relation_role VARCHAR(64) NOT NULL DEFAULT 'ABOUT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_kuc_ku FOREIGN KEY (knowledge_unit_id)
      REFERENCES knowledge_units(id) ON DELETE CASCADE,
    CONSTRAINT fk_kuc_concept FOREIGN KEY (concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE CASCADE,
    CONSTRAINT uq_kuc_ku_concept_role UNIQUE (knowledge_unit_id, concept_id, relation_role)
);
"""
    )
    op.execute("CREATE INDEX ix_kuc_concept ON i5_knowledge_unit_concepts (concept_id);")

    op.execute(
        """
CREATE TABLE i5_knowledge_unit_dimensions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_unit_id INTEGER NOT NULL,
    dimension_code VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_kud_ku FOREIGN KEY (knowledge_unit_id)
      REFERENCES knowledge_units(id) ON DELETE CASCADE,
    CONSTRAINT fk_kud_dim FOREIGN KEY (dimension_code)
      REFERENCES i5_knowledge_dimensions(code) ON DELETE RESTRICT,
    CONSTRAINT uq_kud_ku_dim UNIQUE (knowledge_unit_id, dimension_code)
);
"""
    )
    op.execute("CREATE INDEX ix_kud_dim ON i5_knowledge_unit_dimensions (dimension_code);")

    op.execute(
        """
CREATE TABLE i5_knowledge_coverage_cells (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concept_id BIGINT NOT NULL,
    dimension_code VARCHAR(64) NOT NULL,
    evidence_class VARCHAR(64),
    cell_state VARCHAR(32) NOT NULL,
    freshness_note TEXT,
    detail TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_kcc_concept FOREIGN KEY (concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE CASCADE,
    CONSTRAINT fk_kcc_dim FOREIGN KEY (dimension_code)
      REFERENCES i5_knowledge_dimensions(code) ON DELETE RESTRICT,
    CONSTRAINT uq_kcc_cell UNIQUE (concept_id, dimension_code, evidence_class),
    CONSTRAINT ck_kcc_state CHECK (cell_state IN (
      'COVERED_CURRENT','COVERED_STALE','PARTIAL','CONFLICTED','MISSING','NOT_APPLICABLE'))
);
"""
    )
    op.execute(
        "CREATE INDEX ix_kcc_concept_dim ON i5_knowledge_coverage_cells (concept_id, dimension_code);"
    )

    op.execute(
        """
COMMENT ON TABLE i5_clinical_concepts IS
'I5-KNOW-02 universal human health taxonomy backbone. ALS/MS/Diabetes are P0 overlays, not parallel schemas.';
"""
    )
    op.execute(
        """
COMMENT ON TABLE i5_scientific_artifacts IS
'I5-KNOW-02 scientific artifact identity. Versions are immutable in i5_scientific_artifact_versions.';
"""
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS i5_knowledge_coverage_cells")
    op.execute("DROP TABLE IF EXISTS i5_knowledge_unit_dimensions")
    op.execute("DROP TABLE IF EXISTS i5_knowledge_unit_concepts")
    op.execute("DROP TABLE IF EXISTS i5_knowledge_claim_details")
    op.execute("DROP TABLE IF EXISTS i5_knowledge_unit_evidence_links")
    op.execute("DROP TABLE IF EXISTS i5_scientific_artifact_versions")
    op.execute("DROP TABLE IF EXISTS i5_scientific_artifacts")
    op.execute("DROP TABLE IF EXISTS i5_sedi_priority_overlays")
    op.execute("DROP TABLE IF EXISTS i5_clinical_concept_mappings")
    op.execute("DROP TABLE IF EXISTS i5_clinical_concept_labels")
    op.execute("DROP TABLE IF EXISTS i5_clinical_concepts")
    op.execute("DROP TABLE IF EXISTS i5_knowledge_dimensions")
    op.execute("DROP TABLE IF EXISTS i5_terminology_releases")
