"""I5-KNOW-03 — W0 integrity hardening + structured studies/PICO/effects/recommendations.

Revision ID: 064_i5_know03_studies_effects_recs
Revises: 063_i5_know02_artifacts_claims_taxonomy

Additive + constraint hardening only. NO Production apply.
Does NOT create user_clinical_feature_index / user_evidence_matches / clinical_trials bulk CT.gov schema.
clinical_trials* deferred to KNOW-04 connectors (registry_identifier on studies covers identity).
"""

from typing import Sequence, Union

from alembic import op

revision: str = "064_i5_know03_studies_effects_recs"
down_revision: Union[str, None] = "063_i5_know02_artifacts_claims_taxonomy"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # W0 NF5/NF6 — relational / nullable uniqueness / supersession
    # Rationale: PostgreSQL UNIQUE treats NULL as distinct; use NULLS NOT DISTINCT (PG15+).
    # ------------------------------------------------------------------
    op.execute("ALTER TABLE i5_clinical_concept_mappings DROP CONSTRAINT IF EXISTS uq_ccm_system_code_release")
    op.execute(
        """
ALTER TABLE i5_clinical_concept_mappings
  ADD CONSTRAINT uq_ccm_system_code_release
  UNIQUE NULLS NOT DISTINCT (terminology_system, external_code, release_version)
"""
    )
    op.execute("ALTER TABLE i5_knowledge_coverage_cells DROP CONSTRAINT IF EXISTS uq_kcc_cell")
    op.execute(
        """
ALTER TABLE i5_knowledge_coverage_cells
  ADD CONSTRAINT uq_kcc_cell
  UNIQUE NULLS NOT DISTINCT (concept_id, dimension_code, evidence_class)
"""
    )
    op.execute("ALTER TABLE i5_sedi_priority_overlays DROP CONSTRAINT IF EXISTS uq_spo_concept_track")
    op.execute(
        """
ALTER TABLE i5_sedi_priority_overlays
  ADD CONSTRAINT uq_spo_concept_track
  UNIQUE NULLS NOT DISTINCT (concept_id, track_key)
"""
    )

    op.execute(
        """
ALTER TABLE i5_scientific_artifact_versions
  ADD CONSTRAINT ck_sav_no_self_supersede
  CHECK (supersedes_version_id IS NULL OR supersedes_version_id <> id)
"""
    )
    op.execute(
        """
ALTER TABLE i5_scientific_artifact_versions
  ADD CONSTRAINT fk_sav_supersedes
  FOREIGN KEY (supersedes_version_id)
  REFERENCES i5_scientific_artifact_versions(id)
  ON DELETE RESTRICT
"""
    )
    # Same-artifact supersession policy (default: VERSION_SUPERSESSION stays inside artifact)
    op.execute(
        """
CREATE OR REPLACE FUNCTION i5_sav_supersedes_same_artifact()
RETURNS TRIGGER AS $$
DECLARE
  parent_artifact_id BIGINT;
BEGIN
  IF NEW.supersedes_version_id IS NULL THEN
    RETURN NEW;
  END IF;
  SELECT artifact_id INTO parent_artifact_id
  FROM i5_scientific_artifact_versions
  WHERE id = NEW.supersedes_version_id;
  IF parent_artifact_id IS NULL THEN
    RAISE EXCEPTION 'ORPHAN_SUPERSESSION: supersedes_version_id % not found', NEW.supersedes_version_id;
  END IF;
  IF parent_artifact_id <> NEW.artifact_id THEN
    RAISE EXCEPTION 'CROSS_ARTIFACT_SUPERSESSION_FORBIDDEN: parent artifact % != child artifact %',
      parent_artifact_id, NEW.artifact_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql
"""
    )
    op.execute(
        """
CREATE TRIGGER trg_sav_supersedes_same_artifact
BEFORE INSERT OR UPDATE OF supersedes_version_id, artifact_id
ON i5_scientific_artifact_versions
FOR EACH ROW EXECUTE PROCEDURE i5_sav_supersedes_same_artifact()
"""
    )

    # Content-drift provenance (NF5) — never overwrite historical version hash
    op.execute(
        """
CREATE TABLE i5_artifact_version_content_drift_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id BIGINT NOT NULL,
    version_label VARCHAR(128) NOT NULL,
    existing_version_id BIGINT NOT NULL,
    existing_content_hash VARCHAR(64),
    incoming_content_hash VARCHAR(64),
    source_profile_id INTEGER,
    locator TEXT,
    publisher_family VARCHAR(256),
    retrieval_note TEXT,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_avcde_artifact FOREIGN KEY (artifact_id)
      REFERENCES i5_scientific_artifacts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_avcde_existing FOREIGN KEY (existing_version_id)
      REFERENCES i5_scientific_artifact_versions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_avcde_source FOREIGN KEY (source_profile_id)
      REFERENCES governed_source_profiles(id) ON DELETE SET NULL
)
"""
    )
    op.execute(
        "CREATE INDEX ix_avcde_artifact_label ON i5_artifact_version_content_drift_events (artifact_id, version_label)"
    )

    op.execute(
        """
ALTER TABLE i5_knowledge_unit_evidence_links
  ADD COLUMN IF NOT EXISTS study_id BIGINT
"""
    )

    # ------------------------------------------------------------------
    # KNOW-03 structured clinical evidence
    # ------------------------------------------------------------------
    op.execute(
        """
CREATE TABLE i5_clinical_studies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_key VARCHAR(256) NOT NULL,
    primary_artifact_id BIGINT,
    primary_artifact_version_id BIGINT,
    study_design VARCHAR(64) NOT NULL,
    trial_phase VARCHAR(32),
    randomized BOOLEAN,
    controlled BOOLEAN,
    blinded BOOLEAN,
    prospective BOOLEAN,
    retrospective BOOLEAN,
    multicenter BOOLEAN,
    sample_size INTEGER,
    start_date DATE,
    completion_date DATE,
    registry_identifier VARCHAR(128),
    study_status VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
    jurisdiction TEXT,
    sponsor_type VARCHAR(64),
    peer_review_status VARCHAR(64),
    title TEXT,
    notes TEXT,
    risk_of_bias VARCHAR(32),
    evidence_quality VARCHAR(64),
    certainty_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_cs_study_key UNIQUE (study_key),
    CONSTRAINT fk_cs_artifact FOREIGN KEY (primary_artifact_id)
      REFERENCES i5_scientific_artifacts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cs_artifact_version FOREIGN KEY (primary_artifact_version_id)
      REFERENCES i5_scientific_artifact_versions(id) ON DELETE RESTRICT,
    CONSTRAINT ck_cs_design CHECK (study_design IN (
      'RANDOMIZED_CONTROLLED_TRIAL','NONRANDOMIZED_TRIAL','SYSTEMATIC_REVIEW','META_ANALYSIS',
      'COHORT','CASE_CONTROL','CROSS_SECTIONAL','CASE_SERIES','CASE_REPORT','DIAGNOSTIC_ACCURACY',
      'PROGNOSTIC','QUALITATIVE','GUIDELINE_EVIDENCE_REVIEW','REAL_WORLD_EVIDENCE','PRECLINICAL','OTHER')),
    CONSTRAINT ck_cs_sample_size CHECK (sample_size IS NULL OR sample_size >= 0),
    CONSTRAINT ck_cs_rob CHECK (risk_of_bias IS NULL OR risk_of_bias IN (
      'LOW','SOME_CONCERNS','HIGH','UNCLEAR','NOT_ASSESSED'))
)
"""
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_cs_registry_notnull ON i5_clinical_studies (registry_identifier) WHERE registry_identifier IS NOT NULL"
    )
    op.execute("CREATE INDEX ix_cs_design ON i5_clinical_studies (study_design)")
    op.execute("CREATE INDEX ix_cs_status ON i5_clinical_studies (study_status)")

    op.execute(
        """
ALTER TABLE i5_knowledge_unit_evidence_links
  ADD CONSTRAINT fk_kuel_study FOREIGN KEY (study_id)
  REFERENCES i5_clinical_studies(id) ON DELETE SET NULL
"""
    )

    op.execute(
        """
CREATE TABLE i5_study_artifact_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    artifact_version_id BIGINT NOT NULL,
    artifact_role VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_sal_study FOREIGN KEY (study_id)
      REFERENCES i5_clinical_studies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sal_sav FOREIGN KEY (artifact_version_id)
      REFERENCES i5_scientific_artifact_versions(id) ON DELETE RESTRICT,
    CONSTRAINT uq_sal_study_sav_role UNIQUE (study_id, artifact_version_id, artifact_role),
    CONSTRAINT ck_sal_role CHECK (artifact_role IN (
      'PRIMARY_RESULTS','PROTOCOL','FOLLOW_UP','SUBGROUP','SAFETY','REGISTRY','CORRECTION','OTHER'))
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_study_condition_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    concept_id BIGINT NOT NULL,
    condition_role VARCHAR(64) NOT NULL DEFAULT 'PRIMARY_CONDITION',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_scl_study FOREIGN KEY (study_id)
      REFERENCES i5_clinical_studies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_scl_concept FOREIGN KEY (concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE RESTRICT,
    CONSTRAINT uq_scl_study_concept_role UNIQUE (study_id, concept_id, condition_role),
    CONSTRAINT ck_scl_role CHECK (condition_role IN (
      'PRIMARY_CONDITION','COMORBID_CONDITION','EXCLUSION_CONDITION','RISK_POPULATION','PREVENTION_TARGET','OTHER'))
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_study_populations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    population_key VARCHAR(256) NOT NULL,
    population_role VARCHAR(64) NOT NULL DEFAULT 'PRIMARY',
    sample_size INTEGER,
    age_min_years DOUBLE PRECISION,
    age_max_years DOUBLE PRECISION,
    sex_eligibility VARCHAR(32),
    disease_duration_text TEXT,
    prior_therapy_text TEXT,
    current_therapy_text TEXT,
    genotype_text TEXT,
    biomarkers_text TEXT,
    functional_scale_text TEXT,
    inclusion_criteria_text TEXT,
    exclusion_criteria_text TEXT,
    population_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_sp_study FOREIGN KEY (study_id)
      REFERENCES i5_clinical_studies(id) ON DELETE RESTRICT,
    CONSTRAINT uq_sp_study_key UNIQUE (study_id, population_key),
    CONSTRAINT ck_sp_sample CHECK (sample_size IS NULL OR sample_size >= 0)
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_study_population_criteria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    population_id BIGINT NOT NULL,
    criterion_type VARCHAR(64) NOT NULL,
    operator VARCHAR(32),
    value_text TEXT,
    value_numeric DOUBLE PRECISION,
    unit VARCHAR(64),
    concept_id BIGINT,
    is_exclusion BOOLEAN NOT NULL DEFAULT FALSE,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    provenance_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_spc_pop FOREIGN KEY (population_id)
      REFERENCES i5_study_populations(id) ON DELETE RESTRICT,
    CONSTRAINT fk_spc_concept FOREIGN KEY (concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE SET NULL,
    CONSTRAINT ck_spc_type CHECK (criterion_type IN (
      'DIAGNOSIS','SUBTYPE','AGE','SEX','GENOTYPE','BIOMARKER','LAB_VALUE','PRIOR_TREATMENT',
      'CURRENT_TREATMENT','COMORBIDITY','CONTRAINDICATION','PREGNANCY','DISEASE_DURATION',
      'FUNCTIONAL_SCORE','OTHER'))
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_interventions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_key VARCHAR(256) NOT NULL,
    preferred_name VARCHAR(512) NOT NULL,
    intervention_category VARCHAR(64) NOT NULL,
    concept_id BIGINT,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_int_key UNIQUE (intervention_key),
    CONSTRAINT fk_int_concept FOREIGN KEY (concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE SET NULL,
    CONSTRAINT ck_int_category CHECK (intervention_category IN (
      'DRUG','BIOLOGIC','GENE_THERAPY','CELL_THERAPY','DEVICE','SURGERY','PROCEDURE','RADIATION',
      'REHABILITATION','PHYSIOTHERAPY','OCCUPATIONAL_THERAPY','SPEECH_THERAPY','RESPIRATORY_SUPPORT',
      'NUTRITION_SUPPORT','DIET','EXERCISE','PSYCHOLOGICAL','BEHAVIORAL','LIFESTYLE','DIGITAL_HEALTH',
      'EDUCATION','SELF_CARE','PALLIATIVE','OTHER'))
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_intervention_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_id BIGINT NOT NULL,
    terminology_system VARCHAR(32) NOT NULL,
    external_code VARCHAR(128) NOT NULL,
    release_version VARCHAR(64),
    mapping_status VARCHAR(32) NOT NULL DEFAULT 'PROVISIONAL',
    provenance_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_im_intervention FOREIGN KEY (intervention_id)
      REFERENCES i5_interventions(id) ON DELETE RESTRICT,
    CONSTRAINT uq_im_system_code_release
      UNIQUE NULLS NOT DISTINCT (terminology_system, external_code, release_version),
    CONSTRAINT ck_im_system CHECK (terminology_system IN (
      'ICD11','MESH','RXNORM','LOINC','UMLS','SNOMED_CT','ICF','ICHI','SEDI_ROOT','OTHER'))
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_study_interventions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    intervention_id BIGINT NOT NULL,
    intervention_role VARCHAR(64) NOT NULL,
    comparator_kind VARCHAR(64),
    dose TEXT,
    dose_unit VARCHAR(64),
    frequency TEXT,
    route VARCHAR(64),
    duration TEXT,
    schedule TEXT,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_si_study FOREIGN KEY (study_id)
      REFERENCES i5_clinical_studies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_si_intervention FOREIGN KEY (intervention_id)
      REFERENCES i5_interventions(id) ON DELETE RESTRICT,
    CONSTRAINT uq_si_study_int_role UNIQUE (study_id, intervention_id, intervention_role),
    CONSTRAINT ck_si_role CHECK (intervention_role IN (
      'EXPERIMENTAL','COMPARATOR','CONTROL','BACKGROUND_THERAPY','COINTERVENTION')),
    CONSTRAINT ck_si_comparator_kind CHECK (comparator_kind IS NULL OR comparator_kind IN (
      'PLACEBO','STANDARD_OF_CARE','NO_INTERVENTION','ACTIVE_COMPARATOR','HISTORICAL_CONTROL','OTHER','UNKNOWN'))
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_clinical_outcomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outcome_key VARCHAR(256) NOT NULL,
    preferred_name VARCHAR(512) NOT NULL,
    outcome_category VARCHAR(64) NOT NULL,
    concept_id BIGINT,
    measurement_scale VARCHAR(128),
    unit VARCHAR(64),
    direction_of_benefit VARCHAR(32),
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_co_key UNIQUE (outcome_key),
    CONSTRAINT fk_co_concept FOREIGN KEY (concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE SET NULL,
    CONSTRAINT ck_co_category CHECK (outcome_category IN (
      'MORTALITY','SURVIVAL','DISEASE_PROGRESSION','RELAPSE','DISABILITY','FUNCTION','QUALITY_OF_LIFE',
      'SYMPTOM','BIOMARKER','LAB','HOSPITALIZATION','ADVERSE_EVENT','TREATMENT_DISCONTINUATION',
      'PATIENT_REPORTED','CAREGIVER_REPORTED','OTHER')),
    CONSTRAINT ck_co_direction CHECK (direction_of_benefit IS NULL OR direction_of_benefit IN (
      'HIGHER_BETTER','LOWER_BETTER','NEUTRAL','CONTEXT_DEPENDENT','UNKNOWN'))
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_study_outcomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    outcome_id BIGINT NOT NULL,
    outcome_role VARCHAR(32) NOT NULL DEFAULT 'PRIMARY',
    time_point TEXT,
    clinically_important_threshold TEXT,
    is_harm BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_so_study FOREIGN KEY (study_id)
      REFERENCES i5_clinical_studies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_so_outcome FOREIGN KEY (outcome_id)
      REFERENCES i5_clinical_outcomes(id) ON DELETE RESTRICT,
    CONSTRAINT uq_so_study_outcome_role UNIQUE (study_id, outcome_id, outcome_role),
    CONSTRAINT ck_so_role CHECK (outcome_role IN ('PRIMARY','SECONDARY','EXPLORATORY','SAFETY','OTHER'))
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_study_effect_estimates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    population_id BIGINT,
    study_intervention_id BIGINT,
    study_comparator_id BIGINT,
    study_outcome_id BIGINT NOT NULL,
    analysis_population VARCHAR(128),
    effect_measure VARCHAR(64) NOT NULL,
    effect_value DOUBLE PRECISION,
    ci_lower DOUBLE PRECISION,
    ci_upper DOUBLE PRECISION,
    confidence_level DOUBLE PRECISION,
    p_value DOUBLE PRECISION,
    absolute_effect DOUBLE PRECISION,
    relative_effect DOUBLE PRECISION,
    baseline_risk DOUBLE PRECISION,
    follow_up_duration DOUBLE PRECISION,
    follow_up_unit VARCHAR(32),
    sample_size_analyzed INTEGER,
    event_count_intervention INTEGER,
    event_count_comparator INTEGER,
    statistical_significance VARCHAR(32),
    clinical_significance VARCHAR(32),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_see_study FOREIGN KEY (study_id)
      REFERENCES i5_clinical_studies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_see_pop FOREIGN KEY (population_id)
      REFERENCES i5_study_populations(id) ON DELETE RESTRICT,
    CONSTRAINT fk_see_si FOREIGN KEY (study_intervention_id)
      REFERENCES i5_study_interventions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_see_sc FOREIGN KEY (study_comparator_id)
      REFERENCES i5_study_interventions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_see_so FOREIGN KEY (study_outcome_id)
      REFERENCES i5_study_outcomes(id) ON DELETE RESTRICT,
    CONSTRAINT ck_see_measure CHECK (effect_measure IN (
      'RISK_RATIO','RELATIVE_RISK','ODDS_RATIO','HAZARD_RATIO','RATE_RATIO','RISK_DIFFERENCE',
      'MEAN_DIFFERENCE','STANDARDIZED_MEAN_DIFFERENCE','CORRELATION','SENSITIVITY','SPECIFICITY',
      'AUC','MEDIAN_DIFFERENCE','PERCENT_CHANGE','RAW_MEAN','RAW_PROPORTION','OTHER')),
    CONSTRAINT ck_see_ci_order CHECK (
      ci_lower IS NULL OR ci_upper IS NULL OR ci_lower <= ci_upper),
    CONSTRAINT ck_see_conf CHECK (
      confidence_level IS NULL OR (confidence_level > 0 AND confidence_level < 100)),
    CONSTRAINT ck_see_n CHECK (sample_size_analyzed IS NULL OR sample_size_analyzed >= 0),
    CONSTRAINT ck_see_events_i CHECK (
      event_count_intervention IS NULL OR sample_size_analyzed IS NULL
      OR event_count_intervention <= sample_size_analyzed),
    CONSTRAINT ck_see_events_c CHECK (
      event_count_comparator IS NULL OR sample_size_analyzed IS NULL
      OR event_count_comparator <= sample_size_analyzed),
    CONSTRAINT ck_see_stat_sig CHECK (statistical_significance IS NULL OR statistical_significance IN (
      'SIGNIFICANT','NOT_SIGNIFICANT','NOT_REPORTED','UNKNOWN')),
    CONSTRAINT ck_see_clin_sig CHECK (clinical_significance IS NULL OR clinical_significance IN (
      'IMPORTANT','NOT_IMPORTANT','UNCERTAIN','NOT_REPORTED','SOURCE_STATED','UNKNOWN'))
)
"""
    )
    op.execute("CREATE INDEX ix_see_study ON i5_study_effect_estimates (study_id)")
    op.execute("CREATE INDEX ix_see_outcome ON i5_study_effect_estimates (study_outcome_id)")

    op.execute(
        """
CREATE TABLE i5_clinical_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_key VARCHAR(256) NOT NULL,
    source_artifact_version_id BIGINT NOT NULL,
    knowledge_unit_id INTEGER,
    recommended_action TEXT NOT NULL,
    recommendation_direction VARCHAR(64) NOT NULL,
    grading_system VARCHAR(64),
    original_grade TEXT,
    normalized_strength VARCHAR(64),
    certainty_system VARCHAR(64),
    original_certainty TEXT,
    benefit_summary TEXT,
    harm_summary TEXT,
    exceptions TEXT,
    contraindications TEXT,
    monitoring_requirements TEXT,
    target_population_text TEXT,
    jurisdiction VARCHAR(128),
    effective_from DATE,
    effective_until DATE,
    superseded_by_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'CURRENT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_cr_key UNIQUE (recommendation_key),
    CONSTRAINT fk_cr_sav FOREIGN KEY (source_artifact_version_id)
      REFERENCES i5_scientific_artifact_versions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cr_ku FOREIGN KEY (knowledge_unit_id)
      REFERENCES knowledge_units(id) ON DELETE SET NULL,
    CONSTRAINT fk_cr_superseded_by FOREIGN KEY (superseded_by_id)
      REFERENCES i5_clinical_recommendations(id) ON DELETE RESTRICT,
    CONSTRAINT ck_cr_no_self_supersede CHECK (superseded_by_id IS NULL OR superseded_by_id <> id),
    CONSTRAINT ck_cr_direction CHECK (recommendation_direction IN (
      'RECOMMEND','SUGGEST','CONDITIONAL','CONSIDER','RECOMMEND_AGAINST','DO_NOT_USE',
      'INSUFFICIENT_EVIDENCE','RESEARCH_ONLY','SPECIALIST_ONLY','OTHER')),
    CONSTRAINT ck_cr_status CHECK (status IN ('CURRENT','HISTORICAL','WITHDRAWN','SUPERSEDED','DRAFT'))
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_clinical_recommendation_condition_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    concept_id BIGINT NOT NULL,
    relation_role VARCHAR(64) NOT NULL DEFAULT 'TARGET_CONDITION',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_crc_rec FOREIGN KEY (recommendation_id)
      REFERENCES i5_clinical_recommendations(id) ON DELETE RESTRICT,
    CONSTRAINT fk_crc_concept FOREIGN KEY (concept_id)
      REFERENCES i5_clinical_concepts(id) ON DELETE RESTRICT,
    CONSTRAINT uq_crc_rec_concept_role UNIQUE (recommendation_id, concept_id, relation_role)
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_clinical_recommendation_evidence_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    target_kind VARCHAR(64) NOT NULL,
    knowledge_unit_id INTEGER,
    artifact_version_id BIGINT,
    study_id BIGINT,
    support_direction VARCHAR(32) NOT NULL DEFAULT 'SUPPORTS',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_crel_rec FOREIGN KEY (recommendation_id)
      REFERENCES i5_clinical_recommendations(id) ON DELETE RESTRICT,
    CONSTRAINT fk_crel_ku FOREIGN KEY (knowledge_unit_id)
      REFERENCES knowledge_units(id) ON DELETE RESTRICT,
    CONSTRAINT fk_crel_sav FOREIGN KEY (artifact_version_id)
      REFERENCES i5_scientific_artifact_versions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_crel_study FOREIGN KEY (study_id)
      REFERENCES i5_clinical_studies(id) ON DELETE RESTRICT,
    CONSTRAINT ck_crel_kind CHECK (target_kind IN (
      'KNOWLEDGE_UNIT','ARTIFACT_VERSION','CLINICAL_STUDY','SYSTEMATIC_REVIEW_ARTIFACT')),
    CONSTRAINT ck_crel_target CHECK (
      (target_kind = 'KNOWLEDGE_UNIT' AND knowledge_unit_id IS NOT NULL)
      OR (target_kind IN ('ARTIFACT_VERSION','SYSTEMATIC_REVIEW_ARTIFACT') AND artifact_version_id IS NOT NULL)
      OR (target_kind = 'CLINICAL_STUDY' AND study_id IS NOT NULL)
    ),
    CONSTRAINT ck_crel_dir CHECK (support_direction IN (
      'SUPPORTS','WEAKLY_SUPPORTS','NEUTRAL','CONTRADICTS','REFUTES','INCONCLUSIVE'))
)
"""
    )

    # W4 terminology expansion foundation — import contract metadata (no bulk ingest)
    op.execute(
        """
CREATE TABLE i5_terminology_import_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terminology_system VARCHAR(32) NOT NULL,
    contract_key VARCHAR(128) NOT NULL,
    official_source_note TEXT NOT NULL,
    rights_status VARCHAR(64) NOT NULL,
    import_scope VARCHAR(64) NOT NULL,
    api_or_mechanism TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'FOUNDATION',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_tic_system_key UNIQUE (terminology_system, contract_key),
    CONSTRAINT ck_tic_system CHECK (terminology_system IN (
      'ICD11','MESH','RXNORM','LOINC','UMLS','SNOMED_CT','ICF','ICHI','SEDI_ROOT','OTHER')),
    CONSTRAINT ck_tic_scope CHECK (import_scope IN (
      'METADATA_ONLY','BOUNDED_FIXTURE','API_CONTRACT','FULL_IMPORT_DEFERRED','PROHIBITED'))
)
"""
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS i5_terminology_import_contracts")
    op.execute("DROP TABLE IF EXISTS i5_clinical_recommendation_evidence_links")
    op.execute("DROP TABLE IF EXISTS i5_clinical_recommendation_condition_links")
    op.execute("DROP TABLE IF EXISTS i5_clinical_recommendations")
    op.execute("DROP TABLE IF EXISTS i5_study_effect_estimates")
    op.execute("DROP TABLE IF EXISTS i5_study_outcomes")
    op.execute("DROP TABLE IF EXISTS i5_clinical_outcomes")
    op.execute("DROP TABLE IF EXISTS i5_study_interventions")
    op.execute("DROP TABLE IF EXISTS i5_intervention_mappings")
    op.execute("DROP TABLE IF EXISTS i5_interventions")
    op.execute("DROP TABLE IF EXISTS i5_study_population_criteria")
    op.execute("DROP TABLE IF EXISTS i5_study_populations")
    op.execute("DROP TABLE IF EXISTS i5_study_condition_links")
    op.execute("DROP TABLE IF EXISTS i5_study_artifact_links")
    op.execute("ALTER TABLE i5_knowledge_unit_evidence_links DROP CONSTRAINT IF EXISTS fk_kuel_study")
    op.execute("ALTER TABLE i5_knowledge_unit_evidence_links DROP COLUMN IF EXISTS study_id")
    op.execute("DROP TABLE IF EXISTS i5_clinical_studies")
    op.execute("DROP TABLE IF EXISTS i5_artifact_version_content_drift_events")
    op.execute("DROP TRIGGER IF EXISTS trg_sav_supersedes_same_artifact ON i5_scientific_artifact_versions")
    op.execute("DROP FUNCTION IF EXISTS i5_sav_supersedes_same_artifact()")
    op.execute("ALTER TABLE i5_scientific_artifact_versions DROP CONSTRAINT IF EXISTS fk_sav_supersedes")
    op.execute("ALTER TABLE i5_scientific_artifact_versions DROP CONSTRAINT IF EXISTS ck_sav_no_self_supersede")
    op.execute("ALTER TABLE i5_sedi_priority_overlays DROP CONSTRAINT IF EXISTS uq_spo_concept_track")
    op.execute(
        "ALTER TABLE i5_sedi_priority_overlays ADD CONSTRAINT uq_spo_concept_track UNIQUE (concept_id, track_key)"
    )
    op.execute("ALTER TABLE i5_knowledge_coverage_cells DROP CONSTRAINT IF EXISTS uq_kcc_cell")
    op.execute(
        "ALTER TABLE i5_knowledge_coverage_cells ADD CONSTRAINT uq_kcc_cell UNIQUE (concept_id, dimension_code, evidence_class)"
    )
    op.execute("ALTER TABLE i5_clinical_concept_mappings DROP CONSTRAINT IF EXISTS uq_ccm_system_code_release")
    op.execute(
        "ALTER TABLE i5_clinical_concept_mappings ADD CONSTRAINT uq_ccm_system_code_release UNIQUE (terminology_system, external_code, release_version)"
    )
