"""I5-KNOW-04 — W0 NF7–NF10 integrity + connectors/change/terminology state.

Revision ID: 065_i5_know04_connectors_change_intelligence
Revises: 064_i5_know03_studies_effects_recs

Additive + constraint hardening only. NO Production apply.
Does NOT activate crawler/RAG/scheduler. Does NOT mass-ingest.
"""

from typing import Sequence, Union

from alembic import op

revision: str = "065_i5_know04_connectors_change_intelligence"
down_revision: Union[str, None] = "064_i5_know03_studies_effects_recs"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # W0 NF7 — cross-study effect ownership via composite FKs
    # ------------------------------------------------------------------
    op.execute(
        """
ALTER TABLE i5_study_populations
  ADD CONSTRAINT uq_sp_id_study UNIQUE (id, study_id)
"""
    )
    op.execute(
        """
ALTER TABLE i5_study_interventions
  ADD CONSTRAINT uq_si_id_study UNIQUE (id, study_id)
"""
    )
    op.execute(
        """
ALTER TABLE i5_study_outcomes
  ADD CONSTRAINT uq_so_id_study UNIQUE (id, study_id)
"""
    )

    op.execute("ALTER TABLE i5_study_effect_estimates DROP CONSTRAINT IF EXISTS fk_see_pop")
    op.execute("ALTER TABLE i5_study_effect_estimates DROP CONSTRAINT IF EXISTS fk_see_si")
    op.execute("ALTER TABLE i5_study_effect_estimates DROP CONSTRAINT IF EXISTS fk_see_sc")
    op.execute("ALTER TABLE i5_study_effect_estimates DROP CONSTRAINT IF EXISTS fk_see_so")

    op.execute(
        """
ALTER TABLE i5_study_effect_estimates
  ADD CONSTRAINT fk_see_pop_study
  FOREIGN KEY (population_id, study_id)
  REFERENCES i5_study_populations(id, study_id)
  ON DELETE RESTRICT
"""
    )
    op.execute(
        """
ALTER TABLE i5_study_effect_estimates
  ADD CONSTRAINT fk_see_si_study
  FOREIGN KEY (study_intervention_id, study_id)
  REFERENCES i5_study_interventions(id, study_id)
  ON DELETE RESTRICT
"""
    )
    op.execute(
        """
ALTER TABLE i5_study_effect_estimates
  ADD CONSTRAINT fk_see_sc_study
  FOREIGN KEY (study_comparator_id, study_id)
  REFERENCES i5_study_interventions(id, study_id)
  ON DELETE RESTRICT
"""
    )
    op.execute(
        """
ALTER TABLE i5_study_effect_estimates
  ADD CONSTRAINT fk_see_so_study
  FOREIGN KEY (study_outcome_id, study_id)
  REFERENCES i5_study_outcomes(id, study_id)
  ON DELETE RESTRICT
"""
    )

    # ------------------------------------------------------------------
    # W0 NF8 — recommendation evidence target XOR
    # ------------------------------------------------------------------
    op.execute("ALTER TABLE i5_clinical_recommendation_evidence_links DROP CONSTRAINT IF EXISTS ck_crel_target")
    op.execute(
        """
ALTER TABLE i5_clinical_recommendation_evidence_links
  ADD CONSTRAINT ck_crel_target_xor CHECK (
    (
      target_kind = 'KNOWLEDGE_UNIT'
      AND knowledge_unit_id IS NOT NULL
      AND artifact_version_id IS NULL
      AND study_id IS NULL
    ) OR (
      target_kind IN ('ARTIFACT_VERSION', 'SYSTEMATIC_REVIEW_ARTIFACT')
      AND artifact_version_id IS NOT NULL
      AND knowledge_unit_id IS NULL
      AND study_id IS NULL
    ) OR (
      target_kind = 'CLINICAL_STUDY'
      AND study_id IS NOT NULL
      AND knowledge_unit_id IS NULL
      AND artifact_version_id IS NULL
    )
  )
"""
    )

    # ------------------------------------------------------------------
    # W0 NF9 — p_value domain [0,1] (NaN comparisons fail CHECK)
    # ------------------------------------------------------------------
    op.execute(
        """
ALTER TABLE i5_study_effect_estimates
  ADD CONSTRAINT ck_see_p_value CHECK (
    p_value IS NULL OR (p_value >= 0 AND p_value <= 1)
  )
"""
    )

    # ------------------------------------------------------------------
    # W0 NF10 — terminology mapping reassignment conflict ledger
    # ------------------------------------------------------------------
    op.execute(
        """
CREATE TABLE i5_terminology_mapping_conflict_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_kind VARCHAR(32) NOT NULL,
    terminology_system VARCHAR(32) NOT NULL,
    external_code VARCHAR(128) NOT NULL,
    release_version VARCHAR(64),
    existing_target_id BIGINT NOT NULL,
    incoming_target_id BIGINT NOT NULL,
    existing_mapping_id BIGINT,
    conflict_code VARCHAR(64) NOT NULL DEFAULT 'SILENT_REMAP_BLOCKED',
    details TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_tmc_kind CHECK (mapping_kind IN ('CLINICAL_CONCEPT', 'INTERVENTION')),
    CONSTRAINT ck_tmc_code CHECK (conflict_code IN (
      'SILENT_REMAP_BLOCKED', 'TARGET_REASSIGNMENT_CONFLICT', 'GOVERNED_REVIEW_REQUIRED'))
)
"""
    )
    op.execute(
        "CREATE INDEX ix_tmc_lookup ON i5_terminology_mapping_conflict_events "
        "(terminology_system, external_code, release_version)"
    )

    # ------------------------------------------------------------------
    # KNOW-04 connector / change / terminology operational tables
    # ------------------------------------------------------------------
    op.execute(
        """
CREATE TABLE i5_connector_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_key VARCHAR(128) NOT NULL,
    source_profile_key VARCHAR(128),
    source_role VARCHAR(64) NOT NULL,
    access_mechanism VARCHAR(64) NOT NULL,
    official_authority_note TEXT NOT NULL,
    base_url VARCHAR(1024),
    connector_state VARCHAR(64) NOT NULL DEFAULT 'CONNECTOR_READY',
    rights_blocker TEXT,
    live_status VARCHAR(64) NOT NULL DEFAULT 'NOT_EXECUTED',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_icp_key UNIQUE (connector_key),
    CONSTRAINT ck_icp_mech CHECK (access_mechanism IN (
      'OFFICIAL_API','OFFICIAL_FEED','OFFICIAL_SYNDICATION','OFFICIAL_DOWNLOAD',
      'OFFICIAL_HTML_ONLY','MANUAL_REVIEW_REQUIRED','NO_SUPPORTED_AUTOMATION')),
    CONSTRAINT ck_icp_state CHECK (connector_state IN (
      'CONNECTOR_READY','AUTH_REQUIRED','LICENSE_ACCEPTANCE_REQUIRED','LIVE_VERIFIED',
      'BOUNDED_IMPORT_VERIFIED','FULL_IMPORT_READY','FULL_IMPORT_DEFERRED',
      'BLOCKED_BY_RIGHTS','BLOCKED_BY_NETWORK_POLICY')),
    CONSTRAINT ck_icp_live CHECK (live_status IN (
      'LIVE_VERIFIED','NOT_EXECUTED_MISSING_CREDENTIALS','NOT_EXECUTED_RIGHTS_BLOCK',
      'NOT_EXECUTED_NETWORK_POLICY','FAILED','NOT_EXECUTED'))
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_connector_cursors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_key VARCHAR(128) NOT NULL,
    cursor_name VARCHAR(128) NOT NULL,
    cursor_value TEXT,
    page_token TEXT,
    last_success_at TIMESTAMPTZ,
    last_error TEXT,
    rate_limit_state VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_icc_key_name UNIQUE (connector_key, cursor_name),
    CONSTRAINT fk_icc_connector FOREIGN KEY (connector_key)
      REFERENCES i5_connector_profiles(connector_key) ON DELETE RESTRICT
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_connector_run_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_key VARCHAR(128) NOT NULL,
    request_type VARCHAR(64) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    result VARCHAR(32) NOT NULL DEFAULT 'STARTED',
    http_status_class VARCHAR(16),
    records_discovered INTEGER NOT NULL DEFAULT 0,
    records_processed INTEGER NOT NULL DEFAULT 0,
    records_blocked_by_rights INTEGER NOT NULL DEFAULT 0,
    records_changed INTEGER NOT NULL DEFAULT 0,
    retractions_detected INTEGER NOT NULL DEFAULT 0,
    retry_count INTEGER NOT NULL DEFAULT 0,
    error_summary TEXT,
    cursor_snapshot TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_icre_connector FOREIGN KEY (connector_key)
      REFERENCES i5_connector_profiles(connector_key) ON DELETE RESTRICT,
    CONSTRAINT ck_icre_result CHECK (result IN (
      'STARTED','SUCCESS','PARTIAL','BLOCKED_RIGHTS','FAILED','IDEMPOTENT_NOOP')),
    CONSTRAINT ck_icre_counts CHECK (
      records_discovered >= 0 AND records_processed >= 0
      AND records_blocked_by_rights >= 0 AND records_changed >= 0
      AND retractions_detected >= 0 AND retry_count >= 0)
)
"""
    )
    op.execute("CREATE INDEX ix_icre_connector ON i5_connector_run_events (connector_key, started_at DESC)")

    op.execute(
        """
CREATE TABLE i5_scientific_change_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change_kind VARCHAR(64) NOT NULL,
    source_connector_key VARCHAR(128),
    external_identifier VARCHAR(256),
    artifact_id BIGINT,
    artifact_version_id BIGINT,
    study_id BIGINT,
    recommendation_id BIGINT,
    related_notice_external_id VARCHAR(256),
    content_hash VARCHAR(128),
    previous_content_hash VARCHAR(128),
    details TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_sce_kind CHECK (change_kind IN (
      'NEW','UPDATED','CORRECTED','SUPERSEDED','WITHDRAWN','RETRACTED',
      'PARTIALLY_RETRACTED','EXPRESSION_OF_CONCERN','REPLACED','DEPRECATED',
      'NO_LONGER_AVAILABLE','RIGHTS_CHANGED','CONTENT_DRIFT',
      'RETRACTION_NOTICE','ERRATUM','CORRECTED_AND_REPUBLISHED','UPDATE')),
    CONSTRAINT fk_sce_artifact FOREIGN KEY (artifact_id)
      REFERENCES i5_scientific_artifacts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sce_version FOREIGN KEY (artifact_version_id)
      REFERENCES i5_scientific_artifact_versions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sce_study FOREIGN KEY (study_id)
      REFERENCES i5_clinical_studies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sce_rec FOREIGN KEY (recommendation_id)
      REFERENCES i5_clinical_recommendations(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sce_has_target CHECK (
      artifact_id IS NOT NULL OR artifact_version_id IS NOT NULL
      OR study_id IS NOT NULL OR recommendation_id IS NOT NULL
      OR external_identifier IS NOT NULL)
)
"""
    )
    op.execute("CREATE INDEX ix_sce_kind ON i5_scientific_change_events (change_kind, created_at DESC)")
    op.execute("CREATE INDEX ix_sce_ext ON i5_scientific_change_events (external_identifier)")

    op.execute(
        """
CREATE TABLE i5_terminology_import_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terminology_system VARCHAR(32) NOT NULL,
    release_version VARCHAR(64) NOT NULL,
    release_date DATE,
    source_note TEXT NOT NULL,
    retrieved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    content_hash VARCHAR(128),
    previous_release_version VARCHAR(64),
    import_status VARCHAR(64) NOT NULL,
    change_count INTEGER NOT NULL DEFAULT 0,
    new_codes INTEGER NOT NULL DEFAULT 0,
    changed_codes INTEGER NOT NULL DEFAULT 0,
    deprecated_codes INTEGER NOT NULL DEFAULT 0,
    replaced_codes INTEGER NOT NULL DEFAULT 0,
    mapping_conflicts INTEGER NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_tir_system_release UNIQUE (terminology_system, release_version),
    CONSTRAINT ck_tir_status CHECK (import_status IN (
      'CONNECTOR_READY','AUTH_REQUIRED','LICENSE_ACCEPTANCE_REQUIRED','LIVE_VERIFIED',
      'BOUNDED_IMPORT_VERIFIED','FULL_IMPORT_READY','FULL_IMPORT_DEFERRED',
      'BLOCKED_BY_RIGHTS','FAILED','IDEMPOTENT_NOOP')),
    CONSTRAINT ck_tir_counts CHECK (
      change_count >= 0 AND new_codes >= 0 AND changed_codes >= 0
      AND deprecated_codes >= 0 AND replaced_codes >= 0 AND mapping_conflicts >= 0)
)
"""
    )

    op.execute(
        """
CREATE TABLE i5_source_ingestion_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_key VARCHAR(128) NOT NULL,
    external_identifier VARCHAR(256) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    canonical_locator TEXT,
    content_hash VARCHAR(128),
    rights_decision VARCHAR(64) NOT NULL,
    processing_decision VARCHAR(64) NOT NULL,
    storage_decision VARCHAR(64) NOT NULL,
    transient_raw_deleted BOOLEAN NOT NULL DEFAULT false,
    retrieved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_sia_connector_ext UNIQUE NULLS NOT DISTINCT (
      connector_key, external_identifier, content_hash),
    CONSTRAINT ck_sia_rights CHECK (rights_decision IN (
      'ALLOWED','DENIED','CONDITIONAL','UNKNOWN','REVIEW_REQUIRED')),
    CONSTRAINT ck_sia_proc CHECK (processing_decision IN (
      'PROCESS','TRANSIENT_PROCESS','BLOCK','METADATA_ONLY')),
    CONSTRAINT ck_sia_store CHECK (storage_decision IN (
      'RAW_RETAIN','DERIVED_ONLY','LINK_ONLY','NO_STORE','TRANSIENT_THEN_DELETE'))
)
"""
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS i5_source_ingestion_audit")
    op.execute("DROP TABLE IF EXISTS i5_terminology_import_runs")
    op.execute("DROP TABLE IF EXISTS i5_scientific_change_events")
    op.execute("DROP TABLE IF EXISTS i5_connector_run_events")
    op.execute("DROP TABLE IF EXISTS i5_connector_cursors")
    op.execute("DROP TABLE IF EXISTS i5_connector_profiles")
    op.execute("DROP TABLE IF EXISTS i5_terminology_mapping_conflict_events")

    op.execute("ALTER TABLE i5_study_effect_estimates DROP CONSTRAINT IF EXISTS ck_see_p_value")
    op.execute("ALTER TABLE i5_clinical_recommendation_evidence_links DROP CONSTRAINT IF EXISTS ck_crel_target_xor")
    op.execute(
        """
ALTER TABLE i5_clinical_recommendation_evidence_links
  ADD CONSTRAINT ck_crel_target CHECK (
    (target_kind = 'KNOWLEDGE_UNIT' AND knowledge_unit_id IS NOT NULL)
    OR (target_kind IN ('ARTIFACT_VERSION','SYSTEMATIC_REVIEW_ARTIFACT') AND artifact_version_id IS NOT NULL)
    OR (target_kind = 'CLINICAL_STUDY' AND study_id IS NOT NULL)
  )
"""
    )

    op.execute("ALTER TABLE i5_study_effect_estimates DROP CONSTRAINT IF EXISTS fk_see_pop_study")
    op.execute("ALTER TABLE i5_study_effect_estimates DROP CONSTRAINT IF EXISTS fk_see_si_study")
    op.execute("ALTER TABLE i5_study_effect_estimates DROP CONSTRAINT IF EXISTS fk_see_sc_study")
    op.execute("ALTER TABLE i5_study_effect_estimates DROP CONSTRAINT IF EXISTS fk_see_so_study")
    op.execute(
        """
ALTER TABLE i5_study_effect_estimates
  ADD CONSTRAINT fk_see_pop FOREIGN KEY (population_id)
  REFERENCES i5_study_populations(id) ON DELETE RESTRICT
"""
    )
    op.execute(
        """
ALTER TABLE i5_study_effect_estimates
  ADD CONSTRAINT fk_see_si FOREIGN KEY (study_intervention_id)
  REFERENCES i5_study_interventions(id) ON DELETE RESTRICT
"""
    )
    op.execute(
        """
ALTER TABLE i5_study_effect_estimates
  ADD CONSTRAINT fk_see_sc FOREIGN KEY (study_comparator_id)
  REFERENCES i5_study_interventions(id) ON DELETE RESTRICT
"""
    )
    op.execute(
        """
ALTER TABLE i5_study_effect_estimates
  ADD CONSTRAINT fk_see_so FOREIGN KEY (study_outcome_id)
  REFERENCES i5_study_outcomes(id) ON DELETE RESTRICT
"""
    )
    op.execute("ALTER TABLE i5_study_outcomes DROP CONSTRAINT IF EXISTS uq_so_id_study")
    op.execute("ALTER TABLE i5_study_interventions DROP CONSTRAINT IF EXISTS uq_si_id_study")
    op.execute("ALTER TABLE i5_study_populations DROP CONSTRAINT IF EXISTS uq_sp_id_study")
