"""I7 lifelong memory foundation (Section45).

Revision ID: 067_i7_lifelong_memory_foundation
Revises: 065_i5_know04_connectors_change_intelligence

Numeric gap 066 is intentional and frozen (RAG/ANN reserved).
Additive only. No destructive backfill. No I8 tables. No pgvector/RAG.
Reconciliation is a separate application step, not this DDL.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "067_i7_lifelong_memory_foundation"
down_revision: Union[str, None] = "065_i5_know04_connectors_change_intelligence"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE user_lifelong_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    user_id INTEGER NOT NULL,
    version INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    structured_profile_json TEXT NOT NULL,
    narrative_compact TEXT,
    source_fact_ids_json TEXT NOT NULL,
    source_event_refs_json TEXT NOT NULL,
    consent_id INTEGER,
    generator_version TEXT NOT NULL,
    built_from_period_start TIMESTAMPTZ NOT NULL,
    built_from_period_end TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    superseded_at TIMESTAMPTZ,
    PRIMARY KEY (id),
    CONSTRAINT uq_ulp_user_version UNIQUE (user_id, version),
    CONSTRAINT ck_ulp_status_vocab CHECK (status IN ('active', 'superseded', 'stale', 'invalidated')),
    CONSTRAINT fk_ulp_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ulp_consent_id FOREIGN KEY (consent_id) REFERENCES user_consents(id) ON DELETE SET NULL
);
"""
    )
    op.execute("""CREATE INDEX ix_ulp_user_status ON user_lifelong_profiles (user_id, status);""")
    op.execute("""CREATE INDEX ix_ulp_user_id ON user_lifelong_profiles (user_id);""")
    op.execute(
        """COMMENT ON TABLE user_lifelong_profiles IS
        'I7 derived compact profile; NOT canonical truth; NOT diagnosis; rebuildable from UMF';"""
    )

    op.execute(
        """
CREATE TABLE user_memory_export_jobs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    user_id INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    schema_version TEXT NOT NULL,
    generator_version TEXT NOT NULL,
    artifact_uri TEXT,
    artifact_sha256 VARCHAR(64),
    bytes INTEGER,
    content_class VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    downloaded_at TIMESTAMPTZ,
    consent_id INTEGER,
    actor_user_id INTEGER,
    error_code TEXT,
    PRIMARY KEY (id),
    CONSTRAINT ck_umej_status_vocab CHECK (
        status IN ('queued', 'running', 'ready', 'expired', 'revoked', 'failed')
    ),
    CONSTRAINT ck_umej_content_class_vocab CHECK (content_class IN ('MEMORY_BUNDLE')),
    CONSTRAINT fk_umej_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_umej_consent_id FOREIGN KEY (consent_id) REFERENCES user_consents(id) ON DELETE SET NULL,
    CONSTRAINT fk_umej_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
);
"""
    )
    op.execute(
        """CREATE INDEX ix_umej_user_status_expires
        ON user_memory_export_jobs (user_id, status, expires_at);"""
    )
    op.execute("""CREATE INDEX ix_umej_user_id ON user_memory_export_jobs (user_id);""")
    op.execute(
        """COMMENT ON TABLE user_memory_export_jobs IS
        'I7 export control-plane; artifact is derived; DB is not the blob store';"""
    )

    op.execute("""ALTER TABLE memory ADD COLUMN retain_until TIMESTAMPTZ;""")
    op.execute("""CREATE INDEX IF NOT EXISTS ix_memory_user_created_at ON memory (user_id, created_at);""")
    op.execute("""CREATE INDEX IF NOT EXISTS ix_memory_retain_until ON memory (retain_until);""")
    op.execute(
        """COMMENT ON COLUMN memory.retain_until IS
        'HOT chat retention bound; NULL means unset (no bulk prune in 067)';"""
    )


def downgrade() -> None:
    op.execute("""DROP INDEX IF EXISTS ix_memory_retain_until;""")
    op.execute("""DROP INDEX IF EXISTS ix_memory_user_created_at;""")
    op.execute("""ALTER TABLE memory DROP COLUMN IF EXISTS retain_until;""")
    op.execute("""DROP TABLE IF EXISTS user_memory_export_jobs;""")
    op.execute("""DROP TABLE IF EXISTS user_lifelong_profiles;""")
