"""I7 Wave-2 governed raw memory lifecycle (additive).

Revision ID: 068_i7_wave2_governed_memory_lifecycle
Revises: 067_i7_lifelong_memory_foundation

Additive only. No destructive backfill. No fabricated consent/provenance for legacy rows.
No HNSW/IVFFLAT/pgvector. Migration execution is a later gate.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "068_i7_wave2_governed_memory_lifecycle"
down_revision: Union[str, None] = "067_i7_lifelong_memory_foundation"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Governed raw chat columns on memory ---
    op.execute("""ALTER TABLE memory ADD COLUMN IF NOT EXISTS consent_id INTEGER;""")
    op.execute("""ALTER TABLE memory ADD COLUMN IF NOT EXISTS provenance_json TEXT;""")
    op.execute("""ALTER TABLE memory ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(128);""")
    op.execute("""ALTER TABLE memory ADD COLUMN IF NOT EXISTS period_timezone VARCHAR(64);""")
    op.execute("""ALTER TABLE memory ADD COLUMN IF NOT EXISTS period_week_start SMALLINT;""")
    op.execute("""ALTER TABLE memory ADD COLUMN IF NOT EXISTS local_period_date DATE;""")
    op.execute(
        """ALTER TABLE memory ADD COLUMN IF NOT EXISTS durable_write BOOLEAN
        NOT NULL DEFAULT FALSE;"""
    )
    op.execute(
        """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_consent_id'
    ) THEN
        ALTER TABLE memory
            ADD CONSTRAINT fk_memory_consent_id
            FOREIGN KEY (consent_id) REFERENCES user_consents(id) ON DELETE SET NULL;
    END IF;
END$$;
"""
    )
    op.execute(
        """
CREATE UNIQUE INDEX IF NOT EXISTS uq_memory_user_idempotency
    ON memory (user_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
"""
    )
    op.execute(
        """CREATE INDEX IF NOT EXISTS ix_memory_user_local_period
        ON memory (user_id, local_period_date);"""
    )
    op.execute(
        """COMMENT ON COLUMN memory.durable_write IS
        'TRUE only when I7 memory consent + provenance + idempotency were satisfied';"""
    )

    # --- UPS finalization / lineage / period identity ---
    op.execute("""ALTER TABLE user_period_summaries ADD COLUMN IF NOT EXISTS finalized_at TIMESTAMPTZ;""")
    op.execute(
        """ALTER TABLE user_period_summaries ADD COLUMN IF NOT EXISTS source_complete BOOLEAN
        NOT NULL DEFAULT FALSE;"""
    )
    op.execute("""ALTER TABLE user_period_summaries ADD COLUMN IF NOT EXISTS integrity_sha256 VARCHAR(64);""")
    op.execute("""ALTER TABLE user_period_summaries ADD COLUMN IF NOT EXISTS lineage_json TEXT;""")
    op.execute("""ALTER TABLE user_period_summaries ADD COLUMN IF NOT EXISTS period_timezone VARCHAR(64);""")
    op.execute("""ALTER TABLE user_period_summaries ADD COLUMN IF NOT EXISTS period_week_start SMALLINT;""")
    op.execute("""ALTER TABLE user_period_summaries ADD COLUMN IF NOT EXISTS consent_id INTEGER;""")
    op.execute("""ALTER TABLE user_period_summaries ADD COLUMN IF NOT EXISTS provenance_json TEXT;""")
    op.execute(
        """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_ups_consent_id'
    ) THEN
        ALTER TABLE user_period_summaries
            ADD CONSTRAINT fk_ups_consent_id
            FOREIGN KEY (consent_id) REFERENCES user_consents(id) ON DELETE SET NULL;
    END IF;
END$$;
"""
    )
    op.execute(
        """CREATE INDEX IF NOT EXISTS ix_ups_user_type_finalized
        ON user_period_summaries (user_id, summary_type, finalized_at);"""
    )

    # --- Independent purge receipts (idempotent) ---
    op.execute(
        """
CREATE TABLE IF NOT EXISTS user_memory_purge_receipts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    user_id INTEGER NOT NULL,
    memory_id INTEGER,
    local_period_date DATE,
    purge_key VARCHAR(160) NOT NULL,
    purged_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    reason VARCHAR(64) NOT NULL,
    integrity_sha256 VARCHAR(64),
    daily_summary_id INTEGER,
    provenance_json TEXT,
    PRIMARY KEY (id),
    CONSTRAINT uq_umpr_purge_key UNIQUE (purge_key),
    CONSTRAINT fk_umpr_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_umpr_daily_summary_id FOREIGN KEY (daily_summary_id)
        REFERENCES user_period_summaries(id) ON DELETE SET NULL
);
"""
    )
    op.execute("""CREATE INDEX IF NOT EXISTS ix_umpr_user_id ON user_memory_purge_receipts (user_id);""")
    op.execute(
        """COMMENT ON TABLE user_memory_purge_receipts IS
        'I7 independent purge receipts; repeated purge is idempotent by purge_key';"""
    )

    # --- I9->I7 derived pattern provenance (optional additive plane) ---
    op.execute(
        """
CREATE TABLE IF NOT EXISTS user_i7_derived_patterns (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    user_id INTEGER NOT NULL,
    pattern_key VARCHAR(128) NOT NULL,
    pattern_json TEXT NOT NULL,
    source_system VARCHAR(32) NOT NULL,
    source_refs_json TEXT NOT NULL,
    provenance_json TEXT NOT NULL,
    consent_id INTEGER,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    superseded_at TIMESTAMPTZ,
    PRIMARY KEY (id),
    CONSTRAINT ck_uidp_source_system CHECK (source_system IN ('I9')),
    CONSTRAINT ck_uidp_status CHECK (status IN ('active', 'superseded', 'invalidated')),
    CONSTRAINT fk_uidp_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_uidp_consent_id FOREIGN KEY (consent_id) REFERENCES user_consents(id) ON DELETE SET NULL
);
"""
    )
    op.execute(
        """CREATE INDEX IF NOT EXISTS ix_uidp_user_status
        ON user_i7_derived_patterns (user_id, status);"""
    )
    op.execute(
        """COMMENT ON TABLE user_i7_derived_patterns IS
        'I7 patterns derived from I9 vitals only; explicit source provenance required';"""
    )


def downgrade() -> None:
    op.execute("""DROP TABLE IF EXISTS user_i7_derived_patterns;""")
    op.execute("""DROP TABLE IF EXISTS user_memory_purge_receipts;""")
    op.execute("""DROP INDEX IF EXISTS ix_ups_user_type_finalized;""")
    op.execute("""ALTER TABLE user_period_summaries DROP CONSTRAINT IF EXISTS fk_ups_consent_id;""")
    op.execute("""ALTER TABLE user_period_summaries DROP COLUMN IF EXISTS provenance_json;""")
    op.execute("""ALTER TABLE user_period_summaries DROP COLUMN IF EXISTS consent_id;""")
    op.execute("""ALTER TABLE user_period_summaries DROP COLUMN IF EXISTS period_week_start;""")
    op.execute("""ALTER TABLE user_period_summaries DROP COLUMN IF EXISTS period_timezone;""")
    op.execute("""ALTER TABLE user_period_summaries DROP COLUMN IF EXISTS lineage_json;""")
    op.execute("""ALTER TABLE user_period_summaries DROP COLUMN IF EXISTS integrity_sha256;""")
    op.execute("""ALTER TABLE user_period_summaries DROP COLUMN IF EXISTS source_complete;""")
    op.execute("""ALTER TABLE user_period_summaries DROP COLUMN IF EXISTS finalized_at;""")
    op.execute("""DROP INDEX IF EXISTS ix_memory_user_local_period;""")
    op.execute("""DROP INDEX IF EXISTS uq_memory_user_idempotency;""")
    op.execute("""ALTER TABLE memory DROP CONSTRAINT IF EXISTS fk_memory_consent_id;""")
    op.execute("""ALTER TABLE memory DROP COLUMN IF EXISTS durable_write;""")
    op.execute("""ALTER TABLE memory DROP COLUMN IF EXISTS local_period_date;""")
    op.execute("""ALTER TABLE memory DROP COLUMN IF EXISTS period_week_start;""")
    op.execute("""ALTER TABLE memory DROP COLUMN IF EXISTS period_timezone;""")
    op.execute("""ALTER TABLE memory DROP COLUMN IF EXISTS idempotency_key;""")
    op.execute("""ALTER TABLE memory DROP COLUMN IF EXISTS provenance_json;""")
    op.execute("""ALTER TABLE memory DROP COLUMN IF EXISTS consent_id;""")
