"""I8 short-lived operational plan state foundation (PD-I8-01 OPTION_B).

Revision ID: 069_i8_operational_plan_state_foundation
Revises: 068_i7_wave2_governed_memory_lifecycle

Additive only. I8-owned operational plan + action tables.
No Gate4/Gate2 schema mutation. No ORM coupling. No pgvector/RAG.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "069_i8_operational_plan_state_foundation"
down_revision: Union[str, None] = "068_i7_wave2_governed_memory_lifecycle"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE i8_operational_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    user_local_date DATE NOT NULL,
    timezone_snapshot VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    generation_mode VARCHAR(16) NOT NULL,
    plan_idempotency_key VARCHAR(128) NOT NULL,
    proactive_evaluation_key VARCHAR(128),
    valid_from TIMESTAMPTZ NOT NULL,
    valid_until TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    superseded_by_plan_id BIGINT,
    trace_id VARCHAR(64),
    row_version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_i8_plan_user_idempotency UNIQUE (user_id, plan_idempotency_key),
    CONSTRAINT uq_i8_plan_id_user UNIQUE (id, user_id),
    CONSTRAINT ck_i8_plan_status CHECK (
        status IN ('ACTIVE', 'COMPLETED', 'SUPERSEDED', 'EXPIRED', 'CANCELLED')
    ),
    CONSTRAINT ck_i8_plan_generation_mode CHECK (
        generation_mode IN ('reactive', 'proactive')
    ),
    CONSTRAINT fk_i8_plan_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_i8_plan_superseded_by FOREIGN KEY (superseded_by_plan_id)
        REFERENCES i8_operational_plans(id) ON DELETE SET NULL
);
"""
    )
    op.execute(
        """
CREATE UNIQUE INDEX uq_i8_plan_user_local_active
ON i8_operational_plans (user_id, user_local_date)
WHERE status = 'ACTIVE';
"""
    )
    op.execute(
        """
CREATE UNIQUE INDEX uq_i8_plan_proactive_eval
ON i8_operational_plans (user_id, user_local_date, proactive_evaluation_key)
WHERE proactive_evaluation_key IS NOT NULL
  AND status IN ('ACTIVE', 'COMPLETED');
"""
    )
    op.execute(
        """CREATE INDEX ix_i8_plan_user_local_date
        ON i8_operational_plans (user_id, user_local_date);"""
    )
    op.execute("""CREATE INDEX ix_i8_plan_expires_at ON i8_operational_plans (expires_at);""")
    op.execute(
        """COMMENT ON TABLE i8_operational_plans IS
        'I8 same-day operational plan header; NOT canonical health truth; NOT long-term history';"""
    )

    op.execute(
        """
CREATE TABLE i8_operational_plan_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    plan_id BIGINT NOT NULL,
    user_id INTEGER NOT NULL,
    action_domain VARCHAR(32) NOT NULL,
    action_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    action_idempotency_key VARCHAR(128) NOT NULL,
    summary_text VARCHAR(512) NOT NULL,
    presentation_json TEXT NOT NULL,
    advisory_importance VARCHAR(16),
    safety_state VARCHAR(32) NOT NULL,
    clarification_required BOOLEAN NOT NULL DEFAULT false,
    knowledge_refs_json TEXT NOT NULL,
    context_refs_json TEXT,
    proactive_evaluation_key VARCHAR(128),
    valid_from TIMESTAMPTZ NOT NULL,
    valid_until TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    trace_id VARCHAR(64),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_i8_action_plan_idempotency UNIQUE (plan_id, action_idempotency_key),
    CONSTRAINT ck_i8_action_status CHECK (
        status IN ('ACTIVE', 'COMPLETED', 'SUPERSEDED', 'EXPIRED', 'CANCELLED', 'FAILED')
    ),
    CONSTRAINT ck_i8_action_domain CHECK (
        action_domain IN (
            'nutrition', 'exercise', 'routine', 'lifestyle', 'wellbeing', 'cross_domain'
        )
    ),
    CONSTRAINT ck_i8_action_safety_state CHECK (
        safety_state IN ('SAFE', 'BLOCKED', 'CLARIFY')
    ),
    CONSTRAINT fk_i8_action_plan_user FOREIGN KEY (plan_id, user_id)
        REFERENCES i8_operational_plans(id, user_id) ON DELETE CASCADE,
    CONSTRAINT fk_i8_action_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
"""
    )
    op.execute(
        """CREATE INDEX ix_i8_action_user_status
        ON i8_operational_plan_actions (user_id, status);"""
    )
    op.execute("""CREATE INDEX ix_i8_action_expires_at ON i8_operational_plan_actions (expires_at);""")
    op.execute("""CREATE INDEX ix_i8_action_plan_id ON i8_operational_plan_actions (plan_id);""")
    op.execute(
        """COMMENT ON TABLE i8_operational_plan_actions IS
        'I8 same-day operational action items; bounded summary/presentation only; Gate4 correlates via source_id';"""
    )


def downgrade() -> None:
    op.execute("""DROP TABLE IF EXISTS i8_operational_plan_actions;""")
    op.execute("""DROP TABLE IF EXISTS i8_operational_plans;""")
