"""I9 health subject, device binding, and packet foundation (PD-I9-V1-01).

Revision ID: 071_i9_health_subject_device_packet_foundation
Revises: 070_i8_proactive_evaluation_ledger

Additive foundation for Health Subject identity, historical device binding,
canonical device packets (device_id + client_packet_id idempotency), and
DEVICE_REPORTED cardiac events. Does not backfill historical observation
subject attribution (NULL = legacy unknown).
"""

from typing import Sequence, Union

from alembic import op


revision: str = "071_i9_health_subject_device_packet_foundation"
down_revision: Union[str, None] = "070_i8_proactive_evaluation_ledger"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE health_subjects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    display_name VARCHAR(255),
    linked_user_id INTEGER,
    subject_kind VARCHAR(32) DEFAULT 'managed' NOT NULL,
    status VARCHAR(16) DEFAULT 'active' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_hs_linked_user_id FOREIGN KEY (linked_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT ck_hs_subject_kind CHECK (subject_kind IN ('self', 'managed', 'legacy_user')),
    CONSTRAINT ck_hs_status CHECK (status IN ('active', 'inactive'))
);
"""
    )
    op.execute("""CREATE INDEX ix_health_subjects_linked_user_id ON health_subjects (linked_user_id);""")
    op.execute("""CREATE INDEX ix_health_subjects_status ON health_subjects (status);""")
    op.execute(
        """COMMENT ON TABLE health_subjects IS 'I9 canonical health data subject; may exist without Sedi account';"""
    )

    op.execute(
        """
CREATE TABLE account_health_subject_access (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    account_user_id INTEGER NOT NULL,
    health_subject_id INTEGER NOT NULL,
    access_role VARCHAR(32) NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    revoked_at TIMESTAMPTZ,
    PRIMARY KEY (id),
    CONSTRAINT fk_ahsa_account_user_id FOREIGN KEY (account_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ahsa_health_subject_id FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE CASCADE,
    CONSTRAINT ck_ahsa_access_role CHECK (access_role IN ('SELF', 'CAREGIVER', 'MANAGER'))
);
"""
    )
    op.execute(
        """
CREATE UNIQUE INDEX uq_ahsa_active_account_subject
ON account_health_subject_access (account_user_id, health_subject_id)
WHERE is_active = true AND revoked_at IS NULL;
"""
    )
    op.execute("""CREATE INDEX ix_ahsa_health_subject_id ON account_health_subject_access (health_subject_id);""")

    op.execute(
        """
CREATE TABLE device_subject_bindings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    device_row_id INTEGER NOT NULL,
    health_subject_id INTEGER NOT NULL,
    bound_at TIMESTAMPTZ NOT NULL,
    unbound_at TIMESTAMPTZ,
    bound_by_account_user_id INTEGER,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_dsb_device_row_id FOREIGN KEY (device_row_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT fk_dsb_health_subject_id FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE RESTRICT,
    CONSTRAINT fk_dsb_bound_by_account_user_id FOREIGN KEY (bound_by_account_user_id) REFERENCES users(id) ON DELETE SET NULL
);
"""
    )
    op.execute(
        """CREATE INDEX ix_dsb_device_row_id_bound_at ON device_subject_bindings (device_row_id, bound_at);"""
    )
    op.execute(
        """
CREATE UNIQUE INDEX uq_dsb_device_active_binding
ON device_subject_bindings (device_row_id)
WHERE unbound_at IS NULL;
"""
    )

    op.execute("""ALTER TABLE devices ADD COLUMN health_subject_id INTEGER;""")
    op.execute("""ALTER TABLE devices ADD COLUMN current_binding_id INTEGER;""")
    op.execute(
        """
ALTER TABLE devices
ADD CONSTRAINT fk_devices_health_subject_id
FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE SET NULL;
"""
    )
    op.execute(
        """
ALTER TABLE devices
ADD CONSTRAINT fk_devices_current_binding_id
FOREIGN KEY (current_binding_id) REFERENCES device_subject_bindings(id) ON DELETE SET NULL;
"""
    )
    op.execute("""CREATE INDEX ix_devices_health_subject_id ON devices (health_subject_id);""")

    op.execute(
        """
CREATE TABLE device_packets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    device_row_id INTEGER NOT NULL,
    device_logical_id VARCHAR(255) NOT NULL,
    client_packet_id VARCHAR(128) NOT NULL,
    sequence_number BIGINT,
    health_subject_id INTEGER NOT NULL,
    binding_id INTEGER,
    measured_at TIMESTAMPTZ NOT NULL,
    measured_interval_start TIMESTAMPTZ,
    measured_interval_end TIMESTAMPTZ,
    server_received_at TIMESTAMPTZ NOT NULL,
    gateway_received_at TIMESTAMPTZ,
    transport VARCHAR(32),
    firmware_version VARCHAR(64),
    hardware_version VARCHAR(64),
    algorithm_version VARCHAR(64),
    quality_metadata_json TEXT,
    provenance_json TEXT,
    ingestion_status VARCHAR(32) DEFAULT 'accepted' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_device_packets_device_client_packet UNIQUE (device_row_id, client_packet_id),
    CONSTRAINT fk_dp_device_row_id FOREIGN KEY (device_row_id) REFERENCES devices(id) ON DELETE RESTRICT,
    CONSTRAINT fk_dp_health_subject_id FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE RESTRICT,
    CONSTRAINT fk_dp_binding_id FOREIGN KEY (binding_id) REFERENCES device_subject_bindings(id) ON DELETE SET NULL,
    CONSTRAINT ck_dp_ingestion_status CHECK (ingestion_status IN ('accepted', 'duplicate', 'rejected'))
);
"""
    )
    op.execute("""CREATE INDEX ix_device_packets_subject_measured ON device_packets (health_subject_id, measured_at);""")
    op.execute("""CREATE INDEX ix_device_packets_device_logical_id ON device_packets (device_logical_id);""")

    op.execute(
        """
CREATE TABLE device_reported_cardiac_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    device_packet_id BIGINT NOT NULL,
    health_subject_id INTEGER NOT NULL,
    event_code VARCHAR(128) NOT NULL,
    event_value_numeric DOUBLE PRECISION,
    event_value_json TEXT,
    detected_at TIMESTAMPTZ NOT NULL,
    source_class VARCHAR(32) DEFAULT 'DEVICE_REPORTED' NOT NULL,
    firmware_version VARCHAR(64),
    hardware_version VARCHAR(64),
    algorithm_version VARCHAR(64),
    provenance_json TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_drc_device_packet_id FOREIGN KEY (device_packet_id) REFERENCES device_packets(id) ON DELETE CASCADE,
    CONSTRAINT fk_drc_health_subject_id FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE RESTRICT,
    CONSTRAINT ck_drc_source_class CHECK (source_class IN ('DEVICE_REPORTED'))
);
"""
    )
    op.execute(
        """CREATE INDEX ix_drc_subject_detected ON device_reported_cardiac_events (health_subject_id, detected_at);"""
    )

    # Subject attribution on canonical I9 rows (nullable for legacy; no false backfill).
    op.execute("""ALTER TABLE device_events ADD COLUMN health_subject_id INTEGER;""")
    op.execute("""ALTER TABLE device_events ADD COLUMN device_packet_id BIGINT;""")
    op.execute(
        """
ALTER TABLE device_events
ADD CONSTRAINT fk_device_events_health_subject_id
FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE SET NULL;
"""
    )
    op.execute(
        """
ALTER TABLE device_events
ADD CONSTRAINT fk_device_events_device_packet_id
FOREIGN KEY (device_packet_id) REFERENCES device_packets(id) ON DELETE SET NULL;
"""
    )
    op.execute("""CREATE INDEX ix_device_events_health_subject_id ON device_events (health_subject_id);""")

    op.execute("""ALTER TABLE physiological_measurements ADD COLUMN health_subject_id INTEGER;""")
    op.execute(
        """
ALTER TABLE physiological_measurements
ADD CONSTRAINT fk_pm_health_subject_id
FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE SET NULL;
"""
    )
    op.execute("""CREATE INDEX ix_pm_health_subject_measured_at ON physiological_measurements (health_subject_id, measured_at);""")
    op.execute("""ALTER TABLE physiological_measurements ALTER COLUMN user_id DROP NOT NULL;""")

    op.execute("""ALTER TABLE physiological_measurement_rollups ADD COLUMN health_subject_id INTEGER;""")
    op.execute(
        """
ALTER TABLE physiological_measurement_rollups
ADD CONSTRAINT fk_pmr_health_subject_id
FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE SET NULL;
"""
    )
    op.execute("""ALTER TABLE physiological_measurement_rollups ADD COLUMN coverage DOUBLE PRECISION;""")
    op.execute("""ALTER TABLE physiological_measurement_rollups ADD COLUMN arrhythmia_event_count INTEGER;""")
    op.execute("""ALTER TABLE physiological_measurement_rollups ADD COLUMN critical_event_count INTEGER;""")

    op.execute("""ALTER TABLE physiological_baselines ADD COLUMN health_subject_id INTEGER;""")
    op.execute(
        """
ALTER TABLE physiological_baselines
ADD CONSTRAINT fk_pb_health_subject_id
FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE SET NULL;
"""
    )

    op.execute("""ALTER TABLE derived_health_signals ADD COLUMN health_subject_id INTEGER;""")
    op.execute(
        """
ALTER TABLE derived_health_signals
ADD CONSTRAINT fk_dhs_health_subject_id
FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE SET NULL;
"""
    )

    # Expand multi-vital vocabulary (I9 foundation).
    op.execute("""ALTER TABLE physiological_measurements DROP CONSTRAINT IF EXISTS ck_pm_measurement_type_vocab;""")
    op.execute(
        """
ALTER TABLE physiological_measurements
ADD CONSTRAINT ck_pm_measurement_type_vocab
CHECK (measurement_type IN ('heart_rate', 'blood_pressure', 'glucose', 'temperature', 'spo2'));
"""
    )

    # Expand rollup bucket kinds (4 weeks != calendar month).
    op.execute(
        """ALTER TABLE physiological_measurement_rollups DROP CONSTRAINT IF EXISTS ck_pmr_bucket_kind_vocab;"""
    )
    op.execute(
        """
ALTER TABLE physiological_measurement_rollups
ADD CONSTRAINT ck_pmr_bucket_kind_vocab
CHECK (bucket_kind IN ('hourly', 'daily', 'weekly', 'calendar_month', 'yearly'));
"""
    )

    # Device registry foundation: create subjects + bindings for existing devices only.
    op.execute(
        """
INSERT INTO health_subjects (display_name, linked_user_id, subject_kind, status, created_at, updated_at)
SELECT DISTINCT
    COALESCE(u.name, 'Legacy subject'),
    COALESCE(d.subject_user_id, d.user_id),
    CASE WHEN COALESCE(d.subject_user_id, d.user_id) = d.user_id THEN 'self' ELSE 'legacy_user' END,
    'active',
    now(),
    now()
FROM devices d
JOIN users u ON u.id = COALESCE(d.subject_user_id, d.user_id)
WHERE NOT EXISTS (
    SELECT 1 FROM health_subjects hs
    WHERE hs.linked_user_id = COALESCE(d.subject_user_id, d.user_id)
      AND hs.subject_kind IN ('self', 'legacy_user')
);
"""
    )
    op.execute(
        """
INSERT INTO account_health_subject_access (account_user_id, health_subject_id, access_role, is_active, created_at)
SELECT DISTINCT d.user_id, hs.id,
    CASE WHEN COALESCE(d.subject_user_id, d.user_id) = d.user_id THEN 'SELF' ELSE 'MANAGER' END,
    true, now()
FROM devices d
JOIN health_subjects hs ON hs.linked_user_id = COALESCE(d.subject_user_id, d.user_id)
WHERE NOT EXISTS (
    SELECT 1 FROM account_health_subject_access a
    WHERE a.account_user_id = d.user_id AND a.health_subject_id = hs.id AND a.is_active = true
);
"""
    )
    op.execute(
        """
INSERT INTO device_subject_bindings (device_row_id, health_subject_id, bound_at, bound_by_account_user_id, created_at)
SELECT d.id, hs.id, COALESCE(d.created_at, now()), d.user_id, now()
FROM devices d
JOIN health_subjects hs ON hs.linked_user_id = COALESCE(d.subject_user_id, d.user_id)
WHERE NOT EXISTS (
    SELECT 1 FROM device_subject_bindings b WHERE b.device_row_id = d.id AND b.unbound_at IS NULL
);
"""
    )
    op.execute(
        """
UPDATE devices d
SET health_subject_id = b.health_subject_id,
    current_binding_id = b.id
FROM device_subject_bindings b
WHERE b.device_row_id = d.id AND b.unbound_at IS NULL;
"""
    )


def downgrade() -> None:
    op.execute("""ALTER TABLE derived_health_signals DROP CONSTRAINT IF EXISTS fk_dhs_health_subject_id;""")
    op.execute("""ALTER TABLE derived_health_signals DROP COLUMN IF EXISTS health_subject_id;""")

    op.execute("""ALTER TABLE physiological_baselines DROP CONSTRAINT IF EXISTS fk_pb_health_subject_id;""")
    op.execute("""ALTER TABLE physiological_baselines DROP COLUMN IF EXISTS health_subject_id;""")

    op.execute("""ALTER TABLE physiological_measurement_rollups DROP CONSTRAINT IF EXISTS ck_pmr_bucket_kind_vocab;""")
    op.execute(
        """
ALTER TABLE physiological_measurement_rollups
ADD CONSTRAINT ck_pmr_bucket_kind_vocab
CHECK (bucket_kind IN ('hourly', 'daily'));
"""
    )
    op.execute("""ALTER TABLE physiological_measurement_rollups DROP CONSTRAINT IF EXISTS fk_pmr_health_subject_id;""")
    op.execute("""ALTER TABLE physiological_measurement_rollups DROP COLUMN IF EXISTS critical_event_count;""")
    op.execute("""ALTER TABLE physiological_measurement_rollups DROP COLUMN IF EXISTS arrhythmia_event_count;""")
    op.execute("""ALTER TABLE physiological_measurement_rollups DROP COLUMN IF EXISTS coverage;""")
    op.execute("""ALTER TABLE physiological_measurement_rollups DROP COLUMN IF EXISTS health_subject_id;""")

    op.execute(
        """
UPDATE physiological_measurements pm
SET user_id = hs.linked_user_id
FROM health_subjects hs
WHERE pm.health_subject_id = hs.id AND pm.user_id IS NULL AND hs.linked_user_id IS NOT NULL;
"""
    )
    op.execute("""DELETE FROM physiological_measurements WHERE user_id IS NULL;""")
    op.execute("""ALTER TABLE physiological_measurements DROP CONSTRAINT IF EXISTS ck_pm_measurement_type_vocab;""")
    op.execute(
        """
ALTER TABLE physiological_measurements
ADD CONSTRAINT ck_pm_measurement_type_vocab
CHECK (measurement_type IN ('heart_rate'));
"""
    )
    op.execute("""ALTER TABLE physiological_measurements DROP CONSTRAINT IF EXISTS fk_pm_health_subject_id;""")
    op.execute("""ALTER TABLE physiological_measurements DROP COLUMN IF EXISTS health_subject_id;""")
    op.execute("""ALTER TABLE physiological_measurements ALTER COLUMN user_id SET NOT NULL;""")

    op.execute("""ALTER TABLE device_events DROP CONSTRAINT IF EXISTS fk_device_events_device_packet_id;""")
    op.execute("""ALTER TABLE device_events DROP CONSTRAINT IF EXISTS fk_device_events_health_subject_id;""")
    op.execute("""ALTER TABLE device_events DROP COLUMN IF EXISTS device_packet_id;""")
    op.execute("""ALTER TABLE device_events DROP COLUMN IF EXISTS health_subject_id;""")

    op.execute("""DROP TABLE IF EXISTS device_reported_cardiac_events;""")
    op.execute("""DROP TABLE IF EXISTS device_packets;""")

    op.execute("""ALTER TABLE devices DROP CONSTRAINT IF EXISTS fk_devices_current_binding_id;""")
    op.execute("""ALTER TABLE devices DROP CONSTRAINT IF EXISTS fk_devices_health_subject_id;""")
    op.execute("""ALTER TABLE devices DROP COLUMN IF EXISTS current_binding_id;""")
    op.execute("""ALTER TABLE devices DROP COLUMN IF EXISTS health_subject_id;""")

    op.execute("""DROP TABLE IF EXISTS device_subject_bindings;""")
    op.execute("""DROP TABLE IF EXISTS account_health_subject_access;""")
    op.execute("""DROP TABLE IF EXISTS health_subjects;""")
