"""I9 device claim, gateway authorization, and lifecycle audit (PD-I9-V1-02).

Revision ID: 072_i9_device_claim_gateway_lifecycle_foundation
Revises: 071_i9_health_subject_device_packet_foundation

Bounded additive schema for claim lifecycle, per-device credential fingerprint,
mobile gateway authorization, and auditable release/transfer/revoke operations.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "072_i9_device_claim_gateway_lifecycle_foundation"
down_revision: Union[str, None] = "071_i9_health_subject_device_packet_foundation"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
ALTER TABLE devices
ADD COLUMN claim_lifecycle_status VARCHAR(32) DEFAULT 'claimed' NOT NULL;
"""
    )
    op.execute(
        """
ALTER TABLE devices
ADD CONSTRAINT ck_devices_claim_lifecycle_status
CHECK (claim_lifecycle_status IN ('unclaimed', 'claimed', 'suspended', 'revoked', 'released'));
"""
    )
    op.execute("""CREATE INDEX ix_devices_claim_lifecycle_status ON devices (claim_lifecycle_status);""")

    op.execute(
        """
ALTER TABLE devices
ADD COLUMN credential_kind VARCHAR(64) DEFAULT 'per_device_symmetric' NOT NULL;
"""
    )
    op.execute(
        """
ALTER TABLE devices
ADD COLUMN credential_fingerprint VARCHAR(64);
"""
    )
    op.execute("""CREATE INDEX ix_devices_credential_fingerprint ON devices (credential_fingerprint);""")

    op.execute(
        """
ALTER TABLE devices
ADD COLUMN owner_account_user_id INTEGER;
"""
    )
    op.execute(
        """
ALTER TABLE devices
ADD CONSTRAINT fk_devices_owner_account_user_id
FOREIGN KEY (owner_account_user_id) REFERENCES users(id) ON DELETE SET NULL;
"""
    )
    op.execute("""CREATE INDEX ix_devices_owner_account_user_id ON devices (owner_account_user_id);""")

    # Unclaimed platform identities may exist before account claim.
    op.execute("""ALTER TABLE devices ALTER COLUMN user_id DROP NOT NULL;""")

    op.execute(
        """
UPDATE devices
SET claim_lifecycle_status = 'revoked'
WHERE status = 'revoked';
"""
    )
    op.execute(
        """
UPDATE devices
SET claim_lifecycle_status = 'claimed',
    owner_account_user_id = user_id
WHERE status = 'active'
  AND (health_subject_id IS NOT NULL OR user_id IS NOT NULL);
"""
    )
    op.execute(
        """
UPDATE devices
SET credential_fingerprint = LEFT(token_hash, 16)
WHERE credential_fingerprint IS NULL AND token_hash IS NOT NULL;
"""
    )

    op.execute(
        """
CREATE TABLE device_mobile_gateway_authorizations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    device_row_id INTEGER NOT NULL,
    gateway_install_id VARCHAR(128) NOT NULL,
    authorized_by_account_user_id INTEGER NOT NULL,
    authorized_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_dmga_device_row_id FOREIGN KEY (device_row_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT fk_dmga_authorized_by FOREIGN KEY (authorized_by_account_user_id) REFERENCES users(id) ON DELETE CASCADE
);
"""
    )
    op.execute(
        """
CREATE UNIQUE INDEX uq_dmga_device_gateway_active
ON device_mobile_gateway_authorizations (device_row_id, gateway_install_id)
WHERE is_active = true AND revoked_at IS NULL;
"""
    )
    op.execute(
        """CREATE INDEX ix_dmga_gateway_install_id ON device_mobile_gateway_authorizations (gateway_install_id);"""
    )

    op.execute(
        """
CREATE TABLE device_lifecycle_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    device_row_id INTEGER NOT NULL,
    operation VARCHAR(64) NOT NULL,
    actor_account_user_id INTEGER,
    health_subject_id INTEGER,
    gateway_install_id VARCHAR(128),
    detail_json TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_dla_device_row_id FOREIGN KEY (device_row_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT fk_dla_actor FOREIGN KEY (actor_account_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_dla_health_subject FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE SET NULL
);
"""
    )
    op.execute(
        """CREATE INDEX ix_dla_device_created ON device_lifecycle_audit_log (device_row_id, created_at);"""
    )


def downgrade() -> None:
    op.execute("""DROP TABLE IF EXISTS device_lifecycle_audit_log;""")
    op.execute("""DROP TABLE IF EXISTS device_mobile_gateway_authorizations;""")

    op.execute(
        """
UPDATE devices SET user_id = owner_account_user_id
WHERE user_id IS NULL AND owner_account_user_id IS NOT NULL;
"""
    )

    op.execute("""ALTER TABLE devices DROP CONSTRAINT IF EXISTS fk_devices_owner_account_user_id;""")
    op.execute("""ALTER TABLE devices DROP COLUMN IF EXISTS owner_account_user_id;""")
    op.execute("""ALTER TABLE devices DROP COLUMN IF EXISTS credential_fingerprint;""")
    op.execute("""ALTER TABLE devices DROP COLUMN IF EXISTS credential_kind;""")
    op.execute("""ALTER TABLE devices DROP CONSTRAINT IF EXISTS ck_devices_claim_lifecycle_status;""")
    op.execute("""ALTER TABLE devices DROP COLUMN IF EXISTS claim_lifecycle_status;""")

    op.execute("""ALTER TABLE devices ALTER COLUMN user_id SET NOT NULL;""")
