"""I10 notification domain foundation (PD-I10-B01).

Revision ID: 074_i10_notification_domain_foundation
Revises: 073_i9_subject_native_rollup_baseline

Additive only:
- notifications: subject attribution + I10 policy linkage (nullable for legacy rows)
- i10_notification_decisions: bounded policy ledger
- health_subject_notification_grants: subject-scoped notification authorization

No backfill. No caregiver substitution. No legacy row mutation beyond nullable column adds.
"""

from typing import Sequence, Union

from alembic import op

revision: str = "074_i10_notification_domain_foundation"
down_revision: Union[str, None] = "073_i9_subject_native_rollup_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE i10_notification_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    candidate_key VARCHAR(255) NOT NULL,
    health_subject_id INTEGER,
    recipient_user_id INTEGER NOT NULL,
    source_owner VARCHAR(64) NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_id VARCHAR(255) NOT NULL,
    source_version VARCHAR(64),
    semantic_family VARCHAR(64),
    decision VARCHAR(32) NOT NULL,
    reason_code VARCHAR(128) NOT NULL,
    priority VARCHAR(16),
    privacy_class VARCHAR(32),
    provenance_refs_json TEXT,
    valid_from TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    notification_id INTEGER,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_i10_dec_health_subject_id
        FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE RESTRICT,
    CONSTRAINT fk_i10_dec_recipient_user_id
        FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_i10_decision_value
        CHECK (decision IN ('SEND', 'DEFER', 'SUPPRESS', 'BUNDLE', 'ESCALATE', 'EXPIRE')),
    CONSTRAINT uq_i10_decision_occurrence
        UNIQUE (candidate_key, recipient_user_id, health_subject_id)
);
"""
    )
    op.execute(
        """CREATE INDEX ix_i10_decision_subject_recipient
ON i10_notification_decisions (health_subject_id, recipient_user_id);"""
    )
    op.execute(
        """CREATE INDEX ix_i10_decision_notification_id
ON i10_notification_decisions (notification_id);"""
    )
    op.execute(
        """
COMMENT ON TABLE i10_notification_decisions IS
'I10 bounded policy decision ledger — refs only, no raw health/RAG/chat content';
"""
    )

    op.execute("""ALTER TABLE notifications ADD COLUMN IF NOT EXISTS health_subject_id INTEGER;""")
    op.execute("""ALTER TABLE notifications ADD COLUMN IF NOT EXISTS semantic_family VARCHAR(64);""")
    op.execute("""ALTER TABLE notifications ADD COLUMN IF NOT EXISTS recipient_kind VARCHAR(32);""")
    op.execute("""ALTER TABLE notifications ADD COLUMN IF NOT EXISTS privacy_class VARCHAR(32);""")
    op.execute("""ALTER TABLE notifications ADD COLUMN IF NOT EXISTS i10_policy_decision_id BIGINT;""")

    op.execute(
        """
ALTER TABLE notifications
ADD CONSTRAINT fk_notifications_health_subject_id
FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE SET NULL;
"""
    )
    op.execute(
        """CREATE INDEX IF NOT EXISTS ix_notifications_health_subject_id
ON notifications (health_subject_id);"""
    )
    op.execute(
        """CREATE INDEX IF NOT EXISTS ix_notifications_i10_policy_decision_id
ON notifications (i10_policy_decision_id);"""
    )

    op.execute(
        """
CREATE TABLE health_subject_notification_grants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    health_subject_id INTEGER NOT NULL,
    recipient_user_id INTEGER NOT NULL,
    notification_scope VARCHAR(64) NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    authorization_source VARCHAR(64) NOT NULL,
    user_caregiver_id INTEGER,
    granted_by_account_user_id INTEGER,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    revoked_at TIMESTAMPTZ,
    PRIMARY KEY (id),
    CONSTRAINT fk_hsng_health_subject_id
        FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE CASCADE,
    CONSTRAINT fk_hsng_recipient_user_id
        FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_hsng_user_caregiver_id
        FOREIGN KEY (user_caregiver_id) REFERENCES user_caregivers(id) ON DELETE SET NULL,
    CONSTRAINT fk_hsng_granted_by_account_user_id
        FOREIGN KEY (granted_by_account_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT ck_hsng_notification_scope
        CHECK (notification_scope IN (
            'GENERAL_STATUS', 'DEVICE_STATUS', 'CARE_ACTION',
            'SAFETY_ESCALATION', 'SENSITIVE_HEALTH_DETAIL'
        )),
    CONSTRAINT ck_hsng_authorization_source
        CHECK (authorization_source IN (
            'MANUAL', 'CAREGIVER_PROFILE_LINK', 'SELF_DEFAULT', 'SYSTEM'
        ))
);
"""
    )
    op.execute(
        """
CREATE UNIQUE INDEX uq_hsng_active_subject_recipient_scope
ON health_subject_notification_grants (health_subject_id, recipient_user_id, notification_scope)
WHERE is_active = true AND revoked_at IS NULL;
"""
    )
    op.execute(
        """CREATE INDEX ix_hsng_user_caregiver_id
ON health_subject_notification_grants (user_caregiver_id);"""
    )
    op.execute(
        """
COMMENT ON TABLE health_subject_notification_grants IS
'Subject-scoped notification grant — does not replace AccountHealthSubjectAccess';
"""
    )

    # Deferred FK: notifications -> i10_notification_decisions (after both tables exist)
    op.execute(
        """
ALTER TABLE notifications
ADD CONSTRAINT fk_notifications_i10_policy_decision_id
FOREIGN KEY (i10_policy_decision_id) REFERENCES i10_notification_decisions(id) ON DELETE SET NULL;
"""
    )
    op.execute(
        """
ALTER TABLE i10_notification_decisions
ADD CONSTRAINT fk_i10_dec_notification_id
FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE SET NULL;
"""
    )


def downgrade() -> None:
    op.execute(
        """ALTER TABLE i10_notification_decisions
DROP CONSTRAINT IF EXISTS fk_i10_dec_notification_id;"""
    )
    op.execute(
        """ALTER TABLE notifications
DROP CONSTRAINT IF EXISTS fk_notifications_i10_policy_decision_id;"""
    )
    op.execute("""DROP TABLE IF EXISTS health_subject_notification_grants;""")
    op.execute(
        """ALTER TABLE notifications DROP CONSTRAINT IF EXISTS fk_notifications_health_subject_id;"""
    )
    op.execute("""DROP INDEX IF EXISTS ix_notifications_i10_policy_decision_id;""")
    op.execute("""DROP INDEX IF EXISTS ix_notifications_health_subject_id;""")
    op.execute("""ALTER TABLE notifications DROP COLUMN IF EXISTS i10_policy_decision_id;""")
    op.execute("""ALTER TABLE notifications DROP COLUMN IF EXISTS privacy_class;""")
    op.execute("""ALTER TABLE notifications DROP COLUMN IF EXISTS recipient_kind;""")
    op.execute("""ALTER TABLE notifications DROP COLUMN IF EXISTS semantic_family;""")
    op.execute("""ALTER TABLE notifications DROP COLUMN IF EXISTS health_subject_id;""")
    op.execute("""DROP TABLE IF EXISTS i10_notification_decisions;""")
