"""I9 DeviceReportedVitalStatus — gadget STABLE|UNSTABLE SoT.

Revision ID: 080_i9_device_reported_vital_status
Revises: 079_i10_cni_owner_provenance_nullable

Additive only. Gadget is sole STABLE/UNSTABLE authority.
Does not activate clinical rules, Smart-RAG, or FCM.
"""

from typing import Sequence, Union

from alembic import op

revision: str = "080_i9_device_reported_vital_status"
down_revision: Union[str, None] = "079_i10_cni_owner_provenance_nullable"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE device_reported_vital_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    device_packet_id BIGINT NOT NULL,
    health_subject_id INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL,
    source_class VARCHAR(32) DEFAULT 'DEVICE_REPORTED' NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL,
    server_received_at TIMESTAMPTZ NOT NULL,
    provenance_json TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_drvs_device_packet_id UNIQUE (device_packet_id),
    CONSTRAINT fk_drvs_device_packet_id
        FOREIGN KEY (device_packet_id) REFERENCES device_packets(id) ON DELETE CASCADE,
    CONSTRAINT fk_drvs_health_subject_id
        FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE RESTRICT,
    CONSTRAINT ck_drvs_status CHECK (status IN ('STABLE', 'UNSTABLE')),
    CONSTRAINT ck_drvs_source_class CHECK (source_class IN ('DEVICE_REPORTED'))
);
"""
    )
    op.execute(
        """CREATE INDEX ix_drvs_subject_detected
ON device_reported_vital_statuses (health_subject_id, detected_at);"""
    )
    op.execute(
        """
COMMENT ON TABLE device_reported_vital_statuses IS
'I9 gadget-reported STABLE|UNSTABLE vital status — DEVICE_REPORTED SoT; not clinical safety';
"""
    )


def downgrade() -> None:
    op.execute("""DROP TABLE IF EXISTS device_reported_vital_statuses;""")
