"""I9 absolute vital policy schema scaffold (G8).

Revision ID: 085_i9_absolute_vital_policy_schema_scaffold
Revises: 084_device_category_setup_code_authority

SCHEMA_FOUNDATION_ONLY. Additive tables only.
NO seed rows. NO numeric clinical thresholds.
NO interpreter / I10 producer / activation.
"""

from typing import Sequence, Union

from alembic import op

revision: str = "085_i9_absolute_vital_policy_schema_scaffold"
down_revision: Union[str, None] = "084_device_category_setup_code_authority"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE i9_absolute_vital_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy_key VARCHAR(64) NOT NULL,
    version VARCHAR(32) NOT NULL,
    status VARCHAR(32) DEFAULT 'draft' NOT NULL,
    population_scope_json TEXT,
    context_scope_json TEXT,
    evidence_refs_json TEXT,
    governance_approval_ref VARCHAR(255),
    source_applicability_json TEXT,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_i9avp_policy_key_version UNIQUE (policy_key, version)
);
"""
    )
    op.execute(
        """CREATE INDEX ix_i9avp_status ON i9_absolute_vital_policies (status);"""
    )
    op.execute(
        """CREATE INDEX ix_i9avp_effective_from ON i9_absolute_vital_policies (effective_from);"""
    )
    op.execute(
        """
COMMENT ON TABLE i9_absolute_vital_policies IS
'I9 versioned absolute-vital policy authority scaffold — no seeded numerics; not runtime-active in G8';
"""
    )

    op.execute(
        """
CREATE TABLE i9_absolute_vital_policy_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy_id BIGINT NOT NULL,
    metric VARCHAR(32) NOT NULL,
    rule_kind VARCHAR(64) NOT NULL,
    context_gates_json TEXT,
    rule_payload_json TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_i9avpr_policy_id
        FOREIGN KEY (policy_id) REFERENCES i9_absolute_vital_policies(id) ON DELETE CASCADE
);
"""
    )
    op.execute(
        """CREATE INDEX ix_i9avpr_policy_id ON i9_absolute_vital_policy_rules (policy_id);"""
    )
    op.execute(
        """CREATE INDEX ix_i9avpr_metric ON i9_absolute_vital_policy_rules (metric);"""
    )
    op.execute(
        """
COMMENT ON TABLE i9_absolute_vital_policy_rules IS
'Generic absolute-vital policy rule container — rule_payload_json must not hold G8-unauthorized clinical cutoffs';
"""
    )

    op.execute(
        """
CREATE TABLE i9_absolute_vital_alert_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    health_subject_id INTEGER NOT NULL,
    policy_id BIGINT NOT NULL,
    policy_rule_id BIGINT,
    metric VARCHAR(32) NOT NULL,
    physiological_measurement_id BIGINT,
    observation_at TIMESTAMPTZ NOT NULL,
    evidence_provenance_json TEXT,
    quality_context_state VARCHAR(64),
    confirmation_state VARCHAR(64),
    confirmation_ref VARCHAR(255),
    governed_outcome VARCHAR(64) NOT NULL,
    severity_band VARCHAR(32),
    occurrence_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_i9avar_occurrence_key UNIQUE (occurrence_key),
    CONSTRAINT fk_i9avar_health_subject_id
        FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE RESTRICT,
    CONSTRAINT fk_i9avar_policy_id
        FOREIGN KEY (policy_id) REFERENCES i9_absolute_vital_policies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_i9avar_policy_rule_id
        FOREIGN KEY (policy_rule_id) REFERENCES i9_absolute_vital_policy_rules(id) ON DELETE SET NULL,
    CONSTRAINT fk_i9avar_physiological_measurement_id
        FOREIGN KEY (physiological_measurement_id) REFERENCES physiological_measurements(id) ON DELETE SET NULL
);
"""
    )
    op.execute(
        """CREATE INDEX ix_i9avar_subject_metric
ON i9_absolute_vital_alert_results (health_subject_id, metric);"""
    )
    op.execute(
        """CREATE INDEX ix_i9avar_policy_id ON i9_absolute_vital_alert_results (policy_id);"""
    )
    op.execute(
        """CREATE INDEX ix_i9avar_observation_at
ON i9_absolute_vital_alert_results (observation_at);"""
    )
    op.execute(
        """
COMMENT ON TABLE i9_absolute_vital_alert_results IS
'I9 ABSOLUTE_VITAL_ALERT_STATUS persistence scaffold — no G8 writer/producer; RESTRICT on policy+subject';
"""
    )


def downgrade() -> None:
    op.execute("""DROP TABLE IF EXISTS i9_absolute_vital_alert_results;""")
    op.execute("""DROP TABLE IF EXISTS i9_absolute_vital_policy_rules;""")
    op.execute("""DROP TABLE IF EXISTS i9_absolute_vital_policies;""")
