"""I9 vital observation context authority persistence (G12).

Revision ID: 086_i9_vital_observation_context_authority
Revises: 085_i9_absolute_vital_policy_schema_scaffold

SCHEMA ONLY. No seeds. No clinical thresholds. No runtime producers.
NULL context fields mean UNKNOWN/absent — row presence ≠ invented authority.
"""

from typing import Sequence, Union

from alembic import op

revision: str = "086_i9_vital_observation_context_authority"
down_revision: Union[str, None] = "085_i9_absolute_vital_policy_schema_scaffold"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE i9_vital_observation_contexts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    health_subject_id INTEGER NOT NULL,
    source_class VARCHAR(64) NOT NULL,
    source_row_id BIGINT NOT NULL,
    physiological_measurement_id BIGINT,
    health_data_id INTEGER,
    metric VARCHAR(32) NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL,
    activity_state VARCHAR(64),
    altitude_value DOUBLE PRECISION,
    altitude_unit VARCHAR(32),
    temperature_method VARCHAR(64),
    quality_state VARCHAR(64),
    confirmation_state VARCHAR(64),
    context_authority_json TEXT,
    occurrence_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_i9voc_occurrence_key UNIQUE (occurrence_key),
    CONSTRAINT uq_i9voc_source_metric UNIQUE (source_class, source_row_id, metric),
    CONSTRAINT fk_i9voc_health_subject_id
        FOREIGN KEY (health_subject_id) REFERENCES health_subjects(id) ON DELETE RESTRICT,
    CONSTRAINT fk_i9voc_physiological_measurement_id
        FOREIGN KEY (physiological_measurement_id) REFERENCES physiological_measurements(id) ON DELETE SET NULL,
    CONSTRAINT fk_i9voc_health_data_id
        FOREIGN KEY (health_data_id) REFERENCES health_data(id) ON DELETE SET NULL
);
"""
    )
    op.execute(
        """CREATE INDEX ix_i9voc_subject_observed
ON i9_vital_observation_contexts (health_subject_id, observed_at);"""
    )
    op.execute(
        """CREATE INDEX ix_i9voc_metric ON i9_vital_observation_contexts (metric);"""
    )
    op.execute(
        """
COMMENT ON TABLE i9_vital_observation_contexts IS
'I9 vital observation context authority scaffold — NULL=UNKNOWN; no G12 producers/thresholds';
"""
    )


def downgrade() -> None:
    op.execute("""DROP TABLE IF EXISTS i9_vital_observation_contexts;""")
