# app/core/conversation/brain.py
"""
Conversation Brain - Health Care Assistant (COMMANDER)

RESPONSIBILITY:
- Entry point for all chat interactions
- Receives: user_id, user_message
- Determines current conversation stage
- Manages three types of memory: SHORT-TERM, MEDIUM-TERM, LONG-TERM
- Requests text from prompts.py (AI-generated, NO hardcoded text)
- Updates memory via memory.py
- Proactively initiates conversations for health check-ins
- Provides personalized health, wellness, and fitness suggestions
- Returns assistant message + metadata
- NO database queries directly
- NO hardcoded text - all text generated by AI
"""

from typing import Any, Dict, Mapping, Optional
from sqlalchemy.orm import Session
from backend.app.core.conversation.stages import ConversationStage, get_stage, transition_stage
from backend.app.core.conversation.memory import ConversationMemory
from backend.app.core.conversation.context import ConversationContext
from backend.app.core.conversation.prompts import ConversationPrompts
from backend.app.models import User

_USER_KNOWLEDGE_MAX_CHARS = 1200
_NOTIFICATION_CONTEXT_MAX_CHARS = 2000


def _format_notification_context_block(notification_context: Optional[Mapping[str, Any]]) -> Optional[str]:
    """Format safe notification context for internal GPT system prompt injection."""
    if not notification_context:
        return None

    lines = [
        "[NOTIFICATION_CONTEXT]",
        "The user opened chat from a prior notification. Continue naturally from this context.",
        "Do not provide medical diagnosis, prescribe treatments, or suggest medication dose changes.",
        "If risk is high or critical, encourage contacting a qualified clinician when appropriate.",
    ]

    for key in (
        "category",
        "template_key",
        "risk_level",
        "source_type",
        "source_id",
        "notification_title",
        "notification_summary",
    ):
        value = notification_context.get(key)
        if value is not None and str(value).strip():
            lines.append(f"{key}: {str(value).strip()[:256]}")

    hints = notification_context.get("context_hints")
    if isinstance(hints, dict):
        for hint_key, hint_value in hints.items():
            if hint_value is not None and str(hint_value).strip():
                lines.append(f"hint_{hint_key}: {str(hint_value).strip()[:256]}")

    text = "\n".join(lines)
    if len(text) > _NOTIFICATION_CONTEXT_MAX_CHARS:
        text = text[: _NOTIFICATION_CONTEXT_MAX_CHARS - 3] + "..."
    return text


def _build_user_knowledge_context(db: Session, user_id: int) -> Optional[str]:
    """Load UserProfileKnowledge + UserFact; return [USER_PROFILE] string (max 1200 chars) or None."""
    try:
        from backend.app import models
        lines = []
        profile = (
            db.query(models.UserProfileKnowledge)
            .filter(models.UserProfileKnowledge.user_id == user_id)
            .first()
        )
        if profile:
            if profile.baseline_summary and profile.baseline_summary.strip():
                lines.append("baseline: " + profile.baseline_summary.strip())
            if profile.goals_json and profile.goals_json.strip():
                lines.append("goals: " + profile.goals_json.strip()[:300])
            if profile.constraints_json and profile.constraints_json.strip():
                lines.append("constraints: " + profile.constraints_json.strip()[:300])
            if profile.preferences_json and profile.preferences_json.strip():
                lines.append("preferences: " + profile.preferences_json.strip()[:300])
        facts = (
            db.query(models.UserFact)
            .filter(models.UserFact.user_id == user_id)
            .order_by(models.UserFact.updated_at.desc())
            .limit(30)
            .all()
        )
        fact_parts = []
        for f in facts:
            val = (f.value_json or "").strip()
            if len(val) > 80:
                val = val[:77] + "..."
            fact_parts.append(f"{f.key}={val}")
        if fact_parts:
            lines.append("facts: " + "; ".join(fact_parts))
        if not lines:
            return None
        text = "[USER_PROFILE]\n" + "\n".join(lines)
        if len(text) > _USER_KNOWLEDGE_MAX_CHARS:
            text = text[:_USER_KNOWLEDGE_MAX_CHARS - 3] + "..."
        return text
    except Exception as e:
        print(f"[BRAIN WARNING] User knowledge load failed (non-critical): {e}")
        return None


def _maybe_append_local_rag_context(messages: list, db, user_id: int, user_message: str, language: str) -> None:
    """Stage 17.5: Append [LOCAL_CONTEXT] block when RAG_LOCAL_ENABLED. No-op otherwise."""
    import os
    if not os.environ.get("RAG_LOCAL_ENABLED", "false").lower() in ("true", "1", "yes"):
        return
    try:
        from backend.app.services.local_rag.provider_router import retrieve as rag_retrieve
        result = rag_retrieve(db, user_id, user_message or "chat", language)
        if result.combined_text and len(result.combined_text.strip()) > 10:
            block = "[LOCAL_CONTEXT]\n" + result.combined_text.strip()
            messages.append({"role": "system", "content": block})
    except Exception:
        pass


def _maybe_append_rag_context_v1(
    messages: list,
    db,
    user_id: int,
    user_message: str,
    language: str,
    rag_context_max_chars: int = 1200,
) -> None:
    """
    Stage 23 Step 5: Optional facts-anchored [RAG_CONTEXT] block.
    Builds RagContextPack; if rag_allowed(user_message), appends serialized pack + optional
    local RAG retrieval (capped). Else appends short safety note. Fail-open.
    """
    import os
    try:
        from backend.app.services.rag_context import (
            build_rag_context_pack,
            rag_allowed,
            serialize_rag_pack_for_context,
        )
    except ImportError:
        try:
            from app.services.rag_context import (
                build_rag_context_pack,
                rag_allowed,
                serialize_rag_pack_for_context,
            )
        except ImportError:
            return
    try:
        rag_pack = build_rag_context_pack(db, user_id, fallback_language=language)
        lang = rag_pack.language or language or "en"
        if not rag_allowed(user_message or "", lang):
            safety_note = (
                "[RAG_CONTEXT]\nGeneral info only. If this is a medical emergency or serious concern, "
                "please contact a clinician or emergency services."
            )
            messages.append({"role": "system", "content": safety_note})
            return
        summary = serialize_rag_pack_for_context(rag_pack, max_chars=rag_context_max_chars)
        content = summary
        if os.environ.get("RAG_LOCAL_ENABLED", "false").lower() in ("true", "1", "yes"):
            try:
                from backend.app.services.local_rag.provider_router import retrieve as rag_retrieve
                result = rag_retrieve(db, user_id, user_message or "chat", lang)
                if result and getattr(result, "combined_text", None) and result.combined_text.strip():
                    extra = result.combined_text.strip()[:800]
                    content = (summary + "\n" + extra).strip()
            except Exception:
                pass
        if len(content) > rag_context_max_chars:
            content = content[: rag_context_max_chars - 3] + "..."
        if content.strip():
            messages.append({"role": "system", "content": "[RAG_CONTEXT]\n" + content.strip()})
    except Exception as e:
        print(f"[BRAIN WARNING] RAG context v1 failed (non-critical): {e}")


def _gate3_check_emergency_short_circuit(user_message: str, language: str) -> Optional[str]:
    """Gate 3: fixed emergency template — no creative LLM."""
    try:
        from backend.app.services.gate3.safety_core import RiskClassifier, SafetyPolicy
        risk = RiskClassifier().classify(user_message or "", language or "fa")
        if risk.risk_level == "emergency":
            return SafetyPolicy().response_for_level("emergency", language or "fa")
        if risk.risk_level == "high":
            return SafetyPolicy().response_for_level("high", language or "fa")
    except Exception as e:
        print(f"[BRAIN WARNING] Gate3 emergency check failed (non-critical): {e}")
    return None


def _maybe_append_gate3_care_context(messages: list, db, user_id: int, user_message: str, language: str) -> None:
    """Gate 3: canonical care context for medical/care intents only."""
    try:
        from backend.app.services.gate3.medical_intent import is_medical_care_intent
        from backend.app.services.gate3.care_intelligence import build_care_context
        if not is_medical_care_intent(user_message, language):
            return
        ctx = build_care_context(db, user_id, language, query_hint=user_message)
        # Compact block — no raw chat, no caregiver phone
        lines = ["[CARE_CONTEXT] Canonical user care data (educational use only):"]
        if ctx.get("goals"):
            lines.append("Goals: " + ", ".join(g["title"] for g in ctx["goals"][:3] if g.get("title")))
        if ctx.get("restrictions"):
            lines.append("Restrictions: " + ", ".join(r["title"] for r in ctx["restrictions"][:3] if r.get("title")))
        if ctx.get("upcoming_events"):
            lines.append("Upcoming: " + "; ".join(
                f"{e.get('title')} ({e.get('event_type')})" for e in ctx["upcoming_events"][:3]
            ))
        snippets = ctx.get("knowledge_snippets") or []
        if snippets:
            lines.append("Curated knowledge (cite sources):")
            for sn in snippets[:2]:
                cit = sn.get("citation") or {}
                lines.append(f"- [{cit.get('label', 'source')}] {sn.get('content', '')[:200]}")
        block = "\n".join(lines)[:1200]
        messages.append({"role": "system", "content": block})
    except Exception as e:
        print(f"[BRAIN WARNING] Gate3 care context failed (non-critical): {e}")


def _gate3_validate_assistant_response(text: str, language: str) -> str:
    try:
        from backend.app.services.gate3.safety_validator import validate_response_text
        from backend.app.services.gate3.emergency_templates import get_template
        safe, _code = validate_response_text(text or "")
        if not safe:
            return get_template("safe_fallback", language or "fa")
    except Exception:
        pass
    return text


def _pack_to_prompt_dict(pack) -> Dict:
    """Convert UserContextPack (or None) to a small dict for prompt usage. Safe attributes only."""
    if pack is None:
        return {}
    qh = getattr(pack, "quiet_hours", None)
    qh_start = getattr(qh, "start", None) if qh else None
    qh_end = getattr(qh, "end", None) if qh else None
    goals = getattr(pack, "goals", None)
    goals_items = getattr(goals, "items", []) if goals else []
    lifestyle = getattr(pack, "lifestyle", None)
    lifestyle_text = getattr(lifestyle, "text", None) if lifestyle else None
    return {
        "preferred_name": getattr(pack, "preferred_name", None),
        "language": getattr(pack, "language", None),
        "timezone": getattr(pack, "timezone", None),
        "quiet_hours": {"start": qh_start, "end": qh_end},
        "engagement_level": getattr(pack, "engagement_level", None),
        "goals_items": goals_items if isinstance(goals_items, list) else [],
        "lifestyle_text": lifestyle_text,
        "daily_memory_summary": getattr(pack, "daily_memory_summary", None),
        "birth_year": getattr(pack, "birth_year", None),
        "sex": getattr(pack, "sex", None),
        "addressing_preference": getattr(pack, "addressing_preference", None),
    }


def _build_user_context_block(pack) -> str:
    """Build a short system-only context block (max ~8 lines). No sensitive raw logs."""
    if pack is None:
        return ""
    lines = ["[USER_CONTEXT]"]
    if getattr(pack, "preferred_name", None) and str(pack.preferred_name).strip():
        lines.append("Preferred name: " + str(pack.preferred_name).strip())
    if getattr(pack, "birth_year", None):
        lines.append("Birth year: " + str(pack.birth_year))
    if getattr(pack, "sex", None) and str(pack.sex).strip():
        lines.append("Sex: " + str(pack.sex).strip())
    if getattr(pack, "addressing_preference", None) and str(pack.addressing_preference).strip():
        lines.append("Addressing preference: " + str(pack.addressing_preference).strip())
    goals = getattr(pack, "goals", None)
    if goals and getattr(goals, "items", None):
        items = [str(x) for x in goals.items if x][:5]
        if items:
            lines.append("Goals: " + ", ".join(items))
    lifestyle = getattr(pack, "lifestyle", None)
    if lifestyle and getattr(lifestyle, "text", None) and str(lifestyle.text).strip():
        t = str(lifestyle.text).strip()[:200]
        if "\n" in t:
            t = t.split("\n")[0]
        lines.append("Lifestyle: " + t)
    daily = getattr(pack, "daily_memory_summary", None)
    if daily and str(daily).strip():
        lines.append("Recent: " + str(daily).strip()[:150])
    if len(lines) <= 1:
        return ""
    return "\n".join(lines[:9])


def _redact_secrets(text: str) -> str:
    """Mask likely API key fragments before logging."""
    import re

    redacted = re.sub(r"sk-[A-Za-z0-9_-]{8,}", "sk-***", text or "")
    return re.sub(r"(api[_-]?key\s*[:=]\s*)\S+", r"\1***", redacted, flags=re.IGNORECASE)


def _log_gpt_failure(exc: BaseException, *, where: str) -> None:
    """Structured GPT failure log without leaking secrets."""
    print(
        f"[BRAIN GPT_FAILURE] where={where} "
        f"error_type={type(exc).__name__} "
        f"message={_redact_secrets(str(exc))[:300]}"
    )


def _is_gpt_related_error(exc: BaseException) -> bool:
    """True when the failure should surface as gpt_failure (502) from interact router."""
    error_str = str(exc).lower()
    error_type_name = type(exc).__name__.lower()
    return (
        "openai" in error_str
        or "api key" in error_str
        or "authentication" in error_str
        or "rate limit" in error_str
        or "gpt" in error_str
        or "completion" in error_str
        or "openai" in error_type_name
        or "authenticationerror" in error_type_name
        or "apierror" in error_type_name
    )


class ConversationBrain:
    """Central decision engine for all conversation interactions"""
    
    def __init__(self, db: Session, language: str = "en"):
        self.db = db
        self.language = language
        self.memory = ConversationMemory(db)
        self.prompts = ConversationPrompts(language)
    
    def process_message(
        self,
        user_id: int,
        user_message: str,
        user_name: Optional[str] = None,
        *,
        notification_context: Optional[dict] = None,
    ) -> Dict[str, any]:
        """
        Process user message and generate Sedi's response.
        
        Flow:
        1. Get current conversation stage
        2. Build conversation context
        3. Generate response using prompts
        4. Save conversation to memory
        5. Check for stage transition
        6. Return response with metadata
        
        Args:
            user_id: User ID
            user_message: User's message
        
        Returns:
            Dict with:
            - message: Sedi's response text
            - language: Language code
            - stage: Current conversation stage
            - metadata: Optional metadata (tone, intent, etc.)
        """
        # TEMP DEBUG: Log entry
        print(f"[BRAIN DEBUG] ===== PROCESSING MESSAGE =====")
        print(f"[BRAIN DEBUG] user_id={user_id}, message={user_message[:50]}...")
        
        try:
            # Validate user exists
            user = self.db.query(User).filter(User.id == user_id).first()
            if not user:
                print(f"[BRAIN DEBUG] ERROR: User not found")
                return {
                    "message": self._get_error_message("user_not_found"),
                    "language": self.language,
                    "stage": None,
                    "error": "User not found"
                }
            
            # EXPERIENCE STABILITY: Strict orchestration order
            # 1. IDENTIFY: Ensure user_id is valid (already validated above)
            # 2. LOAD: Get current state (stage, memory count, facts)
            current_stage = get_stage(user_id, self.db)
            current_memory_count = self.memory.get_conversation_count(user_id)
            print(f"[BRAIN DEBUG] Current stage: {current_stage.value}, memory_count: {current_memory_count}")
            
            # 3. BUILD MESSAGES: Build messages explicitly without context dependency
            from backend.app.core.conversation.prompts import client as gpt_client, build_system_prompt_with_context
            from backend.app.core.conversation.persona_policy_v1 import PersonaPolicyV1

            # Stage 23 Step 3: User-aware system prompt (Persona v1 + context block). Fail-open if context fetch fails.
            pack = None
            try:
                from backend.app.services.user_context import UserContextService
                pack = UserContextService(self.db).get_user_context(user_id)
            except Exception as ctx_err:
                print(f"[BRAIN WARNING] UserContext fetch failed (non-critical, proceeding): {ctx_err}")

            lang = PersonaPolicyV1.resolve_language(
                (getattr(pack, "language", None) if pack else None) or self.language
            )
            preferred_name = getattr(pack, "preferred_name", None) if pack else None
            context_block = _build_user_context_block(pack)
            system_prompt_content = build_system_prompt_with_context(lang, preferred_name, context_block)

            messages = [
                {"role": "system", "content": system_prompt_content}
            ]
            # User Knowledge: stable baseline + facts (compact, after main system, before history)
            user_knowledge_str = _build_user_knowledge_context(self.db, user_id)
            if user_knowledge_str:
                messages.append({"role": "system", "content": user_knowledge_str})

            # Stage 17.5: Optional Local RAG context (gated; no behavior change when disabled)
            _maybe_append_local_rag_context(messages, self.db, user_id, user_message, self.language)

            # Stage 23 Step 5: Facts-anchored RAG context (fail-open; medical risk gate)
            _maybe_append_rag_context_v1(messages, self.db, user_id, user_message, lang)

            # Gate 3: care context for medical intents (canonical stores only)
            _maybe_append_gate3_care_context(messages, self.db, user_id, user_message, lang)

            notification_block = _format_notification_context_block(notification_context)
            if notification_block:
                messages.append({"role": "system", "content": notification_block})

            # Optionally append history if available (non-blocking)
            try:
                recent_messages = self.memory.get_recent_messages(user_id, limit=10)
                for msg in reversed(recent_messages):  # Oldest first
                    if msg.user_message and msg.sedi_response:
                        messages.append({"role": "user", "content": msg.user_message})
                        messages.append({"role": "assistant", "content": msg.sedi_response})
            except Exception as history_error:
                # Memory failure is non-critical - continue without history
                print(f"[BRAIN WARNING] Could not load history (non-critical): {history_error}")
            
            # Always append current user message
            messages.append({"role": "user", "content": user_message})
            
            print(f"[BRAIN DEBUG] Messages built - count: {len(messages)}")
            
            # Check if we need to extract user name from conversation
            # Build minimal context_data for helper methods only
            minimal_context = {
                "user_id": user_id,
                "stage": current_stage.value,
                "conversation_count": current_memory_count,
                "recent_messages": []
            }
            try:
                recent_messages_list = self.memory.get_recent_messages(user_id, limit=5)
                minimal_context["recent_messages"] = [
                    {"sedi": msg.sedi_response or ""} for msg in recent_messages_list
                ]
            except:
                pass
            detected_name = self._extract_name_from_message(user_id, user_message, current_stage, minimal_context)

            # Gate 3: emergency/high-risk short-circuit before GPT
            gate3_template = _gate3_check_emergency_short_circuit(user_message, lang)
            if gate3_template:
                sedi_response = gate3_template
                print("[BRAIN] Gate3 safety short-circuit applied")
            else:
                # 4. GENERATE: Call GPT directly with messages
                print(f"[BRAIN] ===== BEFORE GPT CALL =====")
                print(f"[BRAIN] User ID: {user_id}")
                print(f"[BRAIN] User message: '{user_message[:100]}...'")
                print(f"[BRAIN] Language: {self.language}")
                print(f"[BRAIN] Stage: {current_stage.value}")
                print(f"[BRAIN] Messages count: {len(messages)}")
                print(f"[BRAIN] ===== END BEFORE GPT =====")
                try:
                    completion = gpt_client.responses.create(
                        model="gpt-4o-mini",
                        input=messages
                    )
                    sedi_response = completion.output_text.strip()
                    sedi_response = _gate3_validate_assistant_response(sedi_response, lang)
                    print(f"[BRAIN DEBUG] Response generated (length={len(sedi_response)})")
                except Exception as gpt_exception:
                    _log_gpt_failure(gpt_exception, where="process_message.responses_create")
                    raise

            # STEP 4: SAVE: Save conversation to memory (updates memory_count)
            # CRITICAL: Memory is OPTIONAL - memory failure must NOT block chat
            mem = None
            try:
                mem = self.memory.save_conversation(
                    user_id=user_id,
                    user_message=user_message,
                    sedi_response=sedi_response,
                    language=self.language
                )
                print(f"[BRAIN DEBUG] ✅ Conversation saved - new memory_count: {self.memory.get_conversation_count(user_id)}")
            except Exception as memory_error:
                # STEP 4: Memory failure is non-critical - log but continue
                print(f"[BRAIN WARNING] ⚠️ Memory save failed (non-critical): {memory_error}")
                print(f"[BRAIN WARNING] Chat response will still be returned to user")
                import traceback
                print(f"[BRAIN WARNING] Memory error traceback: {traceback.format_exc()}")
                # Continue - don't block chat response

            # Gate 2: KC extraction ingress (replaces legacy user_fact_candidates primary writes)
            try:
                from backend.app.services.knowledge.conversation_extraction_service import process_message as kc_process_message
                kc_process_message(
                    db=self.db,
                    user_id=user_id,
                    text=user_message,
                    language=self.language or "fa",
                    source_message_id=str(mem.id) if mem else None,
                )
            except Exception as extract_err:
                print(f"[BRAIN] KC extract (non-critical): {extract_err}")

            # 6. TRANSITION: Check for stage transition (AFTER save - uses updated memory_count)
            new_stage = transition_stage(current_stage, user_id, self.db)
            print(f"[BRAIN DEBUG] Stage transition: {current_stage.value} -> {new_stage.value}")
            
            # Get updated conversation count
            updated_conversation_count = self.memory.get_conversation_count(user_id)
            
            print(f"[BRAIN DEBUG] ===== MESSAGE PROCESSED =====")
            
            # Build metadata with updated state
            metadata = {
                "stage": new_stage.value,
                "conversation_count": updated_conversation_count,
                "tone": self._infer_tone(sedi_response),
                "stage_transitioned": new_stage != current_stage
            }
            
            return {
                "message": sedi_response,
                "language": self.language,
                "stage": new_stage.value,  # Return NEW stage (after save and transition)
                "metadata": metadata,
                "detected_name": detected_name  # Name detected from conversation (to update frontend)
            }
        except Exception as e:
            # Log the error for debugging
            print(f"[BRAIN ERROR] Exception in process_message: {e}")
            print(f"[BRAIN ERROR] Exception type: {type(e).__name__}")
            import traceback
            print(f"[BRAIN ERROR] Traceback: {traceback.format_exc()}")

            if _is_gpt_related_error(e):
                _log_gpt_failure(e, where="process_message.outer_re_raise")
                raise

            # Non-GPT failures: return a user-friendly error message (HTTP 200 legacy path)
            error_messages = {
                "en": "I'm sorry, I encountered an error processing your message. Please try again.",
                "fa": "متاسفم، در پردازش پیام شما خطایی رخ داد. لطفاً دوباره تلاش کنید.",
                "ar": "عذراً، حدث خطأ في معالجة رسالتك. يرجى المحاولة مرة أخرى."
            }
            
            error_message = error_messages.get(self.language, error_messages["en"])
            
            # Try to get current stage for response
            try:
                current_stage = get_stage(user_id, self.db)
                stage_value = current_stage.value
            except:
                stage_value = "FIRST_CONTACT"
            
            return {
                "message": error_message,
                "language": self.language,
                "stage": stage_value,
                "metadata": {
                    "error": True,
                    "error_type": type(e).__name__
                }
            }
    
    def get_initial_message(self, user_id: int, user_name: Optional[str], language: str) -> str:
        """
        Generate initial message after onboarding.
        Uses GPT with Sedi's knowledge base to introduce Sedi and explain what she does.
        
        Args:
            user_id: User ID from database
            user_name: User's name from frontend (optional, for personalization)
            language: Language code ('en', 'fa', 'ar')
        """
        from backend.app.core.conversation.sedi_knowledge_base import build_complete_sedi_context
        # VERIFY: Same client used in onboarding and chat
        from backend.app.core.conversation.prompts import client as gpt_client
        print(f"[BRAIN] ✅ Using same OpenAI client as chat (verified: same client from prompts.py)")
        
        # CRITICAL: Use user_name if provided, otherwise use "friend" as fallback
        display_name = user_name.strip() if user_name and user_name.strip() else "friend"
        print(f"[BRAIN] get_initial_message: user_id={user_id}, user_name='{user_name}', display_name='{display_name}', language={language}")
        
        # CRITICAL: Initial greeting MUST be in English (for context)
        # User's preferred language will be used for subsequent responses
        # Get Sedi's complete context in English (core thinking language)
        sedi_context = build_complete_sedi_context("en")
        
        # Build system prompt - ALWAYS in English for initial greeting
        system_prompt = f"""{sedi_context}

You are Sedi, speaking with {display_name} for the first time after they completed onboarding.

Your role is to:
1. Introduce yourself warmly
2. Explain who you are (Sedi, AI-powered health care assistant)
3. Explain your purpose: How you help improve their quality of life through:
   - Personalized health care suggestions
   - Lifestyle improvement recommendations
   - Continuous monitoring of daily health data via smart devices
4. Explain how you work: You learn about their lifestyle through natural conversation and use smart devices to track vital signs (heart rate, temperature, SpO2) continuously
5. Be warm, friendly, and engaging
6. Keep it concise (2-3 sentences, max 200 characters)
7. {"Use their name naturally in the greeting" if display_name != "friend" else "Greet them warmly"}

CRITICAL: This is the initial greeting message. It MUST be in English.
The user's preferred language ({language}) will be used for all subsequent responses.
"""
        
        # Build user prompt - ALWAYS in English for initial greeting
        user_prompt = f"Introduce yourself to {display_name} and explain what you do as their health care assistant. Be warm and welcoming." + (f" Use their name: {display_name}." if display_name != "friend" else "")
        
        try:
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ]
            
            # ===== GPT_ONBOARDING_START - HARD LOGGING =====
            print("=" * 80)
            print("[GPT_ONBOARDING_START] ===== CALLING GPT FOR ONBOARDING GREETING =====")
            print(f"[GPT_ONBOARDING_START] Model: gpt-4o-mini")
            print(f"[GPT_ONBOARDING_START] User ID: {user_id}")
            print(f"[GPT_ONBOARDING_START] User name: {user_name}")
            print(f"[GPT_ONBOARDING_START] Display name: {display_name}")
            print(f"[GPT_ONBOARDING_START] Language: {language}")
            print(f"[GPT_ONBOARDING_START] System prompt length: {len(system_prompt)} characters")
            print(f"[GPT_ONBOARDING_START] User prompt length: {len(user_prompt)} characters")
            import os
            print(f"[GPT_ONBOARDING_START] API key available: {bool(os.getenv('OPENAI_API_KEY'))}")
            print(f"[GPT_ONBOARDING_START] API key length: {len(os.getenv('OPENAI_API_KEY', ''))}")
            print("=" * 80)
            
            response = gpt_client.chat.completions.create(
                model="gpt-4o-mini",
                messages=messages,
                temperature=0.7,
                max_tokens=200,
            )
            
            greeting_text = response.choices[0].message.content.strip()
            
            # ===== GPT_ONBOARDING_SUCCESS - HARD LOGGING =====
            print("=" * 80)
            print("[GPT_ONBOARDING_SUCCESS] ===== GPT ONBOARDING CALL SUCCESSFUL =====")
            print(f"[GPT_ONBOARDING_SUCCESS] Response length: {len(greeting_text)} characters")
            print(f"[GPT_ONBOARDING_SUCCESS] Response preview: {greeting_text[:150]}...")
            print("=" * 80)
            
            return greeting_text
        except Exception as e:
            # ===== GPT_ONBOARDING_ERROR - HARD LOGGING =====
            print("=" * 80)
            print("[GPT_ONBOARDING_ERROR] ===== GPT ONBOARDING CALL FAILED =====")
            print(f"[GPT_ONBOARDING_ERROR] Exception type: {type(e).__name__}")
            print(f"[GPT_ONBOARDING_ERROR] Exception message: {str(e)}")
            import traceback
            print(f"[GPT_ONBOARDING_ERROR] Full stack trace:")
            print(traceback.format_exc())
            print("=" * 80)
            print(f"[BRAIN INITIAL MESSAGE ERROR] {e}")
            print(f"[BRAIN INITIAL MESSAGE ERROR] Traceback: {traceback.format_exc()}")
            # Fallback message - use display_name (already set to "friend" if None)
            fallback = {
                "en": f"Hello {display_name}! I'm Sedi, your AI-powered health care assistant. I'm here to help improve your quality of life through personalized health suggestions, lifestyle improvements, and continuous monitoring via smart devices.",
                "fa": f"سلام {display_name}! من صدی هستم، دستیار مراقبت سلامت شما با هوش مصنوعی. من اینجا هستم تا از طریق پیشنهادهای شخصی‌سازی شده سلامت، بهبود سبک زندگی و پایش پیوسته از طریق گجت‌های هوشمند به بهبود کیفیت زندگی‌تان کمک کنم.",
                "ar": f"مرحباً {display_name}! أنا صدي، مساعد رعاية صحية الخاص بك المدعوم بالذكاء الاصطناعي. أنا هنا لمساعدتك على تحسين جودة حياتك من خلال اقتراحات صحية مخصصة وتحسينات نمط الحياة ومراقبة مستمرة عبر الأجهزة الذكية."
            }
            # Fallback message - ALWAYS in English for initial greeting
            return fallback["en"]
    
    def get_greeting(self, user_id: int, user_name: Optional[str] = None) -> Dict[str, any]:
        """
        Generate initial greeting for user.
        
        Used when user first opens chat or returns after absence.
        
        Args:
            user_id: User ID
            user_name: Optional user name from frontend (for personalization)
        
        Returns:
            Dict with greeting message and metadata
        """
        print(f"[BRAIN] get_greeting: user_id={user_id}, user_name='{user_name}'")
        
        # Get current stage
        stage = get_stage(user_id, self.db)
        
        # Build context - pass user_name from frontend
        context = ConversationContext(
            user_id=user_id,
            stage=stage,
            memory=self.memory,
            user_name=user_name  # CRITICAL: Pass name from frontend
        )
        context_data = context.build()
        print(f"[BRAIN] Context built - user_name in context: '{context_data.get('user_name')}'")
        
        # Generate greeting based on stage
        greeting = self._generate_greeting(context_data, stage)
        
        return {
            "message": greeting,
            "language": self.language,
            "stage": stage.value,
            "metadata": {
                "type": "greeting",
                "stage": stage.value
            }
        }
    
    def _generate_greeting(
        self,
        context: Dict[str, any],
        stage: ConversationStage
    ) -> str:
        """
        Generate greeting message - Sedi introduces herself and explains how she can help.
        
        CRITICAL: Sedi must be a conversation initiator and explain:
        - Who she is (health care assistant)
        - How she can improve user's quality of life
        - Through health care suggestions, lifestyle improvements, and smart device monitoring
        """
        user_name = context.get("user_name") or "friend"
        time_since = context.get("time_since_last")
        engagement_level = self._determine_engagement_level(context)
        
        # Build comprehensive greeting prompt based on stage
        if stage == ConversationStage.FIRST_CONTACT:
            # FIRST CONTACT: Use GPT with Sedi's knowledge base for introduction
            # This ensures Sedi introduces herself properly based on her knowledge
            user_id = context.get("user_id")
            if user_id:
                user = self.db.query(User).filter(User.id == user_id).first()
                if user:
                    return self.get_initial_message(user_id, user_name, self.language)
            # Fallback if user_id not available
            return self.prompts._get_fallback_response(stage)
        elif time_since:
            # User returning after absence - be warm and check in
            greeting_prompt = {
                "en": f"""Greet {user_name} warmly. You haven't talked in a while. Remind them briefly who you are (Sedi, their health care assistant) and that you're here to help improve their quality of life through health monitoring and lifestyle suggestions. Be warm but not overwhelming. Ask how they've been.""",
                "fa": f"""با {user_name} گرم سلام کن. مدتی است که حرف نزده‌اید. مختصر یادآوری کن که تو کیستی (صدی، دستیار مراقبت سلامت‌شان) و اینجا هستی تا از طریق نظارت سلامت و پیشنهادهای سبک زندگی کیفیت زندگی‌شان را بهبود دهی. گرم باش اما نه بیش از حد. بپرس چطور بوده‌اند.""",
                "ar": f"""حي {user_name} بحرارة. لم تتحدثا منذ فترة. ذكره باختصار من أنت (صدي، مساعد رعاية صحية) وأنك هنا لمساعدتهم على تحسين جودة حياتهم من خلال مراقبة الصحة واقتراحات نمط الحياة. كن دافئاً لكن ليس ساحقاً. اسأل كيف كانوا."""
            }
        else:
            # Regular greeting - proactive health check-in
            greeting_prompt = {
                "en": f"""Greet {user_name} warmly. As their health care assistant, proactively check in on their wellness. You can mention their health data if available, or ask about their day. Be conversational and supportive. Keep it brief (1-2 sentences, max 150 characters).""",
                "fa": f"""با {user_name} گرم سلام کن. به عنوان دستیار مراقبت سلامت‌شان، به صورت فعالانه چک‌آپ تندرستی کن. می‌توانی به داده‌های سلامت‌شان اشاره کنی اگر در دسترس است، یا درباره روزشان بپرسی. گفتگویی و حمایت‌کننده باش. مختصر نگه دار (1-2 جمله، حداکثر 150 کاراکتر).""",
                "ar": f"""حي {user_name} بحرارة. كمساعد رعاية صحية، تحقق بشكل استباقي من صحتهم. يمكنك ذكر بيانات صحتهم إذا كانت متاحة، أو السؤال عن يومهم. كن محادثاً وداعماً. اجعلها مختصرة (1-2 جملة، بحد أقصى 150 حرف)."""
            }
        
        # For non-FIRST_CONTACT stages, use GPT for greeting
        try:
            system_prompt = self.prompts._build_system_prompt(
                stage,
                user_name,
                context.get("conversation_count", 0),
                engagement_level
            )
            
            prompt_text = greeting_prompt.get(self.language, greeting_prompt["en"])
            
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt_text}
            ]
            
            from backend.app.core.conversation.prompts import client as gpt_client
            response = gpt_client.chat.completions.create(
                model="gpt-4o-mini",
                messages=messages,
                temperature=0.8,
                max_tokens=300,
            )
            
            return response.choices[0].message.content.strip()
            
        except Exception as e:
            print(f"[BRAIN GREETING ERROR] {e}")
            return self.prompts._get_fallback_response(stage)
    
    def _determine_engagement_level(self, context: Dict[str, any]) -> str:
        """
        Determine user engagement level based on conversation patterns.
        
        MINIMAL logic - selection only, no complex calculations.
        
        Returns:
            "low": User rarely responds, long gaps
            "normal": Standard engagement
            "high": User is very engaged, frequent responses
        """
        conversation_count = context.get("conversation_count", 0)
        time_since_last = context.get("time_since_last")
        recent_messages = context.get("recent_messages", [])
        
        # Low engagement indicators
        if conversation_count > 0:
            if time_since_last:
                # Parse time delta (format: "X days, Y:Z:W")
                try:
                    days = 0
                    if "day" in time_since_last.lower():
                        days = int(time_since_last.split()[0])
                    if days > 7:  # More than a week
                        return "low"
                except:
                    pass
            
            # Check recent message frequency
            if len(recent_messages) < 2 and conversation_count > 5:
                return "low"
        
        # High engagement indicators
        if len(recent_messages) >= 3 and conversation_count > 3:
            # User has been actively chatting
            return "high"
        
        # Default to normal
        return "normal"
    
    def _infer_tone(self, message: str) -> str:
        """Infer tone from message (simple heuristic)"""
        message_lower = message.lower()
        if any(word in message_lower for word in ["!", "urgent", "important"]):
            return "urgent"
        elif any(word in message_lower for word in ["?", "wonder", "curious"]):
            return "curious"
        elif any(word in message_lower for word in ["😊", "happy", "glad", "great"]):
            return "warm"
        else:
            return "neutral"
    
    def _extract_name_from_message(
        self,
        user_id: int,
        user_message: str,
        stage: ConversationStage,
        context: Dict[str, any]
    ) -> Optional[str]:
        """
        Extract user name from conversation message if provided.
        
        Returns detected name if found, None otherwise.
        Name is not saved to database - frontend will update UserProfile.
        """
        # Check if this looks like a name response
        user_message_clean = user_message.strip()
        conversation_count = context.get("conversation_count", 0)
        
        # Check if last Sedi message asked for name or user wants to change name
        recent_messages = context.get("recent_messages", [])
        last_sedi_message = recent_messages[-1].get("sedi", "") if recent_messages else ""
        
        name_keywords = [
            "name", "اسم", "اسمك", "اسمك", "what's your name", "اسم شما", "ما اسمك",
            "اسمتون", "اسمت", "اسمتون را", "اسم شما چیه", "اسم شما چیست", "اسمت چیه", "اسمت چیست",
            "میتونم اسمتون", "میتونم اسمت", "بدونم اسمتون", "بدونم اسمت", "بدانم اسمتون", "بدانم اسمت",
            "call me", "من را", "منو", "بگو", "بگو به من"
        ]
        name_was_requested = any(keyword in last_sedi_message.lower() for keyword in name_keywords) if last_sedi_message else False
        
        # Also check if user explicitly says they want to change name
        change_name_keywords = [
            "my name is", "i'm", "i am", "اسم من", "من", "اسمم", "اسم", 
            "call me", "من را", "منو", "بگو", "بگو به من"
        ]
        user_wants_to_change_name = any(keyword in user_message_clean.lower() for keyword in change_name_keywords)
        
        # CRITICAL: Check if password was requested - don't extract name if we're in password flow
        password_keywords = ["password", "رمز", "كلمة مرور", "security", "امنیت", "أمان", "امنیتی"]
        password_requested = any(keyword in last_sedi_message.lower() for keyword in password_keywords) if last_sedi_message else False
        
        # List of common short responses that should NOT be saved as names
        invalid_name_responses = {
            "en": ["good", "fine", "ok", "okay", "yes", "no", "hi", "hello", "hey", "thanks", "thank you", "well", "great", "nice"],
            "fa": ["خوب", "خوبم", "خوبی", "خوبه", "بله", "نه", "سلام", "درود", "ممنون", "تشکر", "عالی", "خوب است"],
            "ar": ["جيد", "حسنا", "نعم", "لا", "مرحبا", "شكرا", "شكراً"]
        }
        invalid_responses = invalid_name_responses.get(self.language, invalid_name_responses["en"])
        all_invalid = []
        for lang_responses in invalid_name_responses.values():
            all_invalid.extend(lang_responses)
        
        is_invalid_response = user_message_clean.lower() in [r.lower() for r in all_invalid]
        
        # Extract name if:
        # 1. Name was requested OR user wants to change name
        # 2. Not in password flow
        # 3. Not an invalid response
        # 4. Looks like a name (reasonable length, no digits, etc.)
        if ((name_was_requested or user_wants_to_change_name) and 
            not password_requested and
            not is_invalid_response and
            2 <= len(user_message_clean) <= 30 and
            not any(char.isdigit() for char in user_message_clean) and
            not any(char in user_message_clean for char in ["?", "؟", "!", "!"])):
            
            # Extract name (first word, clean)
            if user_wants_to_change_name:
                # Extract after keyword
                for kw in change_name_keywords:
                    if kw in user_message_clean.lower():
                        parts = user_message_clean.split(kw, 1)
                        if len(parts) > 1:
                            name = parts[1].strip().split()[0] if parts[1].strip() else None
                            if name and len(name) > 1:
                                print(f"[BRAIN DEBUG] Name detected from change request: {name} for user_id={user_id}")
                                return name
                # If no keyword found, use first word
                name = user_message_clean.split()[0] if user_message_clean.split() else user_message_clean
            else:
                # Direct name response
                name = user_message_clean.split()[0] if user_message_clean.split() else user_message_clean
            
            name = name.strip()
            if name and len(name) > 1:
                print(f"[BRAIN DEBUG] Name detected: {name} for user_id={user_id} (will be sent to frontend)")
                return name
        
        return None
        
        # Check if this looks like a name response
        # (short, no digits, reasonable length, and this is early in conversation)
        user_message_clean = user_message.strip()
        conversation_count = context.get("conversation_count", 0)
        
        # Check if last Sedi message asked for name
        recent_messages = context.get("recent_messages", [])
        last_sedi_message = recent_messages[-1].get("sedi", "") if recent_messages else ""
        
        name_keywords = [
            "name", "اسم", "اسمك", "اسمك", "what's your name", "اسم شما", "ما اسمك",
            "اسمتون", "اسمت", "اسمتون را", "اسم شما چیه", "اسم شما چیست", "اسمت چیه", "اسمت چیست",
            "میتونم اسمتون", "میتونم اسمت", "بدونم اسمتون", "بدونم اسمت", "بدانم اسمتون", "بدانم اسمت"
        ]
        name_was_requested = any(keyword in last_sedi_message.lower() for keyword in name_keywords) if last_sedi_message else False
        
        # CRITICAL: Check if password was requested - don't save name if we're in password flow
        password_keywords = ["password", "رمز", "كلمة مرور", "security", "امنیت", "أمان", "امنیتی"]
        password_requested = any(keyword in last_sedi_message.lower() for keyword in password_keywords) if last_sedi_message else False
        
        # List of common short responses that should NOT be saved as names
        invalid_name_responses = {
            "en": ["good", "fine", "ok", "okay", "yes", "no", "hi", "hello", "hey", "thanks", "thank you", "well", "great", "nice"],
            "fa": ["خوب", "خوبم", "خوبی", "خوبه", "بله", "نه", "سلام", "درود", "ممنون", "تشکر", "عالی", "خوب است", "خوبم", "خوبی", "خوبه", "خوب است", "خوبم", "خوبی", "خوبه"],
            "ar": ["جيد", "حسنا", "نعم", "لا", "مرحبا", "شكرا", "شكراً"]
        }
        invalid_responses = invalid_name_responses.get(self.language, invalid_name_responses["en"])
        # Also check in all languages
        all_invalid = []
        for lang_responses in invalid_name_responses.values():
            all_invalid.extend(lang_responses)
        
        is_invalid_response = user_message_clean.lower() in [r.lower() for r in all_invalid]
        
        # If name was requested and user message looks like a name
        # CRITICAL: Don't save name if password was requested or if it's an invalid response
        # Allow name detection in early conversation (first 5 messages) or if name was explicitly requested
        if (name_was_requested and 
            not password_requested and  # CRITICAL: Don't save name during password flow
            not is_invalid_response and  # CRITICAL: Don't save common responses as names
            conversation_count <= 5 and  # Early in conversation (increased from 2 to 5)
            2 <= len(user_message_clean) <= 30 and  # Reasonable name length
            not any(char.isdigit() for char in user_message_clean) and  # No digits
            not any(char in user_message_clean for char in ["?", "؟", "!", "!"])):  # Not a question/exclamation
            # Extract name (first word, clean)
            name = user_message_clean.split()[0] if user_message_clean.split() else user_message_clean
            name = name.strip()
            
            # Name is no longer stored in database - skip saving
            print(f"[BRAIN DEBUG] Name detected: {name} for user_id={user_id} (not saved to database)")
    
    def _get_error_message(self, error_type: str) -> str:
        """Get error message based on type"""
        error_messages = {
            "user_not_found": {
                "en": "I'm sorry, I couldn't find your account. Please try again.",
                "fa": "متاسفم، نتوانستم حساب کاربری شما را پیدا کنم. لطفاً دوباره تلاش کنید.",
                "ar": "عذراً، لم أتمكن من العثور على حسابك. يرجى المحاولة مرة أخرى."
            }
        }
        
        return error_messages.get(error_type, {}).get(
            self.language,
            error_messages.get(error_type, {}).get("en", "An error occurred.")
        )

